//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UM.CustomFx.GratefulPatient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BATCHCONSTITUENTUPDATE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BATCHCONSTITUENTUPDATE()
        {
            this.BATCHCONSTITUENTUPDATEADDRESSES = new HashSet<BATCHCONSTITUENTUPDATEADDRESS>();
            this.BATCHCONSTITUENTUPDATEEMAILADDRESSES = new HashSet<BATCHCONSTITUENTUPDATEEMAILADDRESS>();
            this.BATCHCONSTITUENTUPDATEPHONES = new HashSet<BATCHCONSTITUENTUPDATEPHONE>();
        }
    
        public System.Guid ID { get; set; }
        public System.Guid BATCHID { get; set; }
        public int SEQUENCE { get; set; }
        public Nullable<System.Guid> PRIMARYRECORDID { get; set; }
        public byte CONSTITUENTTYPECODE { get; set; }
        public string CONSTITUENTTYPE { get; set; }
        public string BIRTHDATE { get; set; }
        public string FIRSTNAME { get; set; }
        public byte GENDERCODE { get; set; }
        public string GENDER { get; set; }
        public bool GIVESANONYMOUSLY { get; set; }
        public string KEYNAME { get; set; }
        public string LOOKUP_ID { get; set; }
        public string MAIDENNAME { get; set; }
        public string MIDDLENAME { get; set; }
        public string NICKNAME { get; set; }
        public Nullable<System.Guid> SUFFIXCODEID { get; set; }
        public Nullable<System.Guid> TITLECODEID { get; set; }
        public string WEBADDRESS { get; set; }
        public bool DECEASED { get; set; }
        public string DECEASEDDATE { get; set; }
        public Nullable<System.Guid> CONSTITUENT_SITEID { get; set; }
        public Nullable<System.Guid> PROSPECTMANAGERFUNDRAISERID { get; set; }
        public Nullable<System.Guid> GROUPTYPEID { get; set; }
        public string GROUPDESCRIPTION { get; set; }
        public Nullable<System.DateTime> GROUPSTARTDATE { get; set; }
        public Nullable<System.Guid> ORG_INDUSTRYCODEID { get; set; }
        public int ORG_NUMEMPLOYEES { get; set; }
        public int ORG_NUMSUBSIDIARIES { get; set; }
        public Nullable<System.Guid> ORG_PARENTCORPID { get; set; }
        public Nullable<System.Guid> MARITALSTATUSCODEID { get; set; }
        public Nullable<System.Guid> SPOUSE_ID { get; set; }
        public Nullable<System.Guid> SPOUSE_TITLECODEID { get; set; }
        public string SPOUSE_FIRSTNAME { get; set; }
        public string SPOUSE_NICKNAME { get; set; }
        public string SPOUSE_MIDDLENAME { get; set; }
        public string SPOUSE_MAIDENNAME { get; set; }
        public string SPOUSE_LASTNAME { get; set; }
        public Nullable<System.Guid> SPOUSE_SUFFIXCODEID { get; set; }
        public string SPOUSE_BIRTHDATE { get; set; }
        public byte SPOUSE_GENDERCODE { get; set; }
        public string SPOUSE_GENDER { get; set; }
        public string SPOUSE_LOOKUPID { get; set; }
        public Nullable<System.Guid> SPOUSE_RELATIONSHIPTYPECODEID { get; set; }
        public Nullable<System.Guid> SPOUSE_RECIPROCALTYPECODEID { get; set; }
        public Nullable<System.Guid> BUSINESS_ID { get; set; }
        public string BUSINESS_ADDRESSBLOCK { get; set; }
        public Nullable<System.Guid> BUSINESS_ADDRESSTYPECODEID { get; set; }
        public string BUSINESS_CART { get; set; }
        public string BUSINESS_CITY { get; set; }
        public Nullable<System.Guid> BUSINESS_COUNTRYID { get; set; }
        public bool BUSINESS_DONOTMAIL { get; set; }
        public Nullable<System.Guid> BUSINESS_DONOTMAILREASONCODEID { get; set; }
        public string BUSINESS_DPC { get; set; }
        public string BUSINESS_EMAILADDRESS { get; set; }
        public Nullable<System.Guid> BUSINESS_EMAILADDRESSTYPECODEID { get; set; }
        public Nullable<System.Guid> BUSINESS_INDUSTRYCODEID { get; set; }
        public string BUSINESS_LOOKUPID { get; set; }
        public string BUSINESS_LOT { get; set; }
        public string BUSINESS_NAME { get; set; }
        public int BUSINESS_NUMEMPLOYEES { get; set; }
        public int BUSINESS_NUMSUBSIDIARIES { get; set; }
        public Nullable<System.Guid> BUSINESS_PARENTCORPID { get; set; }
        public string BUSINESS_PHONENUMBER { get; set; }
        public Nullable<System.Guid> BUSINESS_PHONETYPECODEID { get; set; }
        public Nullable<System.Guid> BUSINESS_RELATIONSHIPTYPECODEID { get; set; }
        public Nullable<System.Guid> BUSINESS_RECIPROCALTYPECODEID { get; set; }
        public Nullable<System.Guid> BUSINESS_STATEID { get; set; }
        public string BUSINESS_WEBADDRESS { get; set; }
        public string BUSINESS_POSTCODE { get; set; }
        public System.Guid ADDEDBYID { get; set; }
        public System.Guid CHANGEDBYID { get; set; }
        public System.DateTime DATEADDED { get; set; }
        public System.DateTime DATECHANGED { get; set; }
        public byte[] TS { get; set; }
        public Nullable<long> TSLONG { get; set; }
        public Nullable<System.Guid> BUSINESS_PHONE_COUNTRYID { get; set; }
        public bool BUSINESS_PRIMARYSOFTCREDITRELATIONSHIPEXISTS { get; set; }
        public decimal BUSINESS_PRIMARYSOFTCREDITMATCHFACTOR { get; set; }
        public Nullable<System.Guid> BUSINESS_PRIMARYRECOGNITIONTYPECODEID { get; set; }
        public bool BUSINESS_RECIPROCALSOFTCREDITRELATIONSHIPEXISTS { get; set; }
        public decimal BUSINESS_RECIPROCALSOFTCREDITMATCHFACTOR { get; set; }
        public Nullable<System.Guid> BUSINESS_RECIPROCALRECOGNITIONTYPECODEID { get; set; }
        public Nullable<System.DateTime> BUSINESS_EMAILADDRESSSTARTDATE { get; set; }
        public bool SPOUSE_PRIMARYSOFTCREDITRELATIONSHIPEXISTS { get; set; }
        public decimal SPOUSE_PRIMARYSOFTCREDITMATCHFACTOR { get; set; }
        public Nullable<System.Guid> SPOUSE_PRIMARYRECOGNITIONTYPECODEID { get; set; }
        public bool SPOUSE_RECIPROCALSOFTCREDITRELATIONSHIPEXISTS { get; set; }
        public decimal SPOUSE_RECIPROCALSOFTCREDITMATCHFACTOR { get; set; }
        public Nullable<System.Guid> SPOUSE_RECIPROCALRECOGNITIONTYPECODEID { get; set; }
        public bool REMOVESPOUSE { get; set; }
        public bool DOMANUALREVIEWFORAUTOMATCH { get; set; }
        public byte DIFFERENTPHONECODE { get; set; }
        public byte NEWPHONEENDDATECODE { get; set; }
        public byte NEWPHONEPRIMARYCODE { get; set; }
        public byte DIFFERENTEMAILCODE { get; set; }
        public byte NEWEMAILENDDATECODE { get; set; }
        public byte NEWEMAILPRIMARYCODE { get; set; }
        public bool USEGLOBALSETTINGS { get; set; }
        public string DIFFERENTEMAIL { get; set; }
        public byte CREATEHISTORICALNAMECODE { get; set; }
        public string CREATEHISTORICALNAME { get; set; }
        public byte NAMECODE { get; set; }
        public byte SIMILARADDRESSCODE { get; set; }
        public byte UNSIMILARADDRESSCODE { get; set; }
        public string UNSIMILARADDRESS { get; set; }
        public byte NEWADDRESSENDDATECODE { get; set; }
        public byte NEWADDRESSPRIMARYCODE { get; set; }
        public byte BIRTHDATERULECODE { get; set; }
        public string NAME { get; set; }
        public string SIMILARADDRESS { get; set; }
        public string NEWADDRESSENDDATE { get; set; }
        public string NEWADDRESSPRIMARY { get; set; }
        public string DIFFERENTPHONE { get; set; }
        public string NEWPHONEENDDATE { get; set; }
        public string NEWPHONEPRIMARY { get; set; }
        public string NEWEMAILENDDATE { get; set; }
        public string NEWEMAILPRIMARY { get; set; }
        public bool REQUESTSNOEMAIL { get; set; }
        public string BIRTHDATERULE { get; set; }
        public bool ROWFROMBATCHUI { get; set; }
        public string ORIGINAL_KEYNAME { get; set; }
        public string ORIGINAL_FIRSTNAME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BATCHCONSTITUENTUPDATEADDRESS> BATCHCONSTITUENTUPDATEADDRESSES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BATCHCONSTITUENTUPDATEEMAILADDRESS> BATCHCONSTITUENTUPDATEEMAILADDRESSES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BATCHCONSTITUENTUPDATEPHONE> BATCHCONSTITUENTUPDATEPHONES { get; set; }
    }
}
