//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UM.CustomFx.GratefulPatient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BATCHREVENUECONSTITUENT
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> EXISTINGCONSTITUENTID { get; set; }
        public string KEYNAME { get; set; }
        public string KEYNAMEPREFIX { get; set; }
        public string FIRSTNAME { get; set; }
        public string MIDDLENAME { get; set; }
        public string MAIDENNAME { get; set; }
        public string NICKNAME { get; set; }
        public Nullable<System.Guid> TITLECODEID { get; set; }
        public Nullable<System.Guid> SUFFIXCODEID { get; set; }
        public byte GENDERCODE { get; set; }
        public string GENDER { get; set; }
        public string BIRTHDATE { get; set; }
        public bool ISORGANIZATION { get; set; }
        public Nullable<System.Guid> MARITALSTATUSCODEID { get; set; }
        public Nullable<System.Guid> INDUSTRYCODEID { get; set; }
        public int NUMEMPLOYEES { get; set; }
        public int NUMSUBSIDIARIES { get; set; }
        public Nullable<System.Guid> PARENTCORPID { get; set; }
        public Nullable<System.Guid> ADDRESSTYPECODEID { get; set; }
        public bool DONOTMAIL { get; set; }
        public Nullable<System.Guid> COUNTRYID { get; set; }
        public Nullable<System.Guid> STATEID { get; set; }
        public string ADDRESSBLOCK { get; set; }
        public string CITY { get; set; }
        public string POSTCODE { get; set; }
        public Nullable<System.Guid> PHONETYPECODEID { get; set; }
        public string NUMBER { get; set; }
        public Nullable<System.Guid> EMAILADDRESSTYPECODEID { get; set; }
        public string EMAILADDRESS { get; set; }
        public Nullable<System.Guid> CURRENTAPPUSERID { get; set; }
        public string WEBADDRESS { get; set; }
        public System.Guid ADDEDBYID { get; set; }
        public System.Guid CHANGEDBYID { get; set; }
        public System.DateTime DATEADDED { get; set; }
        public System.DateTime DATECHANGED { get; set; }
        public byte[] TS { get; set; }
        public Nullable<long> TSLONG { get; set; }
        public bool ISGROUP { get; set; }
        public bool GIVESANONYMOUSLY { get; set; }
        public byte GROUPTYPECODE { get; set; }
        public string GROUPTYPE { get; set; }
        public Nullable<System.Guid> GROUPTYPEID { get; set; }
        public string GROUPDESCRIPTION { get; set; }
        public Nullable<System.DateTime> GROUPSTARTDATE { get; set; }
        public string DPC { get; set; }
        public string CART { get; set; }
        public string LOT { get; set; }
        public bool OMITFROMVALIDATION { get; set; }
        public Nullable<System.Guid> COUNTYCODEID { get; set; }
        public Nullable<System.Guid> CONGRESSIONALDISTRICTCODEID { get; set; }
        public Nullable<System.DateTime> LASTVALIDATIONATTEMPTDATE { get; set; }
        public string VALIDATIONMESSAGE { get; set; }
        public int CERTIFICATIONDATA { get; set; }
        public Nullable<System.Guid> DONOTMAILREASONCODEID { get; set; }
        public Nullable<System.Guid> NAMEFORMATFUNCTIONID { get; set; }
        public bool DONOTCALL { get; set; }
        public bool DONOTEMAIL { get; set; }
        public string NAME { get; set; }
        public Nullable<System.Guid> SITEID { get; set; }
        public Nullable<System.Guid> CONSTITUENTSECURITYGROUPID { get; set; }
        public Nullable<System.Guid> CONSTITUENCYCODEID { get; set; }
        public Nullable<System.Guid> INFOSOURCECODEID { get; set; }
        public short CLASSOF { get; set; }
        public string NAMEFORMATS { get; set; }
        public string ORIGINAL_LASTNAME { get; set; }
        public string ORIGINAL_FIRSTNAME { get; set; }
    }
}
