//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UM.CustomFx.GratefulPatient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BATCHCONSTITUENTUPDATEEMAILADDRESS
    {
        public System.Guid ID { get; set; }
        public System.Guid BATCHCONSTITUENTUPDATEID { get; set; }
        public int SEQUENCE { get; set; }
        public Nullable<System.Guid> EMAILADDRESSTYPECODEID { get; set; }
        public string EMAILADDRESS { get; set; }
        public bool ISPRIMARY { get; set; }
        public bool DONOTEMAIL { get; set; }
        public bool UPDATEHOUSEHOLD { get; set; }
        public System.Guid ADDEDBYID { get; set; }
        public System.Guid CHANGEDBYID { get; set; }
        public System.DateTime DATEADDED { get; set; }
        public System.DateTime DATECHANGED { get; set; }
        public byte[] TS { get; set; }
        public Nullable<long> TSLONG { get; set; }
        public Nullable<System.DateTime> STARTDATE { get; set; }
        public Nullable<System.DateTime> ENDDATE { get; set; }
        public Nullable<System.Guid> INFOSOURCECODEID { get; set; }
        public Nullable<System.Guid> EMAILADDRESSID { get; set; }
        public bool ISMANUALEXCEPTION { get; set; }
        public byte ROWORIGINCODE { get; set; }
        public string ROWORIGIN { get; set; }
    
        public virtual BATCHCONSTITUENTUPDATE BATCHCONSTITUENTUPDATE { get; set; }
    }
}
