//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UM.CustomFx.GratefulPatient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BATCHCONSTITUENTUPDATEADDRESS
    {
        public System.Guid ID { get; set; }
        public System.Guid BATCHCONSTITUENTUPDATEID { get; set; }
        public int SEQUENCE { get; set; }
        public Nullable<System.Guid> ADDRESSTYPECODEID { get; set; }
        public System.Guid COUNTRYID { get; set; }
        public string ADDRESSBLOCK { get; set; }
        public string CITY { get; set; }
        public Nullable<System.Guid> STATEID { get; set; }
        public string POSTCODE { get; set; }
        public Nullable<System.DateTime> HISTORICALSTARTDATE { get; set; }
        public bool ISPRIMARY { get; set; }
        public bool DONOTMAIL { get; set; }
        public Nullable<System.Guid> DONOTMAILREASONCODEID { get; set; }
        public bool UPDATEHOUSEHOLD { get; set; }
        public string STARTDATE { get; set; }
        public string ENDDATE { get; set; }
        public Nullable<System.Guid> INFOSOURCECODEID { get; set; }
        public Nullable<System.Guid> COUNTYCODEID { get; set; }
        public string DPC { get; set; }
        public string CART { get; set; }
        public string LOT { get; set; }
        public Nullable<System.Guid> REGIONCODEID { get; set; }
        public Nullable<System.Guid> CONGRESSIONALDISTRICTCODEID { get; set; }
        public Nullable<System.Guid> STATEHOUSEDISTRICTCODEID { get; set; }
        public Nullable<System.Guid> STATESENATEDISTRICTCODEID { get; set; }
        public Nullable<System.Guid> LOCALPRECINCTCODEID { get; set; }
        public int CERTIFICATIONDATA { get; set; }
        public Nullable<System.DateTime> LASTVALIDATIONATTEMPTDATE { get; set; }
        public bool OMITFROMVALIDATION { get; set; }
        public string VALIDATIONMESSAGE { get; set; }
        public System.Guid ADDEDBYID { get; set; }
        public System.Guid CHANGEDBYID { get; set; }
        public System.DateTime DATEADDED { get; set; }
        public System.DateTime DATECHANGED { get; set; }
        public byte[] TS { get; set; }
        public Nullable<long> TSLONG { get; set; }
        public Nullable<System.Guid> ADDRESSID { get; set; }
        public string INFOSOURCECOMMENTS { get; set; }
        public Nullable<System.DateTime> HISTORICALENDDATE { get; set; }
        public bool ISMANUALEXCEPTION { get; set; }
        public Nullable<System.Guid> MANUALEXCEPTIONSIMILARADDRESSID { get; set; }
        public byte ROWORIGINCODE { get; set; }
        public string ROWORIGIN { get; set; }
    
        public virtual BATCHCONSTITUENTUPDATE BATCHCONSTITUENTUPDATE { get; set; }
    }
}
