//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UM.CustomFx.GratefulPatient.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CRMEntities : DbContext
    {
        static string _connection;
        public CRMEntities() : base(_connection ?? "name=CRMEntities") { }
        public CRMEntities(string connection) : base(connection)
        {
            _connection = connection;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<USR_UMHS_FRIENDNUMBERS> USR_UMHS_FRIENDNUMBERS { get; set; }
        public virtual DbSet<BATCHREVENUECONSTITUENT> BATCHREVENUECONSTITUENTs { get; set; }
        public virtual DbSet<RECORDTYPE> RECORDTYPEs { get; set; }
    
        public virtual int USP_CHANGEAGENT_GETORCREATECHANGEAGENT(ObjectParameter iD, string aPPNAME, string uSERNAME, string pROCESSNAME)
        {
            var aPPNAMEParameter = aPPNAME != null ?
                new ObjectParameter("APPNAME", aPPNAME) :
                new ObjectParameter("APPNAME", typeof(string));
    
            var uSERNAMEParameter = uSERNAME != null ?
                new ObjectParameter("USERNAME", uSERNAME) :
                new ObjectParameter("USERNAME", typeof(string));
    
            var pROCESSNAMEParameter = pROCESSNAME != null ?
                new ObjectParameter("PROCESSNAME", pROCESSNAME) :
                new ObjectParameter("PROCESSNAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_CHANGEAGENT_GETORCREATECHANGEAGENT", iD, aPPNAMEParameter, uSERNAMEParameter, pROCESSNAMEParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> USR_USP_UMHS_FINDFRIEND(Nullable<System.Guid> cONSTITUENTID, Nullable<System.Guid> bATCHID)
        {
            var cONSTITUENTIDParameter = cONSTITUENTID.HasValue ?
                new ObjectParameter("CONSTITUENTID", cONSTITUENTID) :
                new ObjectParameter("CONSTITUENTID", typeof(System.Guid));
    
            var bATCHIDParameter = bATCHID.HasValue ?
                new ObjectParameter("BATCHID", bATCHID) :
                new ObjectParameter("BATCHID", typeof(System.Guid));

            this.Database.CommandTimeout = 180;
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("USR_USP_UMHS_FINDFRIEND", cONSTITUENTIDParameter, bATCHIDParameter);
            
        }
    }
}
