//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by BBUIModelLibrary
//     Version:  4.0.167.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace UM.CustomFx.GratefulPatient.UIModel
{

/// <summary>
/// Represents the UI model for the 'MIMED Interactions Delete Global Change' data form
/// </summary>

public partial class @MIMEDInteractionsDeleteGlobalChangeUIModel : global::Blackbaud.AppFx.UIModeling.Core.CustomUIModel
{

#region "Extensibility methods"

	partial void OnCreated();

#endregion

    private global::Blackbaud.AppFx.UIModeling.Core.SearchListField<System.Guid> _idsetregisterid;

	[System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.167.0")]
	public @MIMEDInteractionsDeleteGlobalChangeUIModel() : base()
	{


        _idsetregisterid = new global::Blackbaud.AppFx.UIModeling.Core.SearchListField<System.Guid>();

        //
        //_idsetregisterid
        //
        _idsetregisterid.Name = "IDSETREGISTERID";
        _idsetregisterid.Caption = "Selection";
        _idsetregisterid.Required = true;
        _idsetregisterid.SearchListId = new System.Guid("98d0070e-c4a7-495b-a438-2ac12da79068");
        _idsetregisterid.EnableQuickFind = true;
        _idsetregisterid.SystemSearchType = global::Blackbaud.AppFx.UIModeling.Core.SystemSearchType.Selection;
        this.Fields.Add(_idsetregisterid);

		OnCreated();

	}

    /// <summary>
    /// Selection
    /// </summary>
    [System.ComponentModel.Description("Selection")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.167.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.SearchListField<System.Guid> @IDSETREGISTERID {
		get { return _idsetregisterid; }
	}

}

}
