//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by BBUIModelLibrary
//     Version:  4.0.165.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace UM.CustomFx.GratefulPatient.UIModel
{

/// <summary>
/// Represents the UI model for the 'MIMED Affiliation Delete Global Change' data form
/// </summary>

public partial class @MIMEDAffiliationDeleteGlobalChangeUIModel : global::Blackbaud.AppFx.UIModeling.Core.CustomUIModel
{

#region "Extensibility methods"

	partial void OnCreated();

#endregion

    private global::Blackbaud.AppFx.UIModeling.Core.SearchListField<System.Guid> _idsetregisterid;
    private global::Blackbaud.AppFx.UIModeling.Core.GuidField _recordtypeid;
    private global::Blackbaud.AppFx.UIModeling.Core.CodeTableField _affiliationcategorycodeid;
    private global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid> _affiliationbasenamecodeid;
    private global::Blackbaud.AppFx.UIModeling.Core.DateField _startdate;
    private global::Blackbaud.AppFx.UIModeling.Core.DateField _enddate;
    private global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid> _departmentid;
    private global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid> _subdepartmentid;

	[System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public @MIMEDAffiliationDeleteGlobalChangeUIModel() : base()
	{


        _idsetregisterid = new global::Blackbaud.AppFx.UIModeling.Core.SearchListField<System.Guid>();
        _recordtypeid = new global::Blackbaud.AppFx.UIModeling.Core.GuidField();
        _affiliationcategorycodeid = new global::Blackbaud.AppFx.UIModeling.Core.CodeTableField();
        _affiliationbasenamecodeid = new global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid>();
        _startdate = new global::Blackbaud.AppFx.UIModeling.Core.DateField();
        _enddate = new global::Blackbaud.AppFx.UIModeling.Core.DateField();
        _departmentid = new global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid>();
        _subdepartmentid = new global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid>();

        this.UserInterfaceUrl = "browser/htmlforms/custom/um.customfx.gratefulpatient/MIMEDAffiliationDeleteGlobalChange.html";

        //
        //_idsetregisterid
        //
        _idsetregisterid.Name = "IDSETREGISTERID";
        _idsetregisterid.Caption = "Selection";
        _idsetregisterid.Required = true;
        _idsetregisterid.SearchListId = new System.Guid("98d0070e-c4a7-495b-a438-2ac12da79068");
        _idsetregisterid.EnableQuickFind = true;
        _idsetregisterid.SearchFieldOverrides.Add(new global::Blackbaud.AppFx.UIModeling.Core.FieldOverride() {FieldId = "RECORDTYPEID", Caption = "Record type", ReadOnly = true, DefaultValueText = "Fields!RECORDTYPEID"});
        _idsetregisterid.SystemSearchType = global::Blackbaud.AppFx.UIModeling.Core.SystemSearchType.Selection;
        this.Fields.Add(_idsetregisterid);
        //
        //_recordtypeid
        //
        _recordtypeid.Name = "RECORDTYPEID";
        _recordtypeid.Caption = "RECORDTYPEID";
        _recordtypeid.Visible = false;
        _recordtypeid.DBReadOnly = true;
        this.Fields.Add(_recordtypeid);
        //
        //_affiliationcategorycodeid
        //
        _affiliationcategorycodeid.Name = "AFFILIATIONCATEGORYCODEID";
        _affiliationcategorycodeid.Caption = "Category";
        _affiliationcategorycodeid.Required = true;
        _affiliationcategorycodeid.CodeTableName = "USR_UMHS_AFFILIATIONCATEGORYTYPECODE";
        this.Fields.Add(_affiliationcategorycodeid);
        //
        //_affiliationbasenamecodeid
        //
        _affiliationbasenamecodeid.Name = "AFFILIATIONBASENAMECODEID";
        _affiliationbasenamecodeid.Caption = "Name";
        _affiliationbasenamecodeid.Required = true;
        _affiliationbasenamecodeid.SimpleDataListId = new System.Guid("4c646cee-0f5b-4197-b4d3-0869693cfc2d");
        _affiliationbasenamecodeid.Parameters.Add(new global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListParameter("AFFILIATIONCATEGORYCODEID", "Fields!AFFILIATIONCATEGORYCODEID"));
        this.Fields.Add(_affiliationbasenamecodeid);
        //
        //_startdate
        //
        _startdate.Name = "STARTDATE";
        _startdate.Caption = "Start date";
        this.Fields.Add(_startdate);
        //
        //_enddate
        //
        _enddate.Name = "ENDDATE";
        _enddate.Caption = "End date";
        this.Fields.Add(_enddate);
        //
        //_departmentid
        //
        _departmentid.Name = "DEPARTMENTID";
        _departmentid.Caption = "MIMED department";
        _departmentid.Required = true;
        _departmentid.SimpleDataListId = new System.Guid("0cbdb7f1-f629-4e7b-a7e1-c3e4ebd7d325");
        this.Fields.Add(_departmentid);
        //
        //_subdepartmentid
        //
        _subdepartmentid.Name = "SUBDEPARTMENTID";
        _subdepartmentid.Caption = "MIMED subdepartment";
        _subdepartmentid.SimpleDataListId = new System.Guid("879b4e21-6a71-4c60-9b41-771fa39ef9cf");
        _subdepartmentid.Parameters.Add(new global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListParameter("DEPARTMENTID", "Fields!DEPARTMENTID"));
        this.Fields.Add(_subdepartmentid);

		OnCreated();

	}

    /// <summary>
    /// Selection
    /// </summary>
    [System.ComponentModel.Description("Selection")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.SearchListField<System.Guid> @IDSETREGISTERID {
		get { return _idsetregisterid; }
	}

    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.GuidField @RECORDTYPEID {
		get { return _recordtypeid; }
	}

    /// <summary>
    /// Category
    /// </summary>
    [System.ComponentModel.Description("Category")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.CodeTableField @AFFILIATIONCATEGORYCODEID {
		get { return _affiliationcategorycodeid; }
	}

    /// <summary>
    /// Name
    /// </summary>
    [System.ComponentModel.Description("Name")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid> @AFFILIATIONBASENAMECODEID {
		get { return _affiliationbasenamecodeid; }
	}

    /// <summary>
    /// Start date
    /// </summary>
    [System.ComponentModel.Description("Start date")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.DateField @STARTDATE {
		get { return _startdate; }
	}

    /// <summary>
    /// End date
    /// </summary>
    [System.ComponentModel.Description("End date")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.DateField @ENDDATE {
		get { return _enddate; }
	}

    /// <summary>
    /// MIMED department
    /// </summary>
    [System.ComponentModel.Description("MIMED department")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid> @DEPARTMENTID {
		get { return _departmentid; }
	}

    /// <summary>
    /// MIMED subdepartment
    /// </summary>
    [System.ComponentModel.Description("MIMED subdepartment")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid> @SUBDEPARTMENTID {
		get { return _subdepartmentid; }
	}

}

}
