//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by BBUIModelLibrary
//     Version:  4.0.170.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace UM.CustomFx.GratefulPatient.UIModel
{

/// <summary>
/// Represents the UI model for the 'MIMED Logging Report Report.' data form
/// </summary>

public partial class @MIMEDLoggingReportReportUIModel : global::Blackbaud.AppFx.UIModeling.Core.ReportParameterUIModel
{

#region "Enums"

    /// <summary>
    /// Enumerated values for use with the DATETYPE property
    /// </summary>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.170.0")]
	public enum DATETYPES : int
	{
        @SpecificDate = 0,
        @AllDates = 1,
        @Last30Days = 56,
        @Last60Days = 57,
        @Last90Days = 46,
        @Last6Months = 47,
        @LastYear = 48,
        @Last5Years = 58
	}

#endregion

#region "Extensibility methods"

	partial void OnCreated();

#endregion

    private global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid> _userid;
    private global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<string> _tabname;
    private global::Blackbaud.AppFx.UIModeling.Core.ValueListField<DATETYPES> _datetype;
    private global::Blackbaud.AppFx.UIModeling.Core.DateField _dateragestart;
    private global::Blackbaud.AppFx.UIModeling.Core.DateField _daterageend;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _daterangedisplay;

	[System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.170.0")]
	public @MIMEDLoggingReportReportUIModel() : base()
	{


        _userid = new global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid>();
        _tabname = new global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<string>();
        _datetype = new global::Blackbaud.AppFx.UIModeling.Core.ValueListField<DATETYPES>();
        _dateragestart = new global::Blackbaud.AppFx.UIModeling.Core.DateField();
        _daterageend = new global::Blackbaud.AppFx.UIModeling.Core.DateField();
        _daterangedisplay = new global::Blackbaud.AppFx.UIModeling.Core.StringField();

        this.UserInterfaceUrl = "browser/htmlforms/custom/um.customfx.gratefulpatient/MIMEDLoggingReportReport.html";

        //
        //_userid
        //
        _userid.Name = "USERID";
        _userid.Caption = "User";
        _userid.Description = "Filter the list based on the user who made the change.";
        _userid.SimpleDataListId = new System.Guid("c8f924ea-3aaf-4025-bd9e-36bc9fadee75");
        this.Fields.Add(_userid);
        //
        //_tabname
        //
        _tabname.Name = "TABNAME";
        _tabname.Caption = "TabName";
        _tabname.Description = "Filter the list based on the Tabs that was accessed.";
        _tabname.SimpleDataListId = new System.Guid("c8f924ea-3aaf-4025-bd9e-36bc9fadee75");
        this.Fields.Add(_tabname);
        //
        //_datetype
        //
        _datetype.Name = "DATETYPE";
        _datetype.Caption = "Show";
        _datetype.Description = "Filter the list based on a time frame.";
        _datetype.Required = true;
        _datetype.DataSource.Add(new global::Blackbaud.AppFx.UIModeling.Core.ValueListItem<DATETYPES> {Value = DATETYPES.@SpecificDate, Translation = "Specific Date"});
        _datetype.DataSource.Add(new global::Blackbaud.AppFx.UIModeling.Core.ValueListItem<DATETYPES> {Value = DATETYPES.@AllDates, Translation = "All Dates"});
        _datetype.DataSource.Add(new global::Blackbaud.AppFx.UIModeling.Core.ValueListItem<DATETYPES> {Value = DATETYPES.@Last30Days, Translation = "Last 30 days"});
        _datetype.DataSource.Add(new global::Blackbaud.AppFx.UIModeling.Core.ValueListItem<DATETYPES> {Value = DATETYPES.@Last60Days, Translation = "Last 60 days"});
        _datetype.DataSource.Add(new global::Blackbaud.AppFx.UIModeling.Core.ValueListItem<DATETYPES> {Value = DATETYPES.@Last90Days, Translation = "Last 90 days"});
        _datetype.DataSource.Add(new global::Blackbaud.AppFx.UIModeling.Core.ValueListItem<DATETYPES> {Value = DATETYPES.@Last6Months, Translation = "Last 6 months"});
        _datetype.DataSource.Add(new global::Blackbaud.AppFx.UIModeling.Core.ValueListItem<DATETYPES> {Value = DATETYPES.@LastYear, Translation = "Last year"});
        _datetype.DataSource.Add(new global::Blackbaud.AppFx.UIModeling.Core.ValueListItem<DATETYPES> {Value = DATETYPES.@Last5Years, Translation = "Last 5 years"});
        _datetype.Value = DATETYPES.@Last30Days;
        this.Fields.Add(_datetype);
        //
        //_dateragestart
        //
        _dateragestart.Name = "DATERAGESTART";
        _dateragestart.Caption = "Start date";
        _dateragestart.Description = "Beginning of the date range on which to filter the list.";
        this.Fields.Add(_dateragestart);
        //
        //_daterageend
        //
        _daterageend.Name = "DATERAGEEND";
        _daterageend.Caption = "End date";
        _daterageend.Description = "End of the date range on which to filter the list.";
        this.Fields.Add(_daterageend);
        //
        //_daterangedisplay
        //
        _daterangedisplay.Name = "DATERANGEDISPLAY";
        _daterangedisplay.Caption = "DATERANGEDISPLAY";
        _daterangedisplay.Visible = false;
        this.Fields.Add(_daterangedisplay);

		OnCreated();

	}

    /// <summary>
    /// Filter the list based on the user who made the change.
    /// </summary>
    [System.ComponentModel.Description("Filter the list based on the user who made the change.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.170.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid> @USERID {
		get { return _userid; }
	}

    /// <summary>
    /// Filter the list based on the Tabs that was accessed.
    /// </summary>
    [System.ComponentModel.Description("Filter the list based on the Tabs that was accessed.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.170.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<string> @TABNAME {
		get { return _tabname; }
	}

    /// <summary>
    /// Filter the list based on a time frame.
    /// </summary>
    [System.ComponentModel.Description("Filter the list based on a time frame.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.170.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.ValueListField<DATETYPES> @DATETYPE {
		get { return _datetype; }
	}

    /// <summary>
    /// Beginning of the date range on which to filter the list.
    /// </summary>
    [System.ComponentModel.Description("Beginning of the date range on which to filter the list.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.170.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.DateField @DATERAGESTART {
		get { return _dateragestart; }
	}

    /// <summary>
    /// End of the date range on which to filter the list.
    /// </summary>
    [System.ComponentModel.Description("End of the date range on which to filter the list.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.170.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.DateField @DATERAGEEND {
		get { return _daterageend; }
	}

    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.170.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @DATERANGEDISPLAY {
		get { return _daterangedisplay; }
	}

}

}
