//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by BBUIModelLibrary
//     Version:  4.0.5.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace UM.CustomFx.GratefulPatient.UIModel
{

    /// <summary>
    /// Represents the UI model for the 'Add/Delete MIMED Team Member Global Change (Custom)' data form
    /// </summary>

    public partial class @MIMEDTeamMemberGlobalChangeUIModel : global::Blackbaud.AppFx.UIModeling.Core.CustomUIModel
{

#region "Extensibility methods"

	partial void OnCreated();

#endregion

    private global::Blackbaud.AppFx.UIModeling.Core.SearchListField<System.Guid> _selectionid;
    private global::Blackbaud.AppFx.UIModeling.Core.SearchListField<System.Guid> _teammemberid;
    private global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid> _teammembersiteid;
    private global::Blackbaud.AppFx.UIModeling.Core.ShowSearchFormUIAction _teammembersiteidsearchaction;
    private global::Blackbaud.AppFx.UIModeling.Core.CodeTableField _teamrolecodeid;
    private global::Blackbaud.AppFx.UIModeling.Core.DateField _startdate;
    private global::Blackbaud.AppFx.UIModeling.Core.DateField _enddate;

	[System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.5.0")]
	public @MIMEDTeamMemberGlobalChangeUIModel() : base()
	{


        _selectionid = new global::Blackbaud.AppFx.UIModeling.Core.SearchListField<System.Guid>();
        _teammemberid = new global::Blackbaud.AppFx.UIModeling.Core.SearchListField<System.Guid>();
        _teammembersiteid = new global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid>();
        _teammembersiteidsearchaction = new global::Blackbaud.AppFx.UIModeling.Core.ShowSearchFormUIAction();
        _teamrolecodeid = new global::Blackbaud.AppFx.UIModeling.Core.CodeTableField();
        _startdate = new global::Blackbaud.AppFx.UIModeling.Core.DateField();
        _enddate = new global::Blackbaud.AppFx.UIModeling.Core.DateField();

        this.UserInterfaceUrl = "browser/htmlforms/custom/um.customfx.gratefulpatient/MIMEDTeamMemberGlobalChange.html";

        //
        //_selectionid
        //
        _selectionid.Name = "SELECTIONID";
        _selectionid.Caption = "Selection";
        _selectionid.Required = true;
        _selectionid.SearchListId = new System.Guid("98d0070e-c4a7-495b-a438-2ac12da79068");
        _selectionid.EnableQuickFind = true;
        _selectionid.SearchFieldOverrides.Add(new global::Blackbaud.AppFx.UIModeling.Core.FieldOverride() {FieldId = "RECORDTYPEID", ReadOnly = true, DefaultValueText = "64CC83C4-CEBF-426B-B72F-B96CEBA4818A"});
        _selectionid.SystemSearchType = global::Blackbaud.AppFx.UIModeling.Core.SystemSearchType.Selection;
        this.Fields.Add(_selectionid);
        //
        //_teammemberid
        //
        _teammemberid.Name = "TEAMMEMBERID";
        _teammemberid.Caption = "Team Member";
        _teammemberid.Required = true;
        _teammemberid.SearchListId = new System.Guid("35fa0186-b669-436f-913a-5e9fd5e59982");
        _teammemberid.EnableQuickFind = true;
        this.Fields.Add(_teammemberid);
        //
        //_teammembersiteid
        //
        _teammembersiteid.Name = "TEAMMEMBERSITEID";
        _teammembersiteid.Caption = "Site";
        _teammembersiteid.SimpleDataListId = new System.Guid("c8e8d3ba-2725-421f-a796-e2fcc1202780");
        _teammembersiteid.LinkedActions.Add(_teammembersiteidsearchaction);
        this.Fields.Add(_teammembersiteid);
        //
        //_teammembersiteidsearchaction
        //
        _teammembersiteidsearchaction.Name = "TEAMMEMBERSITEIDSEARCHACTION";
        _teammembersiteidsearchaction.Caption = "Search";
        _teammembersiteidsearchaction.SearchListId = new System.Guid("27a63ede-a0d4-4074-a85a-196df4adc0dd");
        this.Actions.Add(_teammembersiteidsearchaction);
        //
        //_teamrolecodeid
        //
        _teamrolecodeid.Name = "TEAMROLECODEID";
        _teamrolecodeid.Caption = "Team Role";
        _teamrolecodeid.CodeTableName = "USR_UMHS_TEAMROLECODE";
        this.Fields.Add(_teamrolecodeid);
        //
        //_startdate
        //
        _startdate.Name = "STARTDATE";
        _startdate.Caption = "Start Date";
        this.Fields.Add(_startdate);
        //
        //_enddate
        //
        _enddate.Name = "ENDDATE";
        _enddate.Caption = "End Date";
        this.Fields.Add(_enddate);

		OnCreated();

	}

    /// <summary>
    /// Selection
    /// </summary>
    [System.ComponentModel.Description("Selection")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.5.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.SearchListField<System.Guid> @SELECTIONID {
		get { return _selectionid; }
	}

    /// <summary>
    /// Team Member
    /// </summary>
    [System.ComponentModel.Description("Team Member")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.5.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.SearchListField<System.Guid> @TEAMMEMBERID {
		get { return _teammemberid; }
	}

    /// <summary>
    /// Site
    /// </summary>
    [System.ComponentModel.Description("Site")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.5.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid> @TEAMMEMBERSITEID {
		get { return _teammembersiteid; }
	}

    /// <summary>
    /// Search
    /// </summary>
    [System.ComponentModel.Description("Search")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.5.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.ShowSearchFormUIAction @TEAMMEMBERSITEIDSEARCHACTION {
		get { return _teammembersiteidsearchaction; }
	}

    /// <summary>
    /// Team Role
    /// </summary>
    [System.ComponentModel.Description("Team Role")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.5.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.CodeTableField @TEAMROLECODEID {
		get { return _teamrolecodeid; }
	}

    /// <summary>
    /// Start Date
    /// </summary>
    [System.ComponentModel.Description("Start Date")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.5.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.DateField @STARTDATE {
		get { return _startdate; }
	}

    /// <summary>
    /// End Date
    /// </summary>
    [System.ComponentModel.Description("End Date")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.5.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.DateField @ENDDATE {
		get { return _enddate; }
	}

}

}
