//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by BBUIModelLibrary
//     Version:  4.0.5.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace UM.CustomFx.GratefulPatient.UIModel
{

/// <summary>
/// Represents the UI model for the 'Change MIMED Team Member Global Change (Custom)' data form
/// </summary>

public partial class @MIMEDTeamMemberChangeGlobalChangeUIModel : global::Blackbaud.AppFx.UIModeling.Core.CustomUIModel
{

#region "Extensibility methods"

	partial void OnCreated();

#endregion

    private global::Blackbaud.AppFx.UIModeling.Core.SearchListField<System.Guid> _selectionid;
    private global::Blackbaud.AppFx.UIModeling.Core.SearchListField<System.Guid> _currentteammemberid;
    private global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid> _currentteammembersiteid;
    private global::Blackbaud.AppFx.UIModeling.Core.ShowSearchFormUIAction _currentteammembersiteidsearchaction;
    private global::Blackbaud.AppFx.UIModeling.Core.CodeTableField _currentteamrolecodeid;
    private global::Blackbaud.AppFx.UIModeling.Core.DateField _currentstartdate;
    private global::Blackbaud.AppFx.UIModeling.Core.DateField _currentenddate;
    private global::Blackbaud.AppFx.UIModeling.Core.SearchListField<System.Guid> _newteammemberid;
    private global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid> _newteammembersiteid;
    private global::Blackbaud.AppFx.UIModeling.Core.ShowSearchFormUIAction _newteammembersiteidsearchaction;
    private global::Blackbaud.AppFx.UIModeling.Core.CodeTableField _newteamrolecodeid;
    private global::Blackbaud.AppFx.UIModeling.Core.DateField _newstartdate;
    private global::Blackbaud.AppFx.UIModeling.Core.DateField _newenddate;

	[System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.5.0")]
	public @MIMEDTeamMemberChangeGlobalChangeUIModel() : base()
	{


        _selectionid = new global::Blackbaud.AppFx.UIModeling.Core.SearchListField<System.Guid>();
        _currentteammemberid = new global::Blackbaud.AppFx.UIModeling.Core.SearchListField<System.Guid>();
        _currentteammembersiteid = new global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid>();
        _currentteammembersiteidsearchaction = new global::Blackbaud.AppFx.UIModeling.Core.ShowSearchFormUIAction();
        _currentteamrolecodeid = new global::Blackbaud.AppFx.UIModeling.Core.CodeTableField();
        _currentstartdate = new global::Blackbaud.AppFx.UIModeling.Core.DateField();
        _currentenddate = new global::Blackbaud.AppFx.UIModeling.Core.DateField();
        _newteammemberid = new global::Blackbaud.AppFx.UIModeling.Core.SearchListField<System.Guid>();
        _newteammembersiteid = new global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid>();
        _newteammembersiteidsearchaction = new global::Blackbaud.AppFx.UIModeling.Core.ShowSearchFormUIAction();
        _newteamrolecodeid = new global::Blackbaud.AppFx.UIModeling.Core.CodeTableField();
        _newstartdate = new global::Blackbaud.AppFx.UIModeling.Core.DateField();
        _newenddate = new global::Blackbaud.AppFx.UIModeling.Core.DateField();

        this.UserInterfaceUrl = "browser/htmlforms/custom/um.customfx.gratefulpatient/MIMEDTeamMemberChangeGlobalChange.html";

        //
        //_selectionid
        //
        _selectionid.Name = "SELECTIONID";
        _selectionid.Caption = "Selection";
        _selectionid.Required = true;
        _selectionid.SearchListId = new System.Guid("98d0070e-c4a7-495b-a438-2ac12da79068");
        _selectionid.EnableQuickFind = true;
        _selectionid.SearchFieldOverrides.Add(new global::Blackbaud.AppFx.UIModeling.Core.FieldOverride() {FieldId = "RECORDTYPEID", ReadOnly = true, DefaultValueText = "64CC83C4-CEBF-426B-B72F-B96CEBA4818A"});
        _selectionid.SystemSearchType = global::Blackbaud.AppFx.UIModeling.Core.SystemSearchType.Selection;
        this.Fields.Add(_selectionid);
        //
        //_currentteammemberid
        //
        _currentteammemberid.Name = "CURRENTTEAMMEMBERID";
        _currentteammemberid.Caption = "Team Member";
        _currentteammemberid.Required = true;
        _currentteammemberid.SearchListId = new System.Guid("35fa0186-b669-436f-913a-5e9fd5e59982");
        _currentteammemberid.EnableQuickFind = true;
        this.Fields.Add(_currentteammemberid);
        //
        //_currentteammembersiteid
        //
        _currentteammembersiteid.Name = "CURRENTTEAMMEMBERSITEID";
        _currentteammembersiteid.Caption = "Site";
        _currentteammembersiteid.SimpleDataListId = new System.Guid("c8e8d3ba-2725-421f-a796-e2fcc1202780");
        _currentteammembersiteid.LinkedActions.Add(_currentteammembersiteidsearchaction);
        this.Fields.Add(_currentteammembersiteid);
        //
        //_currentteammembersiteidsearchaction
        //
        _currentteammembersiteidsearchaction.Name = "CURRENTTEAMMEMBERSITEIDSEARCHACTION";
        _currentteammembersiteidsearchaction.Caption = "Search";
        _currentteammembersiteidsearchaction.SearchListId = new System.Guid("27a63ede-a0d4-4074-a85a-196df4adc0dd");
        _currentteammembersiteidsearchaction.EnableQuickFind = true;
        this.Actions.Add(_currentteammembersiteidsearchaction);
        //
        //_currentteamrolecodeid
        //
        _currentteamrolecodeid.Name = "CURRENTTEAMROLECODEID";
        _currentteamrolecodeid.Caption = "Team Role";
        _currentteamrolecodeid.CodeTableName = "USR_UMHS_TEAMROLECODE";
        this.Fields.Add(_currentteamrolecodeid);
        //
        //_currentstartdate
        //
        _currentstartdate.Name = "CURRENTSTARTDATE";
        _currentstartdate.Caption = "Start Date";
        this.Fields.Add(_currentstartdate);
        //
        //_currentenddate
        //
        _currentenddate.Name = "CURRENTENDDATE";
        _currentenddate.Caption = "End Date";
        this.Fields.Add(_currentenddate);
        //
        //_newteammemberid
        //
        _newteammemberid.Name = "NEWTEAMMEMBERID";
        _newteammemberid.Caption = "Team Member";
        _newteammemberid.Required = true;
        _newteammemberid.SearchListId = new System.Guid("35fa0186-b669-436f-913a-5e9fd5e59982");
        _newteammemberid.EnableQuickFind = true;
        this.Fields.Add(_newteammemberid);
        //
        //_newteammembersiteid
        //
        _newteammembersiteid.Name = "NEWTEAMMEMBERSITEID";
        _newteammembersiteid.Caption = "Site";
        _newteammembersiteid.SimpleDataListId = new System.Guid("c8e8d3ba-2725-421f-a796-e2fcc1202780");
        _newteammembersiteid.LinkedActions.Add(_newteammembersiteidsearchaction);
        this.Fields.Add(_newteammembersiteid);
        //
        //_newteammembersiteidsearchaction
        //
        _newteammembersiteidsearchaction.Name = "NEWTEAMMEMBERSITEIDSEARCHACTION";
        _newteammembersiteidsearchaction.Caption = "Search";
        _newteammembersiteidsearchaction.SearchListId = new System.Guid("27a63ede-a0d4-4074-a85a-196df4adc0dd");
        _newteammembersiteidsearchaction.EnableQuickFind = true;
        this.Actions.Add(_newteammembersiteidsearchaction);
        //
        //_newteamrolecodeid
        //
        _newteamrolecodeid.Name = "NEWTEAMROLECODEID";
        _newteamrolecodeid.Caption = "Team Role";
        _newteamrolecodeid.CodeTableName = "USR_UMHS_TEAMROLECODE";
        this.Fields.Add(_newteamrolecodeid);
        //
        //_newstartdate
        //
        _newstartdate.Name = "NEWSTARTDATE";
        _newstartdate.Caption = "Start Date";
        this.Fields.Add(_newstartdate);
        //
        //_newenddate
        //
        _newenddate.Name = "NEWENDDATE";
        _newenddate.Caption = "End Date";
        this.Fields.Add(_newenddate);

		OnCreated();

	}

    /// <summary>
    /// Selection
    /// </summary>
    [System.ComponentModel.Description("Selection")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.5.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.SearchListField<System.Guid> @SELECTIONID {
		get { return _selectionid; }
	}

    /// <summary>
    /// Team Member
    /// </summary>
    [System.ComponentModel.Description("Team Member")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.5.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.SearchListField<System.Guid> @CURRENTTEAMMEMBERID {
		get { return _currentteammemberid; }
	}

    /// <summary>
    /// Site
    /// </summary>
    [System.ComponentModel.Description("Site")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.5.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid> @CURRENTTEAMMEMBERSITEID {
		get { return _currentteammembersiteid; }
	}

    /// <summary>
    /// Search
    /// </summary>
    [System.ComponentModel.Description("Search")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.5.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.ShowSearchFormUIAction @CURRENTTEAMMEMBERSITEIDSEARCHACTION {
		get { return _currentteammembersiteidsearchaction; }
	}

    /// <summary>
    /// Team Role
    /// </summary>
    [System.ComponentModel.Description("Team Role")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.5.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.CodeTableField @CURRENTTEAMROLECODEID {
		get { return _currentteamrolecodeid; }
	}

    /// <summary>
    /// Start Date
    /// </summary>
    [System.ComponentModel.Description("Start Date")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.5.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.DateField @CURRENTSTARTDATE {
		get { return _currentstartdate; }
	}

    /// <summary>
    /// End Date
    /// </summary>
    [System.ComponentModel.Description("End Date")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.5.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.DateField @CURRENTENDDATE {
		get { return _currentenddate; }
	}

    /// <summary>
    /// Team Member
    /// </summary>
    [System.ComponentModel.Description("Team Member")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.5.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.SearchListField<System.Guid> @NEWTEAMMEMBERID {
		get { return _newteammemberid; }
	}

    /// <summary>
    /// Site
    /// </summary>
    [System.ComponentModel.Description("Site")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.5.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid> @NEWTEAMMEMBERSITEID {
		get { return _newteammembersiteid; }
	}

    /// <summary>
    /// Search
    /// </summary>
    [System.ComponentModel.Description("Search")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.5.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.ShowSearchFormUIAction @NEWTEAMMEMBERSITEIDSEARCHACTION {
		get { return _newteammembersiteidsearchaction; }
	}

    /// <summary>
    /// Team Role
    /// </summary>
    [System.ComponentModel.Description("Team Role")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.5.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.CodeTableField @NEWTEAMROLECODEID {
		get { return _newteamrolecodeid; }
	}

    /// <summary>
    /// Start Date
    /// </summary>
    [System.ComponentModel.Description("Start Date")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.5.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.DateField @NEWSTARTDATE {
		get { return _newstartdate; }
	}

    /// <summary>
    /// End Date
    /// </summary>
    [System.ComponentModel.Description("End Date")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.5.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.DateField @NEWENDDATE {
		get { return _newenddate; }
	}

}

}
