//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by BBUIModelLibrary
//     Version:  4.0.159.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace UM.CustomFx.GratefulPatient.UIModel
{

/// <summary>
/// Represents the UI model for the 'MIMED Portfolio Referrals Data List' data form
/// </summary>
[global::Blackbaud.AppFx.UIModeling.Core.DataListFilterUIModelMetadata("1071c8eb-4c82-4fd1-9e35-6aace93a01ec", "Constituent")]
public partial class @MIMEDPortfolioReferralsDataListUIModel : global::Blackbaud.AppFx.UIModeling.Core.DataListFilterUIModel
{

#region "Extensibility methods"

	partial void OnCreated();

#endregion

    private global::Blackbaud.AppFx.UIModeling.Core.BooleanField _includehistorical;

	[System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public @MIMEDPortfolioReferralsDataListUIModel() : base()
	{


        _includehistorical = new global::Blackbaud.AppFx.UIModeling.Core.BooleanField();

        this.DataListId = new System.Guid("1071c8eb-4c82-4fd1-9e35-6aace93a01ec");
        this.ContextRecordType = "Constituent";

        //
        //_includehistorical
        //
        _includehistorical.Name = "INCLUDEHISTORICAL";
        _includehistorical.Caption = "Show historical";
        _includehistorical.Value = true;
        this.Fields.Add(_includehistorical);

		OnCreated();

	}

    /// <summary>
    /// Show historical
    /// </summary>
    [System.ComponentModel.Description("Show historical")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.BooleanField @INCLUDEHISTORICAL {
		get { return _includehistorical; }
	}

}

}
