//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by BBUIModelLibrary
//     Version:  4.0.159.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace UM.CustomFx.GratefulPatient.UIModel
{

/// <summary>
/// Represents the UI model for the 'MIMED History Report' data form
/// </summary>

public partial class @MIMEDHistoryReportUIModel : global::Blackbaud.AppFx.UIModeling.Core.ReportParameterUIModel
{

#region "Enums"

    /// <summary>
    /// Enumerated values for use with the ACTIONTYPECODE property
    /// </summary>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public enum ACTIONTYPECODES : int
	{

	    All,
	    Add,
	    Edit,
	    Delete,
        }

    /// <summary>
    /// Enumerated values for use with the DATETYPE property
    /// </summary>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public enum DATETYPES : int
	{
	    SpecificDate = 0,
	    AllDates = 1,
	    Last90Days = 46,
	    Last6Months = 47,
	    LastYear = 48,
	    Last30Days = 56,
	    Last60Days = 57,
	    Last5Years = 58,
        }

    /// <summary>
    /// Enumerated values for use with the RECORDTYPECODE property
    /// </summary>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public enum RECORDTYPECODES : int
	{
	    All=0,
            //Constituent,
	    MIMEDData=1,
        //DeceasedConstituent,
        //OrganizationData,
        ApplicationUserLink=2,
	    Phone=3,
	    Address=4,
	    EmailAddress=5,
	    Interest=6,
        Interaction=7,
        Affiliation=8,
        Team=9,
	    //MatchingGiftCondition,
	    //Constituency,
	    EducationalHistory=10,
	    Documentation=11,
	    Alias=12,
	    //NameFormat,
	    Relationship=13,
	    //FinancialAccount,
	    SecurityGroup=14,
        }

#endregion

#region "Extensibility methods"

	partial void OnCreated();

#endregion

    private global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid> _userid;
    private global::Blackbaud.AppFx.UIModeling.Core.ValueListField<ACTIONTYPECODES> _actiontypecode;
    private global::Blackbaud.AppFx.UIModeling.Core.ValueListField<DATETYPES> _datetype;
    private global::Blackbaud.AppFx.UIModeling.Core.DateField _startdate;
    private global::Blackbaud.AppFx.UIModeling.Core.DateField _enddate;
    private global::Blackbaud.AppFx.UIModeling.Core.ValueListField<RECORDTYPECODES> _recordtypecode;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _daterangedisplay;
    private global::Blackbaud.AppFx.UIModeling.Core.SearchListField<System.Guid> _umhsid;



	[System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public @MIMEDHistoryReportUIModel() : base()
	{


        _userid = new global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid>();
        _actiontypecode = new global::Blackbaud.AppFx.UIModeling.Core.ValueListField<ACTIONTYPECODES>();
        _datetype = new global::Blackbaud.AppFx.UIModeling.Core.ValueListField<DATETYPES>();
        _startdate = new global::Blackbaud.AppFx.UIModeling.Core.DateField();
        _enddate = new global::Blackbaud.AppFx.UIModeling.Core.DateField();
        _recordtypecode = new global::Blackbaud.AppFx.UIModeling.Core.ValueListField<RECORDTYPECODES>();
        _daterangedisplay = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
	    _umhsid = new global::Blackbaud.AppFx.UIModeling.Core.SearchListField<Guid>();

        this.UserInterfaceUrl = "browser/htmlforms/custom/um.customfx.gratefulpatient/MIMEDHistoryReport.html";

        //
        //_userid
        //
        _userid.Name = "USERID";
        _userid.Caption = "User";
        _userid.Description = "Filter the list based on the user who made the change.";
        _userid.SimpleDataListId = new System.Guid("c8f924ea-3aaf-4025-bd9e-36bc9fadee75");
        this.Fields.Add(_userid);
        //
        //_actiontypecode
        //
        _actiontypecode.Name = "ACTIONTYPECODE";
        _actiontypecode.Caption = "Action";
        _actiontypecode.Description = "Filter the list based on database actions.";
        _actiontypecode.Required = true;
        _actiontypecode.DataSource.Add(new global::Blackbaud.AppFx.UIModeling.Core.ValueListItem<ACTIONTYPECODES> {Value = ACTIONTYPECODES.All});//, Translation = "All"});
        _actiontypecode.DataSource.Add(new global::Blackbaud.AppFx.UIModeling.Core.ValueListItem<ACTIONTYPECODES> {Value = ACTIONTYPECODES.Add });//, Translation = "Add"});
            _actiontypecode.DataSource.Add(new global::Blackbaud.AppFx.UIModeling.Core.ValueListItem<ACTIONTYPECODES> {Value = ACTIONTYPECODES.Edit });//, Translation = "Edit"});
            _actiontypecode.DataSource.Add(new global::Blackbaud.AppFx.UIModeling.Core.ValueListItem<ACTIONTYPECODES> {Value = ACTIONTYPECODES.Delete });//, Translation = "Delete"});
            _actiontypecode.Value = ACTIONTYPECODES.@All;
        this.Fields.Add(_actiontypecode);
        //
        //_datetype
        //
        _datetype.Name = "DATETYPE";
        _datetype.Caption = "Show";
        _datetype.Description = "Filter the list based on a time frame.";
        _datetype.Required = true;
        _datetype.DataSource.Add(new global::Blackbaud.AppFx.UIModeling.Core.ValueListItem<DATETYPES> {Value = DATETYPES.SpecificDate });//, Translation = "Specific Date"});
            _datetype.DataSource.Add(new global::Blackbaud.AppFx.UIModeling.Core.ValueListItem<DATETYPES> {Value = DATETYPES.AllDates });//, Translation = "All Dates"});
            _datetype.DataSource.Add(new global::Blackbaud.AppFx.UIModeling.Core.ValueListItem<DATETYPES> {Value = DATETYPES.Last30Days });//, Translation = "Last 30 days"});
            _datetype.DataSource.Add(new global::Blackbaud.AppFx.UIModeling.Core.ValueListItem<DATETYPES> {Value = DATETYPES.Last60Days });//, Translation = "Last 60 days"});
            _datetype.DataSource.Add(new global::Blackbaud.AppFx.UIModeling.Core.ValueListItem<DATETYPES> {Value = DATETYPES.Last90Days });//, Translation = "Last 90 days"});
            _datetype.DataSource.Add(new global::Blackbaud.AppFx.UIModeling.Core.ValueListItem<DATETYPES> {Value = DATETYPES.Last6Months });//, Translation = "Last 6 months"});
            _datetype.DataSource.Add(new global::Blackbaud.AppFx.UIModeling.Core.ValueListItem<DATETYPES> {Value = DATETYPES.LastYear });//, Translation = "Last year"});
            _datetype.DataSource.Add(new global::Blackbaud.AppFx.UIModeling.Core.ValueListItem<DATETYPES> {Value = DATETYPES.Last5Years });//, Translation = "Last 5 years"});
            _datetype.Value = DATETYPES.@Last30Days;
        this.Fields.Add(_datetype);
        //
        //_startdate
        //
        _startdate.Name = "STARTDATE";
        _startdate.Caption = "Start date";
        _startdate.Description = "Beginning of the date range on which to filter the list.";
        this.Fields.Add(_startdate);
        //
        //_enddate
        //
        _enddate.Name = "ENDDATE";
        _enddate.Caption = "End date";
        _enddate.Description = "End of the date range on which to filter the list.";
        this.Fields.Add(_enddate);
        //
        //_recordtypecode
        //
        _recordtypecode.Name = "RECORDTYPECODE";
        _recordtypecode.Caption = "Field type";
        _recordtypecode.Description = "Filter the list based on database actions.";
        _recordtypecode.Required = true;
        _recordtypecode.DataSource.Add(new global::Blackbaud.AppFx.UIModeling.Core.ValueListItem<RECORDTYPECODES> {Value = RECORDTYPECODES.All });//, Translation = "All"});
            _recordtypecode.DataSource.Add(new global::Blackbaud.AppFx.UIModeling.Core.ValueListItem<RECORDTYPECODES> {Value = RECORDTYPECODES.Address });//, Translation = "Address"});
            _recordtypecode.DataSource.Add(new global::Blackbaud.AppFx.UIModeling.Core.ValueListItem<RECORDTYPECODES> {Value = RECORDTYPECODES.Alias });//, Translation = "Alias"});
                                                                                                                                                        //_recordtypecode.DataSource.Add(new global::Blackbaud.AppFx.UIModeling.Core.ValueListItem<RECORDTYPECODES> {Value = RECORDTYPECODES.@ApplicationUserLink, Translation = "Application user link"});
                                                                                                                                                        // _recordtypecode.DataSource.Add(new global::Blackbaud.AppFx.UIModeling.Core.ValueListItem<RECORDTYPECODES> {Value = RECORDTYPECODES.@Constituency, Translation = "Constituency"});
            _recordtypecode.DataSource.Add(new global::Blackbaud.AppFx.UIModeling.Core.ValueListItem<RECORDTYPECODES> {Value = RECORDTYPECODES.MIMEDData });//, Translation = "MIMED Data"});
                                                                                                                                                              //_recordtypecode.DataSource.Add(new global::Blackbaud.AppFx.UIModeling.Core.ValueListItem<RECORDTYPECODES> {Value = RECORDTYPECODES.@DeceasedConstituent, Translation = "Deceased constituent"});
            _recordtypecode.DataSource.Add(new global::Blackbaud.AppFx.UIModeling.Core.ValueListItem<RECORDTYPECODES> {Value = RECORDTYPECODES.Documentation });//, Translation = "Documentation"});
                                                                                                                                                                // _recordtypecode.DataSource.Add(new global::Blackbaud.AppFx.UIModeling.Core.ValueListItem<RECORDTYPECODES> {Value = RECORDTYPECODES.@EducationalHistory, Translation = "Educational history"});
            _recordtypecode.DataSource.Add(new global::Blackbaud.AppFx.UIModeling.Core.ValueListItem<RECORDTYPECODES> {Value = RECORDTYPECODES.EmailAddress });//, Translation = "Email address"});
                                                                                                                                                               //_recordtypecode.DataSource.Add(new global::Blackbaud.AppFx.UIModeling.Core.ValueListItem<RECORDTYPECODES> {Value = RECORDTYPECODES.@FinancialAccount, Translation = "Financial account"});
            _recordtypecode.DataSource.Add(new global::Blackbaud.AppFx.UIModeling.Core.ValueListItem<RECORDTYPECODES> {Value = RECORDTYPECODES.Interest });//, Translation = "Interest"});
                                                                                                                                                           //_recordtypecode.DataSource.Add(new global::Blackbaud.AppFx.UIModeling.Core.ValueListItem<RECORDTYPECODES> {Value = RECORDTYPECODES.@MatchingGiftCondition, Translation = "Matching gift condition"});
                                                                                                                                                           // _recordtypecode.DataSource.Add(new global::Blackbaud.AppFx.UIModeling.Core.ValueListItem<RECORDTYPECODES> {Value = RECORDTYPECODES.@NameFormat, Translation = "Name format"});
                                                                                                                                                           // _recordtypecode.DataSource.Add(new global::Blackbaud.AppFx.UIModeling.Core.ValueListItem<RECORDTYPECODES> {Value = RECORDTYPECODES.@OrganizationData, Translation = "Organization data"});
	    _recordtypecode.DataSource.Add(new global::Blackbaud.AppFx.UIModeling.Core.ValueListItem<RECORDTYPECODES> { Value = RECORDTYPECODES.Interaction });
	    _recordtypecode.DataSource.Add(new global::Blackbaud.AppFx.UIModeling.Core.ValueListItem<RECORDTYPECODES> { Value = RECORDTYPECODES.Affiliation });
	    _recordtypecode.DataSource.Add(new global::Blackbaud.AppFx.UIModeling.Core.ValueListItem<RECORDTYPECODES> { Value = RECORDTYPECODES.Team });
            _recordtypecode.DataSource.Add(new global::Blackbaud.AppFx.UIModeling.Core.ValueListItem<RECORDTYPECODES> {Value = RECORDTYPECODES.Phone });//, Translation = "Phone"});
            _recordtypecode.DataSource.Add(new global::Blackbaud.AppFx.UIModeling.Core.ValueListItem<RECORDTYPECODES> {Value = RECORDTYPECODES.Relationship });//, Translation = "Relationship"});
                                                                                                                                                               //_recordtypecode.DataSource.Add(new global::Blackbaud.AppFx.UIModeling.Core.ValueListItem<RECORDTYPECODES> {Value = RECORDTYPECODES.@SecurityGroup, Translation = "Security group"});
                                                                                                                                                               // _recordtypecode.Value = RECORDTYPECODES.@All;
            this.Fields.Add(_recordtypecode);
        //
        //_daterangedisplay
        //
        _daterangedisplay.Name = "DATERANGEDISPLAY";
        _daterangedisplay.Caption = "DATERANGEDISPLAY";
        _daterangedisplay.Visible = false;
        this.Fields.Add(_daterangedisplay);
        //
        //_umhsid
        //
        _umhsid.Name = "UMHSID";
        _umhsid.Caption = "MIMED Constituent Name";
	    _umhsid.Required = true;
	    _umhsid.EnableQuickFind = true;
        _umhsid.SearchListId = new System.Guid("747530a1-be80-4054-a021-d2a599248261");
        _umhsid.Visible = true;
        this.Fields.Add(_umhsid);

		OnCreated();

	}

    /// <summary>
    /// Filter the list based on the user who made the change.
    /// </summary>
    [System.ComponentModel.Description("Filter the list based on the user who made the change.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid> @USERID {
		get { return _userid; }
	}

    /// <summary>
    /// Filter the list based on database actions.
    /// </summary>
    [System.ComponentModel.Description("Filter the list based on database actions.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.ValueListField<ACTIONTYPECODES> @ACTIONTYPECODE {
		get { return _actiontypecode; }
	}

    /// <summary>
    /// Filter the list based on a time frame.
    /// </summary>
    [System.ComponentModel.Description("Filter the list based on a time frame.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.ValueListField<DATETYPES> @DATETYPE {
		get { return _datetype; }
	}

    /// <summary>
    /// Beginning of the date range on which to filter the list.
    /// </summary>
    [System.ComponentModel.Description("Beginning of the date range on which to filter the list.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.DateField @STARTDATE {
		get { return _startdate; }
	}

    /// <summary>
    /// End of the date range on which to filter the list.
    /// </summary>
    [System.ComponentModel.Description("End of the date range on which to filter the list.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.DateField @ENDDATE {
		get { return _enddate; }
	}

    /// <summary>
    /// Filter the list based on database actions.
    /// </summary>
    [System.ComponentModel.Description("Filter the list based on database actions.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.ValueListField<RECORDTYPECODES> @RECORDTYPECODE {
		get { return _recordtypecode; }
	}

    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @DATERANGEDISPLAY {
		get { return _daterangedisplay; }
	}

    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
    public global::Blackbaud.AppFx.UIModeling.Core.SearchListField<System.Guid> @TEAMMEMBERID
    {
        get { return _umhsid; }
    }
        
}

}
