//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by BBUIModelLibrary
//     Version:  4.0.167.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace UM.CustomFx.GratefulPatient.UIModel
{

/// <summary>
/// Represents the UI model for the 'MIMED Team Add Form' data form
/// </summary>
[global::Blackbaud.AppFx.UIModeling.Core.DataFormUIModelMetadata(global::Blackbaud.AppFx.UIModeling.Core.DataFormMode.Add, "e4c3131d-dda7-47e9-8773-202344189b96", "416dde6f-dde3-4ca1-b0a9-62c19f25fc4b", "MIMED Team", "MIMED Data")]
public partial class @MIMEDTeamAddFormUIModel : global::Blackbaud.AppFx.UIModeling.Core.DataFormUIModel
{

#region "Extensibility methods"

	partial void OnCreated();

#endregion

    private global::Blackbaud.AppFx.UIModeling.Core.SearchListField<System.Guid> _teammemberid;
    private global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid> _siteid;
    private global::Blackbaud.AppFx.UIModeling.Core.ShowSearchFormUIAction _siteidsearchaction;
    private global::Blackbaud.AppFx.UIModeling.Core.CodeTableField _teamrolecodeid;
    private global::Blackbaud.AppFx.UIModeling.Core.DateField _startdate;
    private global::Blackbaud.AppFx.UIModeling.Core.DateField _enddate;

	[System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.167.0")]
	public @MIMEDTeamAddFormUIModel() : base()
	{


        _teammemberid = new global::Blackbaud.AppFx.UIModeling.Core.SearchListField<System.Guid>();
        _siteid = new global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid>();
        _siteidsearchaction = new global::Blackbaud.AppFx.UIModeling.Core.ShowSearchFormUIAction();
        _teamrolecodeid = new global::Blackbaud.AppFx.UIModeling.Core.CodeTableField();
        _startdate = new global::Blackbaud.AppFx.UIModeling.Core.DateField();
        _enddate = new global::Blackbaud.AppFx.UIModeling.Core.DateField();

        this.Mode = global::Blackbaud.AppFx.UIModeling.Core.DataFormMode.Add;
        this.DataFormTemplateId = new System.Guid("e4c3131d-dda7-47e9-8773-202344189b96");
        this.DataFormInstanceId = new System.Guid("416dde6f-dde3-4ca1-b0a9-62c19f25fc4b");
        this.RecordType = "MIMED Team";
        this.ContextRecordType = "MIMED Data";
        this.FixedDialog = true;
        this.FORMHEADER.Value = "Add MIMED Team";
        this.UserInterfaceUrl = "browser/htmlforms/custom/um.customfx.gratefulpatient/MIMEDTeamAddForm.html";

        //
        //_teammemberid
        //
        _teammemberid.Name = "TEAMMEMBERID";
        _teammemberid.Caption = "Team member";
        _teammemberid.Required = true;
        _teammemberid.SearchListId = new System.Guid("35fa0186-b669-436f-913a-5e9fd5e59982");
        _teammemberid.EnableQuickFind = true;
        this.Fields.Add(_teammemberid);
        //
        //_siteid
        //
        _siteid.Name = "SITEID";
        _siteid.Caption = "Site";
        _siteid.SimpleDataListId = new System.Guid("c8e8d3ba-2725-421f-a796-e2fcc1202780");
        _siteid.LinkedActions.Add(_siteidsearchaction);
        this.Fields.Add(_siteid);
        //
        //_siteidsearchaction
        //
        _siteidsearchaction.Name = "SITEIDSEARCHACTION";
        _siteidsearchaction.Caption = "Search";
        _siteidsearchaction.SearchListId = new System.Guid("27a63ede-a0d4-4074-a85a-196df4adc0dd");
        this.Actions.Add(_siteidsearchaction);
        //
        //_teamrolecodeid
        //
        _teamrolecodeid.Name = "TEAMROLECODEID";
        _teamrolecodeid.Caption = "Team role";
        _teamrolecodeid.Required = true;
        _teamrolecodeid.CodeTableName = "USR_UMHS_TEAMROLECODE";
        this.Fields.Add(_teamrolecodeid);
        //
        //_startdate
        //
        _startdate.Name = "STARTDATE";
        _startdate.Caption = "Start date";
        _startdate.Required = true;
        this.Fields.Add(_startdate);
        //
        //_enddate
        //
        _enddate.Name = "ENDDATE";
        _enddate.Caption = "End date";
        this.Fields.Add(_enddate);

		OnCreated();

	}

    /// <summary>
    /// Team member
    /// </summary>
    [System.ComponentModel.Description("Team member")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.167.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.SearchListField<System.Guid> @TEAMMEMBERID {
		get { return _teammemberid; }
	}

    /// <summary>
    /// Site
    /// </summary>
    [System.ComponentModel.Description("Site")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.167.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid> @SITEID {
		get { return _siteid; }
	}

    /// <summary>
    /// Search
    /// </summary>
    [System.ComponentModel.Description("Search")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.167.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.ShowSearchFormUIAction @SITEIDSEARCHACTION {
		get { return _siteidsearchaction; }
	}

    /// <summary>
    /// Team role
    /// </summary>
    [System.ComponentModel.Description("Team role")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.167.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.CodeTableField @TEAMROLECODEID {
		get { return _teamrolecodeid; }
	}

    /// <summary>
    /// Start date
    /// </summary>
    [System.ComponentModel.Description("Start date")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.167.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.DateField @STARTDATE {
		get { return _startdate; }
	}

    /// <summary>
    /// End date
    /// </summary>
    [System.ComponentModel.Description("End date")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.167.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.DateField @ENDDATE {
		get { return _enddate; }
	}

}


}
