//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by BBUIModelLibrary
//     Version:  4.0.159.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace UM.CustomFx.GratefulPatient.UIModel
{

/// <summary>
/// Represents the UI model for the 'UMHS Data View Form' data form
/// </summary>
[global::Blackbaud.AppFx.UIModeling.Core.DataFormUIModelMetadata(global::Blackbaud.AppFx.UIModeling.Core.DataFormMode.View, "09205855-aabd-4266-9b21-b9bf09ca2488", "97d591d1-75b1-417f-94da-a03fca7357e4", "MIMED Data")]
public partial class @UMHSDataViewFormUIModel : global::Blackbaud.AppFx.UIModeling.Core.DataFormUIModel
{

#region "Enums"

    /// <summary>
    /// Enumerated values for use with the GENDERCODE property
    /// </summary>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public enum GENDERCODES : int
	{
        @Unknown = 0,
        @Male = 1,
        @Female = 2
	}

#endregion

#region "Extensibility methods"

	partial void OnCreated();

#endregion

    private global::Blackbaud.AppFx.UIModeling.Core.StringField _mrn;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _cpisequence;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _firstname;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _middlename;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _keyname;
    private global::Blackbaud.AppFx.UIModeling.Core.FuzzyDateField _birthdate;
    private global::Blackbaud.AppFx.UIModeling.Core.IntegerField _age;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _titlecode;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _title2code;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _suffixcode;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _suffix2code;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _nickname;
        private global::Blackbaud.AppFx.UIModeling.Core.StringField _lookupid;
        private global::Blackbaud.AppFx.UIModeling.Core.StringField _infosourcecodeid;
        private global::Blackbaud.AppFx.UIModeling.Core.BooleanField _isdmineligible;
        private global::Blackbaud.AppFx.UIModeling.Core.StringField _dmineligiblereasoncodeid;
        private global::Blackbaud.AppFx.UIModeling.Core.ValueListField<System.Nullable<GENDERCODES>> _gendercode;
        private global::Blackbaud.AppFx.UIModeling.Core.StringField _primaryimage;
        private global::Blackbaud.AppFx.UIModeling.Core.GroupField _umhsinformation;
        private global::Blackbaud.AppFx.UIModeling.Core.GroupField _sourceinformation;

        private global::Blackbaud.AppFx.UIModeling.Core.DateField _datecreated;
    private global::Blackbaud.AppFx.UIModeling.Core.DateField _dateupdated;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _msg;

	[System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public @UMHSDataViewFormUIModel() : base()
	{


            _mrn = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _cpisequence = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _firstname = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _middlename = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _keyname = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _birthdate = new global::Blackbaud.AppFx.UIModeling.Core.FuzzyDateField();
        _age = new global::Blackbaud.AppFx.UIModeling.Core.IntegerField();
        _titlecode = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _title2code = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _suffixcode = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _suffix2code = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _nickname = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
            _lookupid = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
            _infosourcecodeid = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
            _isdmineligible = new global::Blackbaud.AppFx.UIModeling.Core.BooleanField();
            _dmineligiblereasoncodeid = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
            _gendercode = new global::Blackbaud.AppFx.UIModeling.Core.ValueListField<System.Nullable<GENDERCODES>>();
            _primaryimage = new global::Blackbaud.AppFx.UIModeling.Core.StringField();

            _datecreated = new global::Blackbaud.AppFx.UIModeling.Core.DateField();
        _dateupdated = new global::Blackbaud.AppFx.UIModeling.Core.DateField();
	    _msg = new global::Blackbaud.AppFx.UIModeling.Core.StringField();

        _umhsinformation = new global::Blackbaud.AppFx.UIModeling.Core.GroupField();
        _sourceinformation = new global::Blackbaud.AppFx.UIModeling.Core.GroupField();

            this.Mode = global::Blackbaud.AppFx.UIModeling.Core.DataFormMode.View;
        this.DataFormTemplateId = new System.Guid("09205855-aabd-4266-9b21-b9bf09ca2488");
        this.DataFormInstanceId = new System.Guid("97d591d1-75b1-417f-94da-a03fca7357e4");
        this.RecordType = "MIMED Data";
        this.FixedDialog = true;
        this.UserInterfaceUrl = "browser/htmlforms/custom/um.customfx.gratefulpatient/UMHSDataViewForm.html";

            //
            //_mrn
            //
            _mrn.Name = "MRN";
            _mrn.Caption = "MRN";
            _mrn.DBReadOnly = true;
            _mrn.MaxLength = 50;
        this.Fields.Add(_mrn);
        //
        //_cpisequence
        //
        _cpisequence.Name = "CPISEQUENCE";
        _cpisequence.Caption = "CPI seq";
        _cpisequence.DBReadOnly = true;
        _cpisequence.MaxLength = 50;
        this.Fields.Add(_cpisequence);
        //
        //_firstname
        //
        _firstname.Name = "FIRSTNAME";
        _firstname.Caption = "First name";
        _firstname.DBReadOnly = true;
        _firstname.MaxLength = 50;
        this.Fields.Add(_firstname);
        //
        //_middlename
        //
        _middlename.Name = "MIDDLENAME";
        _middlename.Caption = "Middle name";
        _middlename.DBReadOnly = true;
        _middlename.MaxLength = 50;
        this.Fields.Add(_middlename);
        //
        //_keyname
        //
        _keyname.Name = "KEYNAME";
        _keyname.Caption = "Last name";
        _keyname.DBReadOnly = true;
        _keyname.MaxLength = 100;
        this.Fields.Add(_keyname);
        //
        //_birthdate
        //
        _birthdate.Name = "BIRTHDATE";
        _birthdate.Caption = "Birth date";
        _birthdate.DBReadOnly = true;
        this.Fields.Add(_birthdate);
        //
        //_age
        //
        _age.Name = "AGE";
        _age.Caption = "Age";
        _age.DBReadOnly = true;
        this.Fields.Add(_age);
        //
        //_titlecode
        //
        _titlecode.Name = "TITLECODE";
        _titlecode.Caption = "Title";
        _titlecode.DBReadOnly = true;
        _titlecode.MaxLength = 100;
        this.Fields.Add(_titlecode);
        //
        //_title2code
        //
        _title2code.Name = "TITLE2CODE";
        _title2code.Caption = "Title 2";
        _title2code.DBReadOnly = true;
        _title2code.MaxLength = 100;
        this.Fields.Add(_title2code);
        //
        //_suffixcode
        //
        _suffixcode.Name = "SUFFIXCODE";
        _suffixcode.Caption = "Suffix";
        _suffixcode.DBReadOnly = true;
        _suffixcode.MaxLength = 100;
        this.Fields.Add(_suffixcode);
        //
        //_suffix2code
        //
        _suffix2code.Name = "SUFFIX2CODE";
        _suffix2code.Caption = "Suffix 2";
        _suffix2code.DBReadOnly = true;
        _suffix2code.MaxLength = 100;
        this.Fields.Add(_suffix2code);
            //
            //_nickname
            //
            _nickname.Name = "NICKNAME";
            _nickname.Caption = "Nickname";
            _nickname.DBReadOnly = true;
            _nickname.MaxLength = 100;
            this.Fields.Add(_nickname);
            //
            //_gendercode
            //
            _gendercode.Name = "GENDERCODE";
        _gendercode.Caption = "Gender";
        _gendercode.DBReadOnly = true;
        _gendercode.DataSource.Add(new global::Blackbaud.AppFx.UIModeling.Core.ValueListItem<System.Nullable<GENDERCODES>> {Value = GENDERCODES.@Unknown, Translation = "Unknown"});
        _gendercode.DataSource.Add(new global::Blackbaud.AppFx.UIModeling.Core.ValueListItem<System.Nullable<GENDERCODES>> {Value = GENDERCODES.@Male, Translation = "Male"});
        _gendercode.DataSource.Add(new global::Blackbaud.AppFx.UIModeling.Core.ValueListItem<System.Nullable<GENDERCODES>> {Value = GENDERCODES.@Female, Translation = "Female"});
        this.Fields.Add(_gendercode);
        
        //
        //_datecreated
        //
        _datecreated.Name = "DATECREATED";
        _datecreated.Caption = "Date created";
        _datecreated.DBReadOnly = true;
        this.Fields.Add(_datecreated);
        //
        //_dateupdated
        //
        _dateupdated.Name = "DATEUPDATED";
        _dateupdated.Caption = "Date last updated";
        _dateupdated.DBReadOnly = true;
        this.Fields.Add(_dateupdated);

            //
            //_msg
            //
            _msg.Name = "MSG";
	        _msg.Caption = "Message";
	        _msg.DBReadOnly = true;
	        this.Fields.Add(_msg);

            //
            //_lookupid
            //
            _lookupid.Name = "LOOKUPID";
            _lookupid.Caption = "_lookupid";
            _lookupid.MaxLength = 50;
            _lookupid.DBReadOnly = true;
            this.Fields.Add(_lookupid);
            //
            //_primaryimage
            //
            _primaryimage.Name = "PRIMARYIMAGE";
            _primaryimage.Caption = "PRIMARYIMAGE";
            _primaryimage.DBReadOnly = true;
            this.Fields.Add(_primaryimage);
            //
            //_isdmineligible
            //
            _isdmineligible.Name = "ISDMINELIGIBLE";
            _isdmineligible.Caption = "Direct Mail Ineligible";
            this.Fields.Add(_isdmineligible);
            //
            //_dmineligiblereasoncodeid
            //
            _dmineligiblereasoncodeid.Name = "DMINELIGIBLEREASONCODEID";
            _dmineligiblereasoncodeid.Caption = "Reason";
            _dmineligiblereasoncodeid.DBReadOnly = true;
            this.Fields.Add(_dmineligiblereasoncodeid);


            //
            //_infosourcecodeid
            //
            _infosourcecodeid.Name = "INFOSOURCECODE";
            _infosourcecodeid.Caption = "Information source";
            //_infosourcecodeid.CodeTableName = "INFOSOURCECODE";
            this.Fields.Add(_infosourcecodeid);
            //
            //_umhsinformation
            //
            _umhsinformation.Name = "UMHSINFORMATION";
            _umhsinformation.Caption = "MIMED Information";
            _umhsinformation.Fields.Add("MRN");
            _umhsinformation.Fields.Add("CPISEQUENCE");
            _umhsinformation.Fields.Add("LOOKUPID");
            _umhsinformation.Fields.Add("KEYNAME");
            _umhsinformation.Fields.Add("FIRSTNAME");
            _umhsinformation.Fields.Add("MIDDLENAME");
            _umhsinformation.Fields.Add("TITLECODEID");
            _umhsinformation.Fields.Add("TITLE2CODEID");
            _umhsinformation.Fields.Add("SUFFIXCODEID");
            _umhsinformation.Fields.Add("SUFFIX2CODEID");
            _umhsinformation.Fields.Add("NICKNAME");
            _umhsinformation.Fields.Add("BIRTHDATE");
            _umhsinformation.Fields.Add("GENDERCODE");
            _umhsinformation.Fields.Add("ISDMINELIGIBLE");
            _umhsinformation.Fields.Add("DMINELIGIBLEREASONCODEID");
            this.Fields.Add(_umhsinformation);

            //
            //_umhssource
            //
            _sourceinformation.Name = "UMHSSOURCE";
            _sourceinformation.Caption = "MIMED Source";
            _sourceinformation.Fields.Add("INFOSOURCECODE");
            _sourceinformation.DBReadOnly = true;
            this.Fields.Add(_sourceinformation);

            OnCreated();

	}

    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @MRN {
		get { return _mrn; }
	}

    /// <summary>
    /// CPI sequence
    /// </summary>
    [System.ComponentModel.Description("CPI sequence")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @CPISEQUENCE {
		get { return _cpisequence; }
	}

    /// <summary>
    /// First name
    /// </summary>
    [System.ComponentModel.Description("First name")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @FIRSTNAME {
		get { return _firstname; }
	}

    /// <summary>
    /// Middle name
    /// </summary>
    [System.ComponentModel.Description("Middle name")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @MIDDLENAME {
		get { return _middlename; }
	}

    /// <summary>
    /// Last name
    /// </summary>
    [System.ComponentModel.Description("Last name")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @KEYNAME {
		get { return _keyname; }
	}

    /// <summary>
    /// Birth date
    /// </summary>
    [System.ComponentModel.Description("Birth date")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.FuzzyDateField @BIRTHDATE {
		get { return _birthdate; }
	}

    /// <summary>
    /// Age
    /// </summary>
    [System.ComponentModel.Description("Age")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.IntegerField @AGE {
		get { return _age; }
	}

    /// <summary>
    /// Title
    /// </summary>
    [System.ComponentModel.Description("Title")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @TITLECODE {
		get { return _titlecode; }
	}

    /// <summary>
    /// Title 2
    /// </summary>
    [System.ComponentModel.Description("Title 2")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @TITLE2CODE {
		get { return _title2code; }
	}

    /// <summary>
    /// Suffix
    /// </summary>
    [System.ComponentModel.Description("Suffix")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @SUFFIXCODE {
		get { return _suffixcode; }
	}

    /// <summary>
    /// Suffix 2
    /// </summary>
    [System.ComponentModel.Description("Suffix 2")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @SUFFIX2CODE {
		get { return _suffix2code; }
	}

    
    /// <summary>
    /// Gender
    /// </summary>
    [System.ComponentModel.Description("Gender")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.ValueListField<System.Nullable<GENDERCODES>> @GENDERCODE {
		get { return _gendercode; }
	}

    
    /// <summary>
    /// Date created
    /// </summary>
    [System.ComponentModel.Description("Date created")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.DateField @DATECREATED {
		get { return _datecreated; }
	}

    ///<summary>
    ///Primary Image
    ///</summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
    public global::Blackbaud.AppFx.UIModeling.Core.StringField @PRIMARYIMAGE
    {
        get { return _primaryimage; }
    }

    /// <summary>
    /// Date last updated
    /// </summary>
    [System.ComponentModel.Description("Date last updated")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.DateField @DATEUPDATED {
		get { return _dateupdated; }
	}
        /// <summary>
        /// Lookup Id
        /// </summary>
        [System.ComponentModel.Description("Lookup Id")]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.154.0")]
        public global::Blackbaud.AppFx.UIModeling.Core.StringField @LOOKUPID
        {
            get { return _lookupid; }
        }

        /// <summary>
        /// Is DM Ineligible
        /// </summary>
        [System.ComponentModel.Description("Direct Mail Ineligible")]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.154.0")]
        public global::Blackbaud.AppFx.UIModeling.Core.BooleanField @ISDMINELIGIBLE
        {
            get { return _isdmineligible; }
        }


        /// <summary>
        /// Is DM Ineligible Reason code
        /// </summary>
        [System.ComponentModel.Description("Reason")]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.154.0")]
        public global::Blackbaud.AppFx.UIModeling.Core.StringField @DMINELIGIBLEREASONCODEID
        {
            get { return _dmineligiblereasoncodeid; }
        }


        /// <summary>
        /// UMHS source
        /// </summary>
        [System.ComponentModel.Description("MIMED source")]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
        public global::Blackbaud.AppFx.UIModeling.Core.GroupField @UMHSINFORMATION
        {
            get { return _sourceinformation; }
        }

    }


}
