//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by BBUIModelLibrary
//     Version:  4.0.159.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace UM.CustomFx.GratefulPatient.UIModel
{

/// <summary>
/// Represents the UI model for the 'UMHS Interaction View Data Form' data form
/// </summary>
[global::Blackbaud.AppFx.UIModeling.Core.DataFormUIModelMetadata(global::Blackbaud.AppFx.UIModeling.Core.DataFormMode.View, "fc825438-2a74-43a7-b417-0deb017eb863", "a20b702c-9466-42aa-9cc0-5060a9036f28", "MIMED Interaction")]
public partial class @UMHSInteractionViewDataFormUIModel : global::Blackbaud.AppFx.UIModeling.Core.DataFormUIModel
{

#region "Extensibility methods"

	partial void OnCreated();

#endregion

    private global::Blackbaud.AppFx.UIModeling.Core.StringField _participants;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _comment;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _belongsto;
    private global::Blackbaud.AppFx.UIModeling.Core.DateField _expecteddate;
    private global::Blackbaud.AppFx.UIModeling.Core.DateField _actualdate;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _objective;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _status;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _owner;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _type;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _interactioncategory;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _interactionsubcategory;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _sites;
    private global::Blackbaud.AppFx.UIModeling.Core.HourMinuteField _expectedstarttime;
    private global::Blackbaud.AppFx.UIModeling.Core.HourMinuteField _expectedendtime;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _timezone;
    private global::Blackbaud.AppFx.UIModeling.Core.HourMinuteField _actualstarttime;
    private global::Blackbaud.AppFx.UIModeling.Core.HourMinuteField _actualendtime;

	[System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public @UMHSInteractionViewDataFormUIModel() : base()
	{


        _participants = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _comment = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _belongsto = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _expecteddate = new global::Blackbaud.AppFx.UIModeling.Core.DateField();
        _actualdate = new global::Blackbaud.AppFx.UIModeling.Core.DateField();
        _objective = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _status = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _owner = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _type = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _interactioncategory = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _interactionsubcategory = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _sites = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _expectedstarttime = new global::Blackbaud.AppFx.UIModeling.Core.HourMinuteField();
        _expectedendtime = new global::Blackbaud.AppFx.UIModeling.Core.HourMinuteField();
        _timezone = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _actualstarttime = new global::Blackbaud.AppFx.UIModeling.Core.HourMinuteField();
        _actualendtime = new global::Blackbaud.AppFx.UIModeling.Core.HourMinuteField();

        this.Mode = global::Blackbaud.AppFx.UIModeling.Core.DataFormMode.View;
        this.DataFormTemplateId = new System.Guid("fc825438-2a74-43a7-b417-0deb017eb863");
        this.DataFormInstanceId = new System.Guid("a20b702c-9466-42aa-9cc0-5060a9036f28");
        this.RecordType = "MIMED Interaction";
        this.UserInterfaceUrl = "browser/htmlforms/custom/um.customfx.gratefulpatient/UMHSInteractionsViewForm.html";

        //
        //_participants
        //
        _participants.Name = "PARTICIPANTS";
        _participants.Caption = "Participants";
        _participants.DBReadOnly = true;
        this.Fields.Add(_participants);
        //
        //_comment
        //
        _comment.Name = "COMMENT";
        _comment.Caption = "Comments";
        _comment.DBReadOnly = true;
        this.Fields.Add(_comment);
        //
        //_belongsto
        //
        _belongsto.Name = "BELONGSTO";
        _belongsto.Caption = "Belongs to";
        _belongsto.DBReadOnly = true;
        _belongsto.MaxLength = 700;
        this.Fields.Add(_belongsto);
        //
        //_expecteddate
        //
        _expecteddate.Name = "EXPECTEDDATE";
        _expecteddate.Caption = "Expected date";
        _expecteddate.DBReadOnly = true;
        this.Fields.Add(_expecteddate);
        //
        //_actualdate
        //
        _actualdate.Name = "ACTUALDATE";
        _actualdate.Caption = "Actual date";
        _actualdate.DBReadOnly = true;
        this.Fields.Add(_actualdate);
        //
        //_objective
        //
        _objective.Name = "OBJECTIVE";
        _objective.Caption = "Summary";
        _objective.DBReadOnly = true;
        _objective.MaxLength = 100;
        this.Fields.Add(_objective);
        //
        //_status
        //
        _status.Name = "STATUS";
        _status.Caption = "Status";
        _status.DBReadOnly = true;
        _status.MaxLength = 100;
        this.Fields.Add(_status);
        //
        //_owner
        //
        _owner.Name = "OWNER";
        _owner.Caption = "Owner";
        _owner.DBReadOnly = true;
        _owner.MaxLength = 154;
        this.Fields.Add(_owner);
        //
        //_type
        //
        _type.Name = "TYPE";
        _type.Caption = "Contact method";
        _type.DBReadOnly = true;
        _type.MaxLength = 100;
        this.Fields.Add(_type);
        //
        //_interactioncategory
        //
        _interactioncategory.Name = "INTERACTIONCATEGORY";
        _interactioncategory.Caption = "Category";
        _interactioncategory.DBReadOnly = true;
        _interactioncategory.MaxLength = 100;
        this.Fields.Add(_interactioncategory);
        //
        //_interactionsubcategory
        //
        _interactionsubcategory.Name = "INTERACTIONSUBCATEGORY";
        _interactionsubcategory.Caption = "Subcategory";
        _interactionsubcategory.DBReadOnly = true;
        _interactionsubcategory.MaxLength = 100;
        this.Fields.Add(_interactionsubcategory);
        //
        //_sites
        //
        _sites.Name = "SITES";
        _sites.Caption = "Sites";
        _sites.DBReadOnly = true;
        _sites.MaxLength = 1024;
        this.Fields.Add(_sites);
        //
        //_expectedstarttime
        //
        _expectedstarttime.Name = "EXPECTEDSTARTTIME";
        _expectedstarttime.Caption = "Expected start time";
        _expectedstarttime.DBReadOnly = true;
        this.Fields.Add(_expectedstarttime);
        //
        //_expectedendtime
        //
        _expectedendtime.Name = "EXPECTEDENDTIME";
        _expectedendtime.Caption = "Expected end time";
        _expectedendtime.DBReadOnly = true;
        this.Fields.Add(_expectedendtime);
        //
        //_timezone
        //
        _timezone.Name = "TIMEZONE";
        _timezone.Caption = "Time zone";
        _timezone.DBReadOnly = true;
        _timezone.MaxLength = 255;
        this.Fields.Add(_timezone);
        //
        //_actualstarttime
        //
        _actualstarttime.Name = "ACTUALSTARTTIME";
        _actualstarttime.Caption = "Actual start time";
        _actualstarttime.DBReadOnly = true;
        this.Fields.Add(_actualstarttime);
        //
        //_actualendtime
        //
        _actualendtime.Name = "ACTUALENDTIME";
        _actualendtime.Caption = "Actual end time";
        _actualendtime.DBReadOnly = true;
        this.Fields.Add(_actualendtime);

		OnCreated();

	}

    /// <summary>
    /// Participants
    /// </summary>
    [System.ComponentModel.Description("Participants")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @PARTICIPANTS {
		get { return _participants; }
	}

    /// <summary>
    /// Comments
    /// </summary>
    [System.ComponentModel.Description("Comments")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @COMMENT {
		get { return _comment; }
	}

    /// <summary>
    /// Belongs to
    /// </summary>
    [System.ComponentModel.Description("Belongs to")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @BELONGSTO {
		get { return _belongsto; }
	}

    /// <summary>
    /// Expected date
    /// </summary>
    [System.ComponentModel.Description("Expected date")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.DateField @EXPECTEDDATE {
		get { return _expecteddate; }
	}

    /// <summary>
    /// Actual date
    /// </summary>
    [System.ComponentModel.Description("Actual date")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.DateField @ACTUALDATE {
		get { return _actualdate; }
	}

    /// <summary>
    /// Summary
    /// </summary>
    [System.ComponentModel.Description("Summary")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @OBJECTIVE {
		get { return _objective; }
	}

    /// <summary>
    /// Status
    /// </summary>
    [System.ComponentModel.Description("Status")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @STATUS {
		get { return _status; }
	}

    /// <summary>
    /// Owner
    /// </summary>
    [System.ComponentModel.Description("Owner")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @OWNER {
		get { return _owner; }
	}

    /// <summary>
    /// Contact method
    /// </summary>
    [System.ComponentModel.Description("Contact method")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @TYPE {
		get { return _type; }
	}

    /// <summary>
    /// Category
    /// </summary>
    [System.ComponentModel.Description("Category")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @INTERACTIONCATEGORY {
		get { return _interactioncategory; }
	}

    /// <summary>
    /// Subcategory
    /// </summary>
    [System.ComponentModel.Description("Subcategory")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @INTERACTIONSUBCATEGORY {
		get { return _interactionsubcategory; }
	}

    /// <summary>
    /// Sites
    /// </summary>
    [System.ComponentModel.Description("Sites")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @SITES {
		get { return _sites; }
	}

    /// <summary>
    /// Expected start time
    /// </summary>
    [System.ComponentModel.Description("Expected start time")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.HourMinuteField @EXPECTEDSTARTTIME {
		get { return _expectedstarttime; }
	}

    /// <summary>
    /// Expected end time
    /// </summary>
    [System.ComponentModel.Description("Expected end time")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.HourMinuteField @EXPECTEDENDTIME {
		get { return _expectedendtime; }
	}

    /// <summary>
    /// Time zone
    /// </summary>
    [System.ComponentModel.Description("Time zone")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @TIMEZONE {
		get { return _timezone; }
	}

    /// <summary>
    /// Actual start time
    /// </summary>
    [System.ComponentModel.Description("Actual start time")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.HourMinuteField @ACTUALSTARTTIME {
		get { return _actualstarttime; }
	}

    /// <summary>
    /// Actual end time
    /// </summary>
    [System.ComponentModel.Description("Actual end time")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.HourMinuteField @ACTUALENDTIME {
		get { return _actualendtime; }
	}

}


}
