//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by BBUIModelLibrary
//     Version:  4.0.159.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace UM.CustomFx.GratefulPatient.UIModel
{

/// <summary>
/// Represents the UI model for the 'UMHS Phone View Data Form' data form
/// </summary>
[global::Blackbaud.AppFx.UIModeling.Core.DataFormUIModelMetadata(global::Blackbaud.AppFx.UIModeling.Core.DataFormMode.View, "a55fc2f8-f9cc-479a-82c5-e41102319793", "dc0be8a6-d96c-4374-aee5-897404ad975b", "MIMED Data")]
public partial class @UMHSPhoneViewDataFormUIModel : global::Blackbaud.AppFx.UIModeling.Core.DataFormUIModel
{

#region "Extensibility methods"

	partial void OnCreated();

#endregion

    private global::Blackbaud.AppFx.UIModeling.Core.StringField _phonetypecode;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _phonenumber;
    private global::Blackbaud.AppFx.UIModeling.Core.BooleanField _primary;
    private global::Blackbaud.AppFx.UIModeling.Core.BooleanField _donotcall;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _donotcallreasoncode;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _infosourcecode;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _infosourcecomments;
    private global::Blackbaud.AppFx.UIModeling.Core.DateField _startdate;
    private global::Blackbaud.AppFx.UIModeling.Core.DateField _enddate;
        private global::Blackbaud.AppFx.UIModeling.Core.TimeField _callbefore;
        private global::Blackbaud.AppFx.UIModeling.Core.TimeField _callafter;
        private global::Blackbaud.AppFx.UIModeling.Core.DateField _dateadded;
    private global::Blackbaud.AppFx.UIModeling.Core.BooleanField _isconfidential;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _country;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _confidentialimage;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _confidentialdescription;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _primaryimage;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _enddatedescription;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _donotcallimage;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _donotcalldescription;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _hyphen;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _contactimage;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _contactdescription;

	[System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public @UMHSPhoneViewDataFormUIModel() : base()
	{


        _phonetypecode = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _phonenumber = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _primary = new global::Blackbaud.AppFx.UIModeling.Core.BooleanField();
        _donotcall = new global::Blackbaud.AppFx.UIModeling.Core.BooleanField();
        _donotcallreasoncode = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _infosourcecode = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _infosourcecomments = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _startdate = new global::Blackbaud.AppFx.UIModeling.Core.DateField();
        _enddate = new global::Blackbaud.AppFx.UIModeling.Core.DateField();
            _callbefore = new global::Blackbaud.AppFx.UIModeling.Core.TimeField();
            _callafter = new global::Blackbaud.AppFx.UIModeling.Core.TimeField();
            _dateadded = new global::Blackbaud.AppFx.UIModeling.Core.DateField();
        _isconfidential = new global::Blackbaud.AppFx.UIModeling.Core.BooleanField();
        _country = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _confidentialimage = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _confidentialdescription = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _primaryimage = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _enddatedescription = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _donotcallimage = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _donotcalldescription = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _hyphen = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _contactimage = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _contactdescription = new global::Blackbaud.AppFx.UIModeling.Core.StringField();

        this.Mode = global::Blackbaud.AppFx.UIModeling.Core.DataFormMode.View;
        this.DataFormTemplateId = new System.Guid("a55fc2f8-f9cc-479a-82c5-e41102319793");
        this.DataFormInstanceId = new System.Guid("dc0be8a6-d96c-4374-aee5-897404ad975b");
        this.RecordType = "MIMED Data";
        this.FixedDialog = true;
        this.UserInterfaceUrl = "browser/htmlforms/custom/um.customfx.gratefulpatient/UMHSPhoneViewDataForm.html";

        //
        //_phonetypecode
        //
        _phonetypecode.Name = "PHONETYPECODE";
        _phonetypecode.Caption = "Type";
        _phonetypecode.DBReadOnly = true;
        _phonetypecode.MaxLength = 100;
        this.Fields.Add(_phonetypecode);
        //
        //_phonenumber
        //
        _phonenumber.Name = "PHONENUMBER";
        _phonenumber.Caption = "Number";
        _phonenumber.DBReadOnly = true;
        _phonenumber.MaxLength = 100;
        this.Fields.Add(_phonenumber);
        //
        //_primary
        //
        _primary.Name = "PRIMARY";
        _primary.Caption = "Primary";
        _primary.DBReadOnly = true;
        this.Fields.Add(_primary);
        //
        //_donotcall
        //
        _donotcall.Name = "DONOTCALL";
        _donotcall.Caption = "Do not call";
        _donotcall.DBReadOnly = true;
        this.Fields.Add(_donotcall);
        //
        //_donotcallreasoncode
        //
        _donotcallreasoncode.Name = "DONOTCALLREASONCODE";
        _donotcallreasoncode.Caption = "Reason";
        _donotcallreasoncode.DBReadOnly = true;
        _donotcallreasoncode.MaxLength = 100;
        this.Fields.Add(_donotcallreasoncode);
        //
        //_infosourcecode
        //
        _infosourcecode.Name = "INFOSOURCECODE";
        _infosourcecode.Caption = "Information source";
        _infosourcecode.DBReadOnly = true;
        _infosourcecode.MaxLength = 100;
        this.Fields.Add(_infosourcecode);
        //
        //_infosourcecomments
        //
        _infosourcecomments.Name = "INFOSOURCECOMMENTS";
        _infosourcecomments.Caption = "Comments";
        _infosourcecomments.DBReadOnly = true;
        _infosourcecomments.MaxLength = 256;
        this.Fields.Add(_infosourcecomments);
        //
        //_startdate
        //
        _startdate.Name = "STARTDATE";
        _startdate.Caption = "Start date";
        _startdate.DBReadOnly = true;
        this.Fields.Add(_startdate);
        //
        //_enddate
        //
        _enddate.Name = "ENDDATE";
        _enddate.Caption = "End date";
        _enddate.DBReadOnly = true;
        this.Fields.Add(_enddate);
            //
            //_callbefore
            //
            _callbefore.Name = "CALLBEFORE";
            _callbefore.Caption = "Call before";
            this.Fields.Add(_callbefore);
            //
            //_callafter
            //
            _callafter.Name = "CALLAFTER";
            _callafter.Caption = "Call after";
            this.Fields.Add(_callafter);

            //
            //_dateadded
            //
            _dateadded.Name = "DATEADDED";
        _dateadded.Caption = "Date added";
        _dateadded.DBReadOnly = true;
        this.Fields.Add(_dateadded);
        //
        //_isconfidential
        //
        _isconfidential.Name = "ISCONFIDENTIAL";
        _isconfidential.Caption = "Confidential";
        _isconfidential.DBReadOnly = true;
        this.Fields.Add(_isconfidential);
        //
        //_country
        //
        _country.Name = "COUNTRY";
        _country.Caption = "Country";
        _country.DBReadOnly = true;
        _country.MaxLength = 100;
        this.Fields.Add(_country);
        //
        //_confidentialimage
        //
        _confidentialimage.Name = "CONFIDENTIALIMAGE";
        _confidentialimage.Caption = "CONFIDENTIALIMAGE";
        _confidentialimage.DBReadOnly = true;
        this.Fields.Add(_confidentialimage);
        //
        //_confidentialdescription
        //
        _confidentialdescription.Name = "CONFIDENTIALDESCRIPTION";
        _confidentialdescription.Caption = "CONFIDENTIALDESCRIPTION";
        _confidentialdescription.DBReadOnly = true;
        this.Fields.Add(_confidentialdescription);
        //
        //_primaryimage
        //
        _primaryimage.Name = "PRIMARYIMAGE";
        _primaryimage.Caption = "PRIMARYIMAGE";
        _primaryimage.DBReadOnly = true;
        this.Fields.Add(_primaryimage);
        //
        //_enddatedescription
        //
        _enddatedescription.Name = "ENDDATEDESCRIPTION";
        _enddatedescription.Caption = "ENDDATEDESCRIPTION";
        _enddatedescription.DBReadOnly = true;
        this.Fields.Add(_enddatedescription);
        //
        //_donotcallimage
        //
        _donotcallimage.Name = "DONOTCALLIMAGE";
        _donotcallimage.Caption = "DONOTCALLIMAGE";
        _donotcallimage.DBReadOnly = true;
        this.Fields.Add(_donotcallimage);
        //
        //_donotcalldescription
        //
        _donotcalldescription.Name = "DONOTCALLDESCRIPTION";
        _donotcalldescription.Caption = "DONOTCALLDESCRIPTION";
        _donotcalldescription.DBReadOnly = true;
        this.Fields.Add(_donotcalldescription);
        //
        //_hyphen
        //
        _hyphen.Name = "HYPHEN";
        _hyphen.Caption = "HYPHEN";
        _hyphen.DBReadOnly = true;
        this.Fields.Add(_hyphen);
        //
        //_contactimage
        //
        _contactimage.Name = "CONTACTIMAGE";
        _contactimage.Caption = "CONTACTIMAGE";
        _contactimage.DBReadOnly = true;
        this.Fields.Add(_contactimage);
        //
        //_contactdescription
        //
        _contactdescription.Name = "CONTACTDESCRIPTION";
        _contactdescription.Caption = "CONTACTDESCRIPTION";
        _contactdescription.DBReadOnly = true;
        this.Fields.Add(_contactdescription);

		OnCreated();

	}

    /// <summary>
    /// Type
    /// </summary>
    [System.ComponentModel.Description("Type")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @PHONETYPECODE {
		get { return _phonetypecode; }
	}

    /// <summary>
    /// Number
    /// </summary>
    [System.ComponentModel.Description("Number")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @PHONENUMBER {
		get { return _phonenumber; }
	}

    /// <summary>
    /// Primary
    /// </summary>
    [System.ComponentModel.Description("Primary")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.BooleanField @PRIMARY {
		get { return _primary; }
	}

    /// <summary>
    /// Do not call
    /// </summary>
    [System.ComponentModel.Description("Do not call")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.BooleanField @DONOTCALL {
		get { return _donotcall; }
	}

    /// <summary>
    /// Reason
    /// </summary>
    [System.ComponentModel.Description("Reason")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @DONOTCALLREASONCODE {
		get { return _donotcallreasoncode; }
	}

    /// <summary>
    /// Information source
    /// </summary>
    [System.ComponentModel.Description("Information source")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @INFOSOURCECODE {
		get { return _infosourcecode; }
	}

    /// <summary>
    /// Comments
    /// </summary>
    [System.ComponentModel.Description("Comments")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @INFOSOURCECOMMENTS {
		get { return _infosourcecomments; }
	}

    /// <summary>
    /// Start date
    /// </summary>
    [System.ComponentModel.Description("Start date")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.DateField @STARTDATE {
		get { return _startdate; }
	}

    /// <summary>
    /// End date
    /// </summary>
    [System.ComponentModel.Description("End date")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.DateField @ENDDATE {
		get { return _enddate; }
	}


        /// <summary>
        /// Call before
        /// </summary>
        [System.ComponentModel.Description("Call before")]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
        public global::Blackbaud.AppFx.UIModeling.Core.TimeField @CALLBEFORE
        {
            get { return _callbefore; }
        }

        /// <summary>
        /// Call after
        /// </summary>
        [System.ComponentModel.Description("Call after")]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
        public global::Blackbaud.AppFx.UIModeling.Core.TimeField @CALLAFTER
        {
            get { return _callafter; }
        }



        /// <summary>
        /// Date added
        /// </summary>
        [System.ComponentModel.Description("Date added")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.DateField @DATEADDED {
		get { return _dateadded; }
	}

    /// <summary>
    /// Confidential
    /// </summary>
    [System.ComponentModel.Description("Confidential")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.BooleanField @ISCONFIDENTIAL {
		get { return _isconfidential; }
	}

    /// <summary>
    /// Country
    /// </summary>
    [System.ComponentModel.Description("Country")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @COUNTRY {
		get { return _country; }
	}

    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @CONFIDENTIALIMAGE {
		get { return _confidentialimage; }
	}

    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @CONFIDENTIALDESCRIPTION {
		get { return _confidentialdescription; }
	}

    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @PRIMARYIMAGE {
		get { return _primaryimage; }
	}

    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @ENDDATEDESCRIPTION {
		get { return _enddatedescription; }
	}

    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @DONOTCALLIMAGE {
		get { return _donotcallimage; }
	}

    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @DONOTCALLDESCRIPTION {
		get { return _donotcalldescription; }
	}

    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @HYPHEN {
		get { return _hyphen; }
	}

    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @CONTACTIMAGE {
		get { return _contactimage; }
	}

    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @CONTACTDESCRIPTION {
		get { return _contactdescription; }
	}

}


}
