//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by BBUIModelLibrary
//     Version:  4.0.154.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace UM.CustomFx.GratefulPatient.UIModel
{

/// <summary>
/// Represents the UI model for the 'UMHS Data Add Form' data form
/// </summary>
[global::Blackbaud.AppFx.UIModeling.Core.DataFormUIModelMetadata(global::Blackbaud.AppFx.UIModeling.Core.DataFormMode.Add, "c7976657-1974-4225-b724-f143b7651998", "a3e4ea4a-1328-467f-99cd-d352c409eee8", "MIMED Data", "Constituent")]
public partial class @UMHSDataFormUIModel : global::Blackbaud.AppFx.UIModeling.Core.DataFormUIModel
{

#region "Enums"

    /// <summary>
    /// Enumerated values for use with the GENDERCODE property
    /// </summary>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.154.0")]
	public enum GENDERCODES : int
	{
        @Unknown = 0,
        @Male = 1,
        @Female = 2
	}

#endregion

#region "Extensibility methods"

	partial void OnCreated();

#endregion

    private global::Blackbaud.AppFx.UIModeling.Core.StringField _mrn;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _cpisequence;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _firstname;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _middlename;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _keyname;
    private global::Blackbaud.AppFx.UIModeling.Core.FuzzyDateField _birthdate;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _age;
    private global::Blackbaud.AppFx.UIModeling.Core.CodeTableField _titlecodeid;
    private global::Blackbaud.AppFx.UIModeling.Core.CodeTableField _title2codeid;
    private global::Blackbaud.AppFx.UIModeling.Core.CodeTableField _suffixcodeid;
    private global::Blackbaud.AppFx.UIModeling.Core.CodeTableField _suffix2codeid;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _nickname;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _lookupid;
    private global::Blackbaud.AppFx.UIModeling.Core.CodeTableField _infosourcecodeid;
    private global::Blackbaud.AppFx.UIModeling.Core.BooleanField _isdmineligible;
        private global::Blackbaud.AppFx.UIModeling.Core.CodeTableField _dmineligiblereasoncodeid;
    private global::Blackbaud.AppFx.UIModeling.Core.ValueListField<System.Nullable<GENDERCODES>> _gendercode;
        private global::Blackbaud.AppFx.UIModeling.Core.GroupField _umhsinformation;
        private global::Blackbaud.AppFx.UIModeling.Core.GroupField _sourceinformation;
        


        [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.154.0")]
	public @UMHSDataFormUIModel() : base()
	{


        _mrn = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _cpisequence = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _firstname = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _middlename = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _keyname = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _birthdate = new global::Blackbaud.AppFx.UIModeling.Core.FuzzyDateField();
        _age = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _titlecodeid = new global::Blackbaud.AppFx.UIModeling.Core.CodeTableField();
        _title2codeid = new global::Blackbaud.AppFx.UIModeling.Core.CodeTableField();
        _suffixcodeid = new global::Blackbaud.AppFx.UIModeling.Core.CodeTableField();
        _suffix2codeid = new global::Blackbaud.AppFx.UIModeling.Core.CodeTableField();
        _nickname = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _lookupid = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _infosourcecodeid = new global::Blackbaud.AppFx.UIModeling.Core.CodeTableField();
        _isdmineligible = new global::Blackbaud.AppFx.UIModeling.Core.BooleanField();
            _dmineligiblereasoncodeid = new global::Blackbaud.AppFx.UIModeling.Core.CodeTableField();
            _gendercode = new global::Blackbaud.AppFx.UIModeling.Core.ValueListField<System.Nullable<GENDERCODES>>();
            _umhsinformation = new global::Blackbaud.AppFx.UIModeling.Core.GroupField();
            _sourceinformation = new global::Blackbaud.AppFx.UIModeling.Core.GroupField();

            this.Mode = global::Blackbaud.AppFx.UIModeling.Core.DataFormMode.Add;
        this.DataFormTemplateId = new System.Guid("c7976657-1974-4225-b724-f143b7651998");
        this.DataFormInstanceId = new System.Guid("a3e4ea4a-1328-467f-99cd-d352c409eee8");
        this.RecordType = "MIMED Data";
        this.ContextRecordType = "Constituent";
        this.FixedDialog = true;
        this.UserInterfaceUrl = "browser/htmlforms/custom/um.customfx.gratefulpatient/UMHSDataForm.html";

            //
            //_mrn
            //
            _mrn.Name = "MRN";
            _mrn.Caption = "MRN";           
            _mrn.MaxLength = 50;
        this.Fields.Add(_mrn);
        //
        //_cpisequence
        //
        _cpisequence.Name = "CPISEQUENCE";
        _cpisequence.Caption = "CPI seq";
        _cpisequence.MaxLength = 50;
        this.Fields.Add(_cpisequence);
        //
        //_lookupid
        //
        _lookupid.Name = "LOOKUPID";
        _lookupid.Caption = "_lookupid";
        _lookupid.MaxLength = 50;
        _lookupid.DBReadOnly = true;
        this.Fields.Add(_lookupid);
        //
        //_firstname
        //
       _firstname.Name = "FIRSTNAME";
        _firstname.Caption = "First name";
        _firstname.Required = true;
        _firstname.MaxLength = 50;
        this.Fields.Add(_firstname);
        //
        //_middlename
        //
        _middlename.Name = "MIDDLENAME";
        _middlename.Caption = "Middle name";
        _middlename.MaxLength = 50;
        this.Fields.Add(_middlename);
        //
        //_keyname
        //
        _keyname.Name = "KEYNAME";
        _keyname.Caption = "Last name";
        _keyname.Required = true;
        _keyname.MaxLength = 100;
        this.Fields.Add(_keyname);
        //
        //_birthdate
        //
        _birthdate.Name = "BIRTHDATE";
        _birthdate.Caption = "Birth date";
       // _birthdate.Required = true;
        this.Fields.Add(_birthdate);
        //
        //_age
        //
        _age.Name = "AGE";
        _age.Caption = "Age";
        _age.DBReadOnly = true;
        this.Fields.Add(_age);
        //
        //_titlecodeid
        //
        _titlecodeid.Name = "TITLECODEID";
        _titlecodeid.Caption = "Title";
        _titlecodeid.CodeTableName = "TITLECODE";
        this.Fields.Add(_titlecodeid);
        //
        //_title2codeid
        //
        _title2codeid.Name = "TITLE2CODEID";
        _title2codeid.Caption = "Title 2";
        _title2codeid.CodeTableName = "TITLECODE";
        this.Fields.Add(_title2codeid);
        //
        //_suffixcodeid
        //
        _suffixcodeid.Name = "SUFFIXCODEID";
        _suffixcodeid.Caption = "Suffix";
        _suffixcodeid.CodeTableName = "SUFFIXCODE";
        this.Fields.Add(_suffixcodeid);
        //
        //_suffix2codeid
        //
        _suffix2codeid.Name = "SUFFIX2CODEID";
        _suffix2codeid.Caption = "Suffix 2";
        _suffix2codeid.CodeTableName = "SUFFIXCODE";
        this.Fields.Add(_suffix2codeid);
            //
            //_nickname
            //
            _nickname.Name = "NICKNAME";
            _nickname.Caption = "Nickname";
            _nickname.MaxLength = 50;
            this.Fields.Add(_nickname);

           
            //
            //_infosourcecodeid
            //
            _infosourcecodeid.Name = "INFOSOURCECODEID";
            _infosourcecodeid.Caption = "Information source";
            _infosourcecodeid.CodeTableName = "INFOSOURCECODE";
            this.Fields.Add(_infosourcecodeid);
            //
            //_isdmineligible
            //
            _isdmineligible.Name = "ISDMINELIGIBLE";
            _isdmineligible.Caption = "Direct Mail Ineligible";
            this.Fields.Add(_isdmineligible);

            _dmineligiblereasoncodeid.Name = "DMINELIGIBLEREASONCODEID";
            _dmineligiblereasoncodeid.Caption = "Reason";
            _dmineligiblereasoncodeid.CodeTableName = "USR_UMHS_DMINELIGIBLEREASONCODE";
            this.Fields.Add(_dmineligiblereasoncodeid);

            //
            //_gendercode
            //
            _gendercode.Name = "GENDERCODE";
        _gendercode.Caption = "Gender";
        _gendercode.DataSource.Add(new global::Blackbaud.AppFx.UIModeling.Core.ValueListItem<System.Nullable<GENDERCODES>> {Value = GENDERCODES.@Unknown, Translation = "Unknown"});
        _gendercode.DataSource.Add(new global::Blackbaud.AppFx.UIModeling.Core.ValueListItem<System.Nullable<GENDERCODES>> {Value = GENDERCODES.@Male, Translation = "Male"});
        _gendercode.DataSource.Add(new global::Blackbaud.AppFx.UIModeling.Core.ValueListItem<System.Nullable<GENDERCODES>> {Value = GENDERCODES.@Female, Translation = "Female"});
        _gendercode.Value = GENDERCODES.@Unknown;
        this.Fields.Add(_gendercode);


            //
            //_umhsinformation
            //
            _umhsinformation.Name = "UMHSINFORMATION";
            _umhsinformation.Caption = "MIMED Information";
            _umhsinformation.Fields.Add("MRN");
            _umhsinformation.Fields.Add("CPISEQUENCE");
            _umhsinformation.Fields.Add("LOOKUPID");
            _umhsinformation.Fields.Add("KEYNAME");
            _umhsinformation.Fields.Add("FIRSTNAME");
            _umhsinformation.Fields.Add("MIDDLENAME");
            _umhsinformation.Fields.Add("TITLECODEID");
            _umhsinformation.Fields.Add("TITLE2CODEID");
            _umhsinformation.Fields.Add("SUFFIXCODEID");
            _umhsinformation.Fields.Add("SUFFIX2CODEID");
            _umhsinformation.Fields.Add("NICKNAME");
            _umhsinformation.Fields.Add("BIRTHDATE");
            _umhsinformation.Fields.Add("GENDERCODE");
            _umhsinformation.Fields.Add("ISDMINELIGIBLE");
            _umhsinformation.Fields.Add("DMINELIGIBLEREASONCODEID");
           this.Fields.Add(_umhsinformation);

            //
            //_umhssource
            //
            _sourceinformation.Name = "UMHSSOURCE";
            _sourceinformation.Caption = "MIMED Source";
            _sourceinformation.Fields.Add("INFOSOURCECODEID");
            _sourceinformation.DBReadOnly = true;
            this.Fields.Add(_sourceinformation);

            OnCreated();

	}

    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.154.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @MRN {
		get { return _mrn; }
	}

    /// <summary>
    /// CPI sequence
    /// </summary>
    [System.ComponentModel.Description("CPI sequence")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.154.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @CPISEQUENCE {
		get { return _cpisequence; }
	}

    /// <summary>
    /// First name
    /// </summary>
    [System.ComponentModel.Description("First name")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.154.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @FIRSTNAME {
		get { return _firstname; }
	}

    /// <summary>
    /// Middle name
    /// </summary>
    [System.ComponentModel.Description("Middle name")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.154.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @MIDDLENAME {
		get { return _middlename; }
	}

    /// <summary>
    /// Last name
    /// </summary>
    [System.ComponentModel.Description("Last name")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.154.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @KEYNAME {
		get { return _keyname; }
	}

    /// <summary>
    /// Birth date
    /// </summary>
    [System.ComponentModel.Description("Birth date")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.154.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.FuzzyDateField @BIRTHDATE {
		get { return _birthdate; }
	}

    /// <summary>
    /// Age
    /// </summary>
    [System.ComponentModel.Description("Age")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.154.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @AGE {
		get { return _age; }
	}

    /// <summary>
    /// Title
    /// </summary>
    [System.ComponentModel.Description("Title")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.154.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.CodeTableField @TITLECODEID {
		get { return _titlecodeid; }
	}

    /// <summary>
    /// Title 2
    /// </summary>
    [System.ComponentModel.Description("Title 2")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.154.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.CodeTableField @TITLE2CODEID {
		get { return _title2codeid; }
	}

    /// <summary>
    /// Suffix
    /// </summary>
    [System.ComponentModel.Description("Suffix")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.154.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.CodeTableField @SUFFIXCODEID {
		get { return _suffixcodeid; }
	}

    /// <summary>
    /// Suffix 2
    /// </summary>
    [System.ComponentModel.Description("Suffix 2")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.154.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.CodeTableField @SUFFIX2CODEID {
		get { return _suffix2codeid; }
	}

        /// <summary>
        /// Nickname
        /// </summary>
        [System.ComponentModel.Description("Nickname")]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.154.0")]
        public global::Blackbaud.AppFx.UIModeling.Core.StringField @NICKNAME
        {
            get { return _nickname; }
        }
        /// <summary>
        /// Lookup Id
        /// </summary>
        [System.ComponentModel.Description("Lookup Id")]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.154.0")]
        public global::Blackbaud.AppFx.UIModeling.Core.StringField @LOOKUPID
        {
            get { return _lookupid; }
        }

        /// <summary>
        /// Is DM Ineligible
        /// </summary>
        [System.ComponentModel.Description("Direct Mail Ineligible")]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.154.0")]
        public global::Blackbaud.AppFx.UIModeling.Core.BooleanField @ISDMINELIGIBLE
        {
            get { return _isdmineligible; }
        }

        /// <summary>
        /// Is DM Ineligible Reason code ID
        /// </summary>
        [System.ComponentModel.Description("Reason")]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.154.0")]
        public global::Blackbaud.AppFx.UIModeling.Core.CodeTableField @DMINELIGIBLEREASONCODEID
        {
            get { return _dmineligiblereasoncodeid; }
        }

        /// <summary>
        /// UMHS source
        /// </summary>
        [System.ComponentModel.Description("MIMED source")]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
        public global::Blackbaud.AppFx.UIModeling.Core.GroupField @UMHSINFORMATION
        {
            get { return _sourceinformation; }
        }

        /// <summary>
        /// Gender
        /// </summary>
        [System.ComponentModel.Description("Gender")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.154.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.ValueListField<System.Nullable<GENDERCODES>> @GENDERCODE {
		get { return _gendercode; }
	}

    

}


}
