//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by BBUIModelLibrary
//     Version:  4.0.159.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace UM.CustomFx.GratefulPatient.UIModel
{

/// <summary>
/// Represents the UI model for the 'UMHSInterestFormSITES' data form
/// </summary>
public partial class @UMHSInterestFormSITESUIModel : global::Blackbaud.AppFx.UIModeling.Core.UIModel
{

#region "Extensibility methods"

	partial void OnCreated();

#endregion

    private global::Blackbaud.AppFx.UIModeling.Core.GuidField _id;

	[System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public @UMHSInterestFormSITESUIModel() : base()
	{


        _id = new global::Blackbaud.AppFx.UIModeling.Core.GuidField();
       
        //
        //_id
        //
        _id.Name = "ID";
        _id.Caption = "ID";
        _id.Visible = false;
        this.Fields.Add(_id);
        

		OnCreated();

	}

    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.GuidField @ID {
		get { return _id; }
	}

}


}
