//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by BBUIModelLibrary
//     Version:  4.0.159.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace UM.CustomFx.GratefulPatient.UIModel
{

/// <summary>
/// Represents the UI model for the 'UMHS Address View Data Form' data form
/// </summary>
[global::Blackbaud.AppFx.UIModeling.Core.DataFormUIModelMetadata(global::Blackbaud.AppFx.UIModeling.Core.DataFormMode.View, "f1f35dc0-946f-4170-ad74-9fc7b9fedc83", "75f282f7-9e30-41fb-84ca-321bc8c9eb98", "MIMED Data")]
public partial class @UMHSAddressViewDataFormUIModel : global::Blackbaud.AppFx.UIModeling.Core.DataFormUIModel
{

#region "Extensibility methods"

	partial void OnCreated();

#endregion

    private global::Blackbaud.AppFx.UIModeling.Core.StringField _address;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _country;
    private global::Blackbaud.AppFx.UIModeling.Core.BooleanField _primary;
    private global::Blackbaud.AppFx.UIModeling.Core.BooleanField _donotmail;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _donotmailreasoncode;
    private global::Blackbaud.AppFx.UIModeling.Core.BooleanField _isformer;
    private global::Blackbaud.AppFx.UIModeling.Core.DateField _dateadded;
    private global::Blackbaud.AppFx.UIModeling.Core.DateField _historicalstartdate;
    private global::Blackbaud.AppFx.UIModeling.Core.DateField _historicalenddate;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _infosourcecode;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _infosourcecomments;
    private global::Blackbaud.AppFx.UIModeling.Core.BooleanField _isconfidential;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _confidentialimage;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _confidentialdescription;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _primaryimage;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _historicalenddatedescription;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _donotmailimage;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _donotmaildescription;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _seasonalrangedescription;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _hyphen;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _contactimage;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _contactdescription;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _origincodetranslation;

	[System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public @UMHSAddressViewDataFormUIModel() : base()
	{


        _address = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _country = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _primary = new global::Blackbaud.AppFx.UIModeling.Core.BooleanField();
        _donotmail = new global::Blackbaud.AppFx.UIModeling.Core.BooleanField();
        _donotmailreasoncode = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _isformer = new global::Blackbaud.AppFx.UIModeling.Core.BooleanField();
        _dateadded = new global::Blackbaud.AppFx.UIModeling.Core.DateField();
        _historicalstartdate = new global::Blackbaud.AppFx.UIModeling.Core.DateField();
        _historicalenddate = new global::Blackbaud.AppFx.UIModeling.Core.DateField();
        _infosourcecode = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _infosourcecomments = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _isconfidential = new global::Blackbaud.AppFx.UIModeling.Core.BooleanField();
        _confidentialimage = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _confidentialdescription = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _primaryimage = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _historicalenddatedescription = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _donotmailimage = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _donotmaildescription = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _seasonalrangedescription = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _hyphen = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _contactimage = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _contactdescription = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _origincodetranslation = new global::Blackbaud.AppFx.UIModeling.Core.StringField();

        this.Mode = global::Blackbaud.AppFx.UIModeling.Core.DataFormMode.View;
        this.DataFormTemplateId = new System.Guid("f1f35dc0-946f-4170-ad74-9fc7b9fedc83");
        this.DataFormInstanceId = new System.Guid("75f282f7-9e30-41fb-84ca-321bc8c9eb98");
        this.RecordType = "MIMED Data";
        this.UserInterfaceUrl = "browser/htmlforms/custom/um.customfx.gratefulpatient/UMHSAddressViewDataForm.html";

        //
        //_address
        //
        _address.Name = "ADDRESS";
        _address.Caption = "Address";
        _address.DBReadOnly = true;
        _address.MaxLength = 300;
        this.Fields.Add(_address);
        //
        //_country
        //
        _country.Name = "COUNTRY";
        _country.Caption = "Country";
        _country.DBReadOnly = true;
        _country.MaxLength = 100;
        this.Fields.Add(_country);
        //
        //_primary
        //
        _primary.Name = "PRIMARY";
        _primary.Caption = "Primary";
        _primary.DBReadOnly = true;
        this.Fields.Add(_primary);
        //
        //_donotmail
        //
        _donotmail.Name = "DONOTMAIL";
        _donotmail.Caption = "Do not mail";
        _donotmail.DBReadOnly = true;
        this.Fields.Add(_donotmail);
        //
        //_donotmailreasoncode
        //
        _donotmailreasoncode.Name = "DONOTMAILREASONCODE";
        _donotmailreasoncode.Caption = "Reason";
        _donotmailreasoncode.DBReadOnly = true;
        _donotmailreasoncode.MaxLength = 100;
        this.Fields.Add(_donotmailreasoncode);
        //
        //_isformer
        //
        _isformer.Name = "ISFORMER";
        _isformer.Caption = "Is former";
        _isformer.DBReadOnly = true;
        this.Fields.Add(_isformer);
        //
        //_dateadded
        //
        _dateadded.Name = "DATEADDED";
        _dateadded.Caption = "Date added";
        _dateadded.DBReadOnly = true;
        this.Fields.Add(_dateadded);
        //
        //_historicalstartdate
        //
        _historicalstartdate.Name = "HISTORICALSTARTDATE";
        _historicalstartdate.Caption = "Historical start date";
        _historicalstartdate.DBReadOnly = true;
        this.Fields.Add(_historicalstartdate);
        //
        //_historicalenddate
        //
        _historicalenddate.Name = "HISTORICALENDDATE";
        _historicalenddate.Caption = "Historical end date";
        _historicalenddate.DBReadOnly = true;
        this.Fields.Add(_historicalenddate);
        //
        //_infosourcecode
        //
        _infosourcecode.Name = "INFOSOURCECODE";
        _infosourcecode.Caption = "Information source";
        _infosourcecode.DBReadOnly = true;
        _infosourcecode.MaxLength = 100;
        this.Fields.Add(_infosourcecode);
        //
        //_infosourcecomments
        //
        _infosourcecomments.Name = "INFOSOURCECOMMENTS";
        _infosourcecomments.Caption = "Comments";
        _infosourcecomments.DBReadOnly = true;
        _infosourcecomments.MaxLength = 256;
        this.Fields.Add(_infosourcecomments);
        //
        //_isconfidential
        //
        _isconfidential.Name = "ISCONFIDENTIAL";
        _isconfidential.Caption = "Confidential";
        _isconfidential.DBReadOnly = true;
        this.Fields.Add(_isconfidential);
        //
        //_confidentialimage
        //
        _confidentialimage.Name = "CONFIDENTIALIMAGE";
        _confidentialimage.Caption = "CONFIDENTIALIMAGE";
        _confidentialimage.DBReadOnly = true;
        this.Fields.Add(_confidentialimage);
        //
        //_confidentialdescription
        //
        _confidentialdescription.Name = "CONFIDENTIALDESCRIPTION";
        _confidentialdescription.Caption = "CONFIDENTIALDESCRIPTION";
        _confidentialdescription.DBReadOnly = true;
        this.Fields.Add(_confidentialdescription);
        //
        //_primaryimage
        //
        _primaryimage.Name = "PRIMARYIMAGE";
        _primaryimage.Caption = "PRIMARYIMAGE";
        _primaryimage.DBReadOnly = true;
        this.Fields.Add(_primaryimage);
        //
        //_historicalenddatedescription
        //
        _historicalenddatedescription.Name = "HISTORICALENDDATEDESCRIPTION";
        _historicalenddatedescription.Caption = "HISTORICALENDDATEDESCRIPTION";
        _historicalenddatedescription.DBReadOnly = true;
        this.Fields.Add(_historicalenddatedescription);
        //
        //_donotmailimage
        //
        _donotmailimage.Name = "DONOTMAILIMAGE";
        _donotmailimage.Caption = "DONOTMAILIMAGE";
        _donotmailimage.DBReadOnly = true;
        this.Fields.Add(_donotmailimage);
        //
        //_donotmaildescription
        //
        _donotmaildescription.Name = "DONOTMAILDESCRIPTION";
        _donotmaildescription.Caption = "DONOTMAILDESCRIPTION";
        _donotmaildescription.DBReadOnly = true;
        this.Fields.Add(_donotmaildescription);
        //
        //_seasonalrangedescription
        //
        _seasonalrangedescription.Name = "SEASONALRANGEDESCRIPTION";
        _seasonalrangedescription.Caption = "SEASONALRANGEDESCRIPTION";
        _seasonalrangedescription.DBReadOnly = true;
        this.Fields.Add(_seasonalrangedescription);
        //
        //_hyphen
        //
        _hyphen.Name = "HYPHEN";
        _hyphen.Caption = "HYPHEN";
        _hyphen.DBReadOnly = true;
        this.Fields.Add(_hyphen);
        //
        //_contactimage
        //
        _contactimage.Name = "CONTACTIMAGE";
        _contactimage.Caption = "CONTACTIMAGE";
        _contactimage.DBReadOnly = true;
        this.Fields.Add(_contactimage);
        //
        //_contactdescription
        //
        _contactdescription.Name = "CONTACTDESCRIPTION";
        _contactdescription.Caption = "CONTACTDESCRIPTION";
        _contactdescription.DBReadOnly = true;
        this.Fields.Add(_contactdescription);
        //
        //_origincodetranslation
        //
        _origincodetranslation.Name = "ORIGINCODETRANSLATION";
        _origincodetranslation.Caption = "Information source";
        _origincodetranslation.DBReadOnly = true;
        this.Fields.Add(_origincodetranslation);

		OnCreated();

	}

    /// <summary>
    /// Address
    /// </summary>
    [System.ComponentModel.Description("Address")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @ADDRESS {
		get { return _address; }
	}

    /// <summary>
    /// Country
    /// </summary>
    [System.ComponentModel.Description("Country")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @COUNTRY {
		get { return _country; }
	}

    /// <summary>
    /// Primary
    /// </summary>
    [System.ComponentModel.Description("Primary")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.BooleanField @PRIMARY {
		get { return _primary; }
	}

    /// <summary>
    /// Do not mail
    /// </summary>
    [System.ComponentModel.Description("Do not mail")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.BooleanField @DONOTMAIL {
		get { return _donotmail; }
	}

    /// <summary>
    /// Reason
    /// </summary>
    [System.ComponentModel.Description("Reason")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @DONOTMAILREASONCODE {
		get { return _donotmailreasoncode; }
	}

    /// <summary>
    /// Is former
    /// </summary>
    [System.ComponentModel.Description("Is former")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.BooleanField @ISFORMER {
		get { return _isformer; }
	}

    /// <summary>
    /// Date added
    /// </summary>
    [System.ComponentModel.Description("Date added")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.DateField @DATEADDED {
		get { return _dateadded; }
	}

    /// <summary>
    /// Historical start date
    /// </summary>
    [System.ComponentModel.Description("Historical start date")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.DateField @HISTORICALSTARTDATE {
		get { return _historicalstartdate; }
	}

    /// <summary>
    /// Historical end date
    /// </summary>
    [System.ComponentModel.Description("Historical end date")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.DateField @HISTORICALENDDATE {
		get { return _historicalenddate; }
	}

    /// <summary>
    /// Information source
    /// </summary>
    [System.ComponentModel.Description("Information source")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @INFOSOURCECODE {
		get { return _infosourcecode; }
	}

    /// <summary>
    /// Comments
    /// </summary>
    [System.ComponentModel.Description("Comments")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @INFOSOURCECOMMENTS {
		get { return _infosourcecomments; }
	}

    /// <summary>
    /// Confidential
    /// </summary>
    [System.ComponentModel.Description("Confidential")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.BooleanField @ISCONFIDENTIAL {
		get { return _isconfidential; }
	}

    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @CONFIDENTIALIMAGE {
		get { return _confidentialimage; }
	}

    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @CONFIDENTIALDESCRIPTION {
		get { return _confidentialdescription; }
	}

    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @PRIMARYIMAGE {
		get { return _primaryimage; }
	}

    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @HISTORICALENDDATEDESCRIPTION {
		get { return _historicalenddatedescription; }
	}

    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @DONOTMAILIMAGE {
		get { return _donotmailimage; }
	}

    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @DONOTMAILDESCRIPTION {
		get { return _donotmaildescription; }
	}

    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @SEASONALRANGEDESCRIPTION {
		get { return _seasonalrangedescription; }
	}

    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @HYPHEN {
		get { return _hyphen; }
	}

    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @CONTACTIMAGE {
		get { return _contactimage; }
	}

    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @CONTACTDESCRIPTION {
		get { return _contactdescription; }
	}

    /// <summary>
    /// Information source
    /// </summary>
    [System.ComponentModel.Description("Information source")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @ORIGINCODETRANSLATION {
		get { return _origincodetranslation; }
	}

}


}
