//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by BBUIModelLibrary
//     Version:  4.0.159.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace UM.CustomFx.GratefulPatient.UIModel
{

/// <summary>
/// Represents the UI model for the 'UMHS Affiliation Edit Form' data form
/// </summary>
[global::Blackbaud.AppFx.UIModeling.Core.DataFormUIModelMetadata(global::Blackbaud.AppFx.UIModeling.Core.DataFormMode.Edit, "0b6d8f1c-3b01-4077-ae98-7c851fb2a07a", "4da32618-3d0d-4035-81f2-5323083a3f79", "MIMED Affiliation")]
public partial class UMHSAffiliationDataFormUIModel : global::Blackbaud.AppFx.UIModeling.Core.DataFormUIModel
{

#region "Extensibility methods"

	partial void OnCreated();

#endregion

    private global::Blackbaud.AppFx.UIModeling.Core.CodeTableField _affiliationcategorycodeid;
    private global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid> _affiliationbasenamecodeid;
    private global::Blackbaud.AppFx.UIModeling.Core.DateField _startdate;
    private global::Blackbaud.AppFx.UIModeling.Core.DateField _enddate;
    private global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid> _siteid;
    private global::Blackbaud.AppFx.UIModeling.Core.ShowSearchFormUIAction _siteidsearchaction;
    private global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid> _departmentid;
    private global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid> _subdepartmentid;
   // private global::Blackbaud.AppFx.UIModeling.Core.BooleanField _optout;
   // private global::Blackbaud.AppFx.UIModeling.Core.CodeTableField _infosourcecodeid;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _comments;

	[System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public UMHSAffiliationDataFormUIModel() : base()
	{


        _affiliationcategorycodeid = new global::Blackbaud.AppFx.UIModeling.Core.CodeTableField();
        _affiliationbasenamecodeid = new global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid>();
        _startdate = new global::Blackbaud.AppFx.UIModeling.Core.DateField();
        _enddate = new global::Blackbaud.AppFx.UIModeling.Core.DateField();
        _siteid = new global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid>();
        _siteidsearchaction = new global::Blackbaud.AppFx.UIModeling.Core.ShowSearchFormUIAction();
        _departmentid = new global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid>();
        _subdepartmentid = new global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid>();
        //_optout = new global::Blackbaud.AppFx.UIModeling.Core.BooleanField();
        //_infosourcecodeid = new global::Blackbaud.AppFx.UIModeling.Core.CodeTableField();
        _comments = new global::Blackbaud.AppFx.UIModeling.Core.StringField();

        this.Mode = global::Blackbaud.AppFx.UIModeling.Core.DataFormMode.Edit;
        this.DataFormTemplateId = new System.Guid("0b6d8f1c-3b01-4077-ae98-7c851fb2a07a");
        this.DataFormInstanceId = new System.Guid("4da32618-3d0d-4035-81f2-5323083a3f79");
        this.RecordType = "MIMED Data";
        this.FixedDialog = true;
        this.UserInterfaceUrl = "browser/htmlforms/custom/um.customfx.gratefulpatient/UMHSAffiliationEditForm.html";

        //
        //_affiliationcategorycodeid
        //
        _affiliationcategorycodeid.Name = "AFFILIATIONCATEGORYCODEID";
        _affiliationcategorycodeid.Caption = "Category";
        _affiliationcategorycodeid.Required = true;
        _affiliationcategorycodeid.CodeTableName = "USR_UMHS_AFFILIATIONCATEGORYTYPECODE";
        this.Fields.Add(_affiliationcategorycodeid);
        //
        //_affiliationbasenamecodeid
        //
        _affiliationbasenamecodeid.Name = "AFFILIATIONBASENAMECODEID";
        _affiliationbasenamecodeid.Caption = "Name";
        _affiliationbasenamecodeid.Required = true;
        _affiliationbasenamecodeid.SimpleDataListId = new System.Guid("4c646cee-0f5b-4197-b4d3-0869693cfc2d");
        _affiliationbasenamecodeid.Parameters.Add(new global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListParameter("AFFILIATIONCATEGORYCODEID", "Fields!AFFILIATIONCATEGORYCODEID"));
        this.Fields.Add(_affiliationbasenamecodeid);
        //
        //_startdate
        //
        _startdate.Name = "STARTDATE";
        _startdate.Caption = "Start date";
        _startdate.Required = true;
        this.Fields.Add(_startdate);
        //
        //_enddate
        //
        _enddate.Name = "ENDDATE";
        _enddate.Caption = "End date";
        this.Fields.Add(_enddate);
        //
        //_siteid
        //
        _siteid.Name = "SITEID";
        _siteid.Caption = "Site";
        _siteid.Visible = true;
        _siteid.SimpleDataListId = new System.Guid("c8e8d3ba-2725-421f-a796-e2fcc1202780");
        _siteid.LinkedActions.Add(_siteidsearchaction);
        _siteid.Required = true;
        this.Fields.Add(_siteid);
        //
        //_siteidsearchaction
        //
        _siteidsearchaction.Name = "SITEIDSEARCHACTION";
        _siteidsearchaction.Caption = "Search";
        _siteidsearchaction.SearchListId = new System.Guid("27a63ede-a0d4-4074-a85a-196df4adc0dd");
        this.Actions.Add(_siteidsearchaction);
        //
        //_departmentid
        //
        _departmentid.Name = "DEPARTMENTID";
        _departmentid.Caption = "MIMED department";
        _departmentid.SimpleDataListId = new System.Guid("0cbdb7f1-f629-4e7b-a7e1-c3e4ebd7d325");
        _departmentid.Required = true;
        this.Fields.Add(_departmentid);
        //
        //_subdepartmentid
        //
        _subdepartmentid.Name = "SUBDEPARTMENTID";
        _subdepartmentid.Caption = "MIMED subdepartment";
        _subdepartmentid.SimpleDataListId = new System.Guid("879b4e21-6a71-4c60-9b41-771fa39ef9cf");
        _subdepartmentid.Parameters.Add(new global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListParameter("DEPARTMENTID", "Fields!DEPARTMENTID"));
        this.Fields.Add(_subdepartmentid);        
     
        //
        ////_optout
        ////
        //_optout.Name = "OPTOUT";
        //_optout.Caption = "Opt out";
        //this.Fields.Add(_optout);
        ////
        ////_infosourcecodeid
        ////
        //_infosourcecodeid.Name = "INFOSOURCECODEID";
        //_infosourcecodeid.Caption = "Information source";
        //_infosourcecodeid.CodeTableName = "INFOSOURCECODE";
        //this.Fields.Add(_infosourcecodeid);
        //
        //_comments
        //
        _comments.Name = "COMMENTS";
        _comments.Caption = "Comments";
        this.Fields.Add(_comments);

		OnCreated();

	}

    /// <summary>
    /// Category
    /// </summary>
    [System.ComponentModel.Description("Category")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.CodeTableField @AFFILIATIONCATEGORYCODEID {
		get { return _affiliationcategorycodeid; }
	}

    /// <summary>
    /// Name
    /// </summary>
    [System.ComponentModel.Description("Name")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid> @AFFILIATIONBASENAMECODEID {
		get { return _affiliationbasenamecodeid; }
	}

    /// <summary>
    /// Start date
    /// </summary>
    [System.ComponentModel.Description("Start date")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.DateField @STARTDATE {
		get { return _startdate; }
	}

    /// <summary>
    /// End date
    /// </summary>
    [System.ComponentModel.Description("End date")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.DateField @ENDDATE {
		get { return _enddate; }
	}

    /// <summary>
    /// Site
    /// </summary>
    [System.ComponentModel.Description("Site")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
    public global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid> @SITEID
    {
        get { return _siteid; }
    }

        /// <summary>
        /// UMHS Department
        /// </summary>
        [System.ComponentModel.Description("MIMED department")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid> @DEPARTMENTID {
		get { return _departmentid; }
	}

    /// <summary>
    /// UMHS Sub-Department
    /// </summary>
    [System.ComponentModel.Description("MIMED subdepartment")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid> @SUBDEPARTMENTID {
		get { return _subdepartmentid; }
	}


 //   /// <summary>
 //   /// Opt out
 //   /// </summary>
 //   [System.ComponentModel.Description("Opt out")]
 //   [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	//public global::Blackbaud.AppFx.UIModeling.Core.BooleanField @OPTOUT {
	//	get { return _optout; }
	//}

 //   /// <summary>
 //   /// Information source
 //   /// </summary>
 //   [System.ComponentModel.Description("Information source")]
 //   [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	//public global::Blackbaud.AppFx.UIModeling.Core.CodeTableField @INFOSOURCECODEID {
	//	get { return _infosourcecodeid; }
	//}

    /// <summary>
    /// Comments
    /// </summary>
    [System.ComponentModel.Description("Comments")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @COMMENTS {
		get { return _comments; }
	}

}


}
