//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by BBUIModelLibrary
//     Version:  4.0.165.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace UM.CustomFx.GratefulPatient.UIModel
{

/// <summary>
/// Represents the UI model for the 'UMHS Phone Add Form' data form
/// </summary>
[global::Blackbaud.AppFx.UIModeling.Core.DataFormUIModelMetadata(global::Blackbaud.AppFx.UIModeling.Core.DataFormMode.Add, "f76a4009-eabb-4ad8-9603-10c572cf0fe5", "10f54640-0b72-4569-99a4-334c9a12fd3b", "MIMED Phone", "MIMED Data")]
public partial class @UMHSPhoneFormUIModel : global::Blackbaud.AppFx.UIModeling.Core.DataFormUIModel
{

#region "Extensibility methods"

	partial void OnCreated();

#endregion

    private global::Blackbaud.AppFx.UIModeling.Core.CodeTableField _phonetypecodeid;
    private global::Blackbaud.AppFx.UIModeling.Core.PhoneField _number;
    private global::Blackbaud.AppFx.UIModeling.Core.BooleanField _isprimary;
    private global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid> _countryid;
    private global::Blackbaud.AppFx.UIModeling.Core.DateField _startdate;
    private global::Blackbaud.AppFx.UIModeling.Core.DateField _enddate;
    private global::Blackbaud.AppFx.UIModeling.Core.BooleanField _donotcall;
    private global::Blackbaud.AppFx.UIModeling.Core.CodeTableField _donotcallreasoncodeid;
    private global::Blackbaud.AppFx.UIModeling.Core.CodeTableField _infosourcecodeid;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _infosourcecomments;
    private global::Blackbaud.AppFx.UIModeling.Core.TimeField _callbefore;
    private global::Blackbaud.AppFx.UIModeling.Core.TimeField _callafter;
    private global::Blackbaud.AppFx.UIModeling.Core.BooleanField _isconfidential;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _countrycode;
    private global::Blackbaud.AppFx.UIModeling.Core.BooleanField _showinvalid;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _invalidfield3;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _invalidfield4;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _origincodetranslation;
    private global::Blackbaud.AppFx.UIModeling.Core.GroupField _phoneinformation;
    private global::Blackbaud.AppFx.UIModeling.Core.GroupField _sourceinformation;
    //private global::Blackbaud.AppFx.UIModeling.Core.CollectionField<UMHSPhoneFormUIModel> _countrycodes;


    //this._countryCodesDictionary = new Dictionary<Guid, string>();

    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public @UMHSPhoneFormUIModel() : base()
	{


        _phonetypecodeid = new global::Blackbaud.AppFx.UIModeling.Core.CodeTableField();
        _number = new global::Blackbaud.AppFx.UIModeling.Core.PhoneField();
        _isprimary = new global::Blackbaud.AppFx.UIModeling.Core.BooleanField();
        _countryid = new global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid>();
        _startdate = new global::Blackbaud.AppFx.UIModeling.Core.DateField();
        _enddate = new global::Blackbaud.AppFx.UIModeling.Core.DateField();
        _donotcall = new global::Blackbaud.AppFx.UIModeling.Core.BooleanField();
        _donotcallreasoncodeid = new global::Blackbaud.AppFx.UIModeling.Core.CodeTableField();
        _infosourcecodeid = new global::Blackbaud.AppFx.UIModeling.Core.CodeTableField();
        _infosourcecomments = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _callbefore = new global::Blackbaud.AppFx.UIModeling.Core.TimeField();
        _callafter = new global::Blackbaud.AppFx.UIModeling.Core.TimeField();
        _isconfidential = new global::Blackbaud.AppFx.UIModeling.Core.BooleanField();
        _countrycode = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _showinvalid = new global::Blackbaud.AppFx.UIModeling.Core.BooleanField();
        _invalidfield3 = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _invalidfield4 = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _origincodetranslation = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _phoneinformation = new global::Blackbaud.AppFx.UIModeling.Core.GroupField();
        _sourceinformation = new global::Blackbaud.AppFx.UIModeling.Core.GroupField();
       // _countrycodes = new global::Blackbaud.AppFx.UIModeling.Core.StringField();

            // _countryCodesDictionary = new global::Blackbaud.AppFx.UIModeling.Core.StringField();

        this.Mode = global::Blackbaud.AppFx.UIModeling.Core.DataFormMode.Add;
        this.DataFormTemplateId = new System.Guid("f76a4009-eabb-4ad8-9603-10c572cf0fe5");
        this.DataFormInstanceId = new System.Guid("10f54640-0b72-4569-99a4-334c9a12fd3b");
        this.RecordType = "UMHS Phone";
        this.ContextRecordType = "MIMED Data";
        this.FixedDialog = true;
        this.FORMHEADER.Value = "Add MIMED Phone";
        this.UserInterfaceUrl = "browser/htmlforms/custom/um.customfx.gratefulpatient/UMHSPhoneForm.html";

        //
        //_phonetypecodeid
        //
        _phonetypecodeid.Name = "PHONETYPECODEID";
        _phonetypecodeid.Caption = "Phone type";
        _phonetypecodeid.CodeTableName = "PHONETYPECODE";
        this.Fields.Add(_phonetypecodeid);
        //
        //_number
        //
        _number.Name = "NUMBER";
        _number.Caption = "Number";
        _number.Required = true;
        _number.MaxLength = 100;
        this.Fields.Add(_number);
        //
        //_isprimary
        //
        _isprimary.Name = "ISPRIMARY";
        _isprimary.Caption = "Set as primary phone number";
        this.Fields.Add(_isprimary);
        //
        //_countryid
        //
        _countryid.Name = "COUNTRYID";
        _countryid.Caption = "Country";
        _countryid.Required = true;
        _countryid.SimpleDataListId = new System.Guid("c9649672-353d-42e8-8c25-4d34bbabfbba");
        _countryid.Value = new System.Guid("27CF0F7D-CDAF-448F-80DE-E9196BF28D36");
        this.Fields.Add(_countryid);
        //
        //_startdate
        //
        _startdate.Name = "STARTDATE";
        _startdate.Caption = "Start date";
        this.Fields.Add(_startdate);
        //
        //_enddate
        //
        _enddate.Name = "ENDDATE";
        _enddate.Caption = "End date";
        this.Fields.Add(_enddate);
        //
        //_donotcall
        //
        _donotcall.Name = "DONOTCALL";
        _donotcall.Caption = "Do not call this phone number";
        this.Fields.Add(_donotcall);
        //
        //_donotcallreasoncodeid
        //
        _donotcallreasoncodeid.Name = "DONOTCALLREASONCODEID";
        _donotcallreasoncodeid.Caption = "Reason";
        _donotcallreasoncodeid.CodeTableName = "DONOTCALLREASONCODE";
        this.Fields.Add(_donotcallreasoncodeid);
        //
        //_infosourcecodeid
        //
        _infosourcecodeid.Name = "INFOSOURCECODEID";
        _infosourcecodeid.Caption = "Information source";
        _infosourcecodeid.CodeTableName = "INFOSOURCECODE";
        this.Fields.Add(_infosourcecodeid);
        //
        //_infosourcecomments
        //
        _infosourcecomments.Name = "INFOSOURCECOMMENTS";
        _infosourcecomments.Caption = "Comments";
        _infosourcecomments.MaxLength = 256;
        _infosourcecomments.Multiline = true;
        this.Fields.Add(_infosourcecomments);
        //
        //_callbefore
        //
        _callbefore.Name = "CALLBEFORE";
        _callbefore.Caption = "Call before";
        this.Fields.Add(_callbefore);
        //
        //_callafter
        //
        _callafter.Name = "CALLAFTER";
        _callafter.Caption = "Call after";
        this.Fields.Add(_callafter);
        //
        //_isconfidential
        //
        _isconfidential.Name = "ISCONFIDENTIAL";
        _isconfidential.Caption = "This phone number is confidential";
        this.Fields.Add(_isconfidential);
        //
        //_countrycode
        //
        _countrycode.Name = "COUNTRYCODE";
        _countrycode.Caption = "COUNTRYCODE";
        _countrycode.DBReadOnly = true;
        this.Fields.Add(_countrycode);
        //
        //_showinvalid
        //
        _showinvalid.Name = "SHOWINVALID";
        _showinvalid.Caption = "SHOWINVALID";
        _showinvalid.Visible = false;
        _showinvalid.DBReadOnly = true;
        this.Fields.Add(_showinvalid);
        //
        //_invalidfield3
        //
        _invalidfield3.Name = "INVALIDFIELD3";
        _invalidfield3.Caption = "INVALIDFIELD3";
        _invalidfield3.Visible = false;
        _invalidfield3.DBReadOnly = true;
        this.Fields.Add(_invalidfield3);
        //
        //_invalidfield4
        //
        _invalidfield4.Name = "INVALIDFIELD4";
        _invalidfield4.Caption = "INVALIDFIELD4";
        _invalidfield4.Visible = false;
        _invalidfield4.DBReadOnly = true;
        this.Fields.Add(_invalidfield4);
        //
        //_origincodetranslation
        //
        _origincodetranslation.Name = "ORIGINCODETRANSLATION";
        _origincodetranslation.Caption = "Information source";
        _origincodetranslation.DBReadOnly = true;
        this.Fields.Add(_origincodetranslation);
        //
        //_phoneinformation
        //
        _phoneinformation.Name = "PHONEINFORMATION";
        _phoneinformation.Caption = "Phone information";
        _phoneinformation.Fields.Add("PHONETYPECODEID");
        _phoneinformation.Fields.Add("NUMBER");
        _phoneinformation.Fields.Add("ISPRIMARY");
        _phoneinformation.Fields.Add("DONOTCALL");
        _phoneinformation.Fields.Add("ISCONFIDENTIAL");
        this.Fields.Add(_phoneinformation);
        //
        //_sourceinformation
        //
        _sourceinformation.Name = "SOURCEINFORMATION";
        _sourceinformation.Caption = "Phone source";
        _sourceinformation.Fields.Add("INFOSOURCECODEID");
        _sourceinformation.Fields.Add("INFOSOURCECOMMENTS");
        this.Fields.Add(_sourceinformation);

            ////
            ////_countrycodes
            ////
            //this._countrycodes.Name = "COUNTRYCODES";
            //this._countrycodes.Caption = "COUNTRYCODES";
            //this._countrycodes.Visible = false;
            //this._countrycodes.DBReadOnly = true;
            //this.Fields.Add(_countrycodes);


            OnCreated();

	}

    /// <summary>
    /// Phone type
    /// </summary>
    [System.ComponentModel.Description("Phone type")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.CodeTableField @PHONETYPECODEID {
		get { return _phonetypecodeid; }
	}
        ///// <summary>
        ///// Country codes
        ///// </summary>
        //[System.ComponentModel.Description("Country codes")]
        //[System.CodeDom.Compiler.GeneratedCode("BBUIModelLibrary", "1.0.0.0")]
        //public global::Blackbaud.AppFx.UIModeling.Core.CollectionField<UMHSPhoneFormUIModel> COUNTRYCODES
        //{
        //    get
        //    {
        //        return this._countrycodes;
        //    }
        //}





        /// <summary>
        /// Set as primary phone number
        /// </summary>
        [System.ComponentModel.Description("Set as primary phone number")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.BooleanField @ISPRIMARY {
		get { return _isprimary; }
	}

    /// <summary>
    /// Country
    /// </summary>
    [System.ComponentModel.Description("Country")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid> @COUNTRYID {
		get { return _countryid; }
	}

    /// <summary>
    /// Start date
    /// </summary>
    [System.ComponentModel.Description("Start date")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.DateField @STARTDATE {
		get { return _startdate; }
	}

    /// <summary>
    /// End date
    /// </summary>
    [System.ComponentModel.Description("End date")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.DateField @ENDDATE {
		get { return _enddate; }
	}

    /// <summary>
    /// Do not call this phone number
    /// </summary>
    [System.ComponentModel.Description("Do not call this phone number")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.BooleanField @DONOTCALL {
		get { return _donotcall; }
	}

    /// <summary>
    /// Reason
    /// </summary>
    [System.ComponentModel.Description("Reason")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.CodeTableField @DONOTCALLREASONCODEID {
		get { return _donotcallreasoncodeid; }
	}

    /// <summary>
    /// Information source
    /// </summary>
    [System.ComponentModel.Description("Information source")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.CodeTableField @INFOSOURCECODEID {
		get { return _infosourcecodeid; }
	}

    /// <summary>
    /// Comments
    /// </summary>
    [System.ComponentModel.Description("Comments")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @INFOSOURCECOMMENTS {
		get { return _infosourcecomments; }
	}

    /// <summary>
    /// Call before
    /// </summary>
    [System.ComponentModel.Description("Call before")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.TimeField @CALLBEFORE {
		get { return _callbefore; }
	}

    /// <summary>
    /// Call after
    /// </summary>
    [System.ComponentModel.Description("Call after")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.TimeField @CALLAFTER {
		get { return _callafter; }
	}

    /// <summary>
    /// This phone number is confidential
    /// </summary>
    [System.ComponentModel.Description("This phone number is confidential")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.BooleanField @ISCONFIDENTIAL {
		get { return _isconfidential; }
	}

    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @COUNTRYCODE {
		get { return _countrycode; }
	}

    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.BooleanField @SHOWINVALID {
		get { return _showinvalid; }
	}

    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @INVALIDFIELD3 {
		get { return _invalidfield3; }
	}

    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @INVALIDFIELD4 {
		get { return _invalidfield4; }
	}

    /// <summary>
    /// Information source
    /// </summary>
    [System.ComponentModel.Description("Information source")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @ORIGINCODETRANSLATION {
		get { return _origincodetranslation; }
	}

    /// <summary>
    /// Phone information
    /// </summary>
    [System.ComponentModel.Description("Phone information")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.GroupField @PHONEINFORMATION {
		get { return _phoneinformation; }
	}

    /// <summary>
    /// Phone source
    /// </summary>
    [System.ComponentModel.Description("Phone source")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.GroupField @SOURCEINFORMATION {
		get { return _sourceinformation; }
	}

}


}
