//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by BBUIModelLibrary
//     Version:  4.0.159.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace UM.CustomFx.GratefulPatient.UIModel
{

/// <summary>
/// Represents the UI model for the 'UMHS Email Address View Data Form' data form
/// </summary>
[global::Blackbaud.AppFx.UIModeling.Core.DataFormUIModelMetadata(global::Blackbaud.AppFx.UIModeling.Core.DataFormMode.View, "9696e562-cc4c-46c1-8bea-bd44ee7c329e", "67f2d064-dd1c-4512-b2d5-1df37026ab9e", "MIMED Email Address")]
public partial class @UMHSEmailAddressViewDataFormUIModel : global::Blackbaud.AppFx.UIModeling.Core.DataFormUIModel
{

#region "Extensibility methods"

	partial void OnCreated();

#endregion

    private global::Blackbaud.AppFx.UIModeling.Core.StringField _emailaddresstypecode;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _emailaddress;
    private global::Blackbaud.AppFx.UIModeling.Core.BooleanField _primary;
    private global::Blackbaud.AppFx.UIModeling.Core.BooleanField _donotemail;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _infosourcecode;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _infosourcecomments;
    private global::Blackbaud.AppFx.UIModeling.Core.DateField _startdate;
    private global::Blackbaud.AppFx.UIModeling.Core.DateField _enddate;
    private global::Blackbaud.AppFx.UIModeling.Core.BooleanField _isconfidential;
    private global::Blackbaud.AppFx.UIModeling.Core.DateField _dateadded;
    //private global::Blackbaud.AppFx.UIModeling.Core.ValueListField _origincode;    
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _invalidaccount;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _primaryimage;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _donotemailimage;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _donotemaildescription;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _contactimage;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _contactdescription;
    private global::Blackbaud.AppFx.UIModeling.Core.BooleanField _showinvalid;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _origincodetranslation;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _enddatedescription;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _hyphen;

	[System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public @UMHSEmailAddressViewDataFormUIModel() : base()
	{


        _emailaddresstypecode = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _emailaddress = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _primary = new global::Blackbaud.AppFx.UIModeling.Core.BooleanField();
        _donotemail = new global::Blackbaud.AppFx.UIModeling.Core.BooleanField();
        _infosourcecode = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _infosourcecomments = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _startdate = new global::Blackbaud.AppFx.UIModeling.Core.DateField();
        _enddate = new global::Blackbaud.AppFx.UIModeling.Core.DateField();
        _isconfidential = new global::Blackbaud.AppFx.UIModeling.Core.BooleanField();
        _dateadded = new global::Blackbaud.AppFx.UIModeling.Core.DateField();
        //_origincode = new Blackbaud.AppFx.UIModeling.Core.ValueListField<UMHSEmailAddressViewDataFormUIModel.ORIGINCODE?>();
        _invalidaccount = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _primaryimage = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _donotemailimage = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _donotemaildescription = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _contactimage = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _contactdescription = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _showinvalid = new global::Blackbaud.AppFx.UIModeling.Core.BooleanField();
        _origincodetranslation = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _enddatedescription = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _hyphen = new global::Blackbaud.AppFx.UIModeling.Core.StringField();

        this.Mode = global::Blackbaud.AppFx.UIModeling.Core.DataFormMode.View;
        this.DataFormTemplateId = new System.Guid("9696e562-cc4c-46c1-8bea-bd44ee7c329e");
        this.DataFormInstanceId = new System.Guid("67f2d064-dd1c-4512-b2d5-1df37026ab9e");
        this.RecordType = "MIMED Email Address";
        this.FixedDialog = true;

        //
        //_emailaddresstypecode
        //
        _emailaddresstypecode.Name = "EMAILADDRESSTYPECODE";
        _emailaddresstypecode.Caption = "Type";
        _emailaddresstypecode.DBReadOnly = true;
        _emailaddresstypecode.MaxLength = 100;
        this.Fields.Add(_emailaddresstypecode);
        //
        //_emailaddress
        //
        _emailaddress.Name = "EMAILADDRESS";
        _emailaddress.Caption = "Email address";
        _emailaddress.DBReadOnly = true;
        _emailaddress.MaxLength = 100;
        this.Fields.Add(_emailaddress);
        //
        //_primary
        //
        _primary.Name = "PRIMARY";
        _primary.Caption = "Set as primary email address";
        _primary.DBReadOnly = true;
        this.Fields.Add(_primary);
        //
        //_donotemail
        //
        _donotemail.Name = "DONOTEMAIL";
        _donotemail.Caption = "Do not email";
        _donotemail.DBReadOnly = true;
        this.Fields.Add(_donotemail);
        //
        //_infosourcecode
        //
        _infosourcecode.Name = "INFOSOURCECODE";
        _infosourcecode.Caption = "Information source";
        _infosourcecode.DBReadOnly = true;
        _infosourcecode.MaxLength = 100;
        this.Fields.Add(_infosourcecode);
        //
        //_infosourcecomments
        //
        _infosourcecomments.Name = "INFOSOURCECOMMENTS";
        _infosourcecomments.Caption = "Comments";
        _infosourcecomments.DBReadOnly = true;
        _infosourcecomments.MaxLength = 256;
        this.Fields.Add(_infosourcecomments);
        //
        //_startdate
        //
        _startdate.Name = "STARTDATE";
        _startdate.Caption = "Start date";
        _startdate.DBReadOnly = true;
        this.Fields.Add(_startdate);
        //
        //_enddate
        //
        _enddate.Name = "ENDDATE";
        _enddate.Caption = "End date";
        _enddate.DBReadOnly = true;
        this.Fields.Add(_enddate);
        //
        //_isconfidential
        //
        _isconfidential.Name = "ISCONFIDENTIAL";
        _isconfidential.Caption = "Is confidential";
        _isconfidential.DBReadOnly = true;
        this.Fields.Add(_isconfidential);
        //
        //_dateadded
        //
        _dateadded.Name = "DATEADDED";
        _dateadded.Caption = "Date added";
        _dateadded.DBReadOnly = true;
        this.Fields.Add(_dateadded);

        


        //
        //_invalidaccount
        //
        _invalidaccount.Name = "INVALIDACCOUNT";
        _invalidaccount.Caption = "INVALIDACCOUNT";
        _invalidaccount.DBReadOnly = true;
        this.Fields.Add(_invalidaccount);
        //
        //_primaryimage
        //
        _primaryimage.Name = "PRIMARYIMAGE";
        _primaryimage.Caption = "PRIMARYIMAGE";
        _primaryimage.DBReadOnly = true;
        this.Fields.Add(_primaryimage);
        //
        //_donotemailimage
        //
        _donotemailimage.Name = "DONOTEMAILIMAGE";
        _donotemailimage.Caption = "DONOTEMAILIMAGE";
        _donotemailimage.DBReadOnly = true;
        this.Fields.Add(_donotemailimage);
        //
        //_donotemaildescription
        //
        _donotemaildescription.Name = "DONOTEMAILDESCRIPTION";
        _donotemaildescription.Caption = "DONOTEMAILDESCRIPTION";
        _donotemaildescription.DBReadOnly = true;
        this.Fields.Add(_donotemaildescription);
        //
        //_contactimage
        //
        _contactimage.Name = "CONTACTIMAGE";
        _contactimage.Caption = "CONTACTIMAGE";
        _contactimage.DBReadOnly = true;
        this.Fields.Add(_contactimage);
        //
        //_contactdescription
        //
        _contactdescription.Name = "CONTACTDESCRIPTION";
        _contactdescription.Caption = "CONTACTDESCRIPTION";
        _contactdescription.DBReadOnly = true;
        this.Fields.Add(_contactdescription);
        //
        //_showinvalid
        //
        _showinvalid.Name = "SHOWINVALID";
        _showinvalid.Caption = "SHOWINVALID";
        _showinvalid.Visible = false;
        _showinvalid.DBReadOnly = true;
        this.Fields.Add(_showinvalid);
        //
        //_origincodetranslation
        //
        _origincodetranslation.Name = "ORIGINCODETRANSLATION";
        _origincodetranslation.Caption = "Information source";
        _origincodetranslation.DBReadOnly = true;
        this.Fields.Add(_origincodetranslation);
        //
        //_enddatedescription
        //
        _enddatedescription.Name = "ENDDATEDESCRIPTION";
        _enddatedescription.Caption = "ENDDATEDESCRIPTION";
        _enddatedescription.DBReadOnly = true;
        this.Fields.Add(_enddatedescription);
        //
        //_hyphen
        //
        _hyphen.Name = "HYPHEN";
        _hyphen.Caption = "HYPHEN";
        _hyphen.DBReadOnly = true;
        this.Fields.Add(_hyphen);

		OnCreated();

	}

    /// <summary>
    /// Type
    /// </summary>
    [System.ComponentModel.Description("Type")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @EMAILADDRESSTYPECODE {
		get { return _emailaddresstypecode; }
	}

    /// <summary>
    /// Email address
    /// </summary>
    [System.ComponentModel.Description("Email address")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @EMAILADDRESS {
		get { return _emailaddress; }
	}

    /// <summary>
    /// Primary
    /// </summary>
    [System.ComponentModel.Description("Primary")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.BooleanField @PRIMARY {
		get { return _primary; }
	}

    /// <summary>
    /// Do not email
    /// </summary>
    [System.ComponentModel.Description("Do not email")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.BooleanField @DONOTEMAIL {
		get { return _donotemail; }
	}

    /// <summary>
    /// Information source
    /// </summary>
    [System.ComponentModel.Description("Information source")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @INFOSOURCECODE {
		get { return _infosourcecode; }
	}

    /// <summary>
    /// Comments
    /// </summary>
    [System.ComponentModel.Description("Comments")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @INFOSOURCECOMMENTS {
		get { return _infosourcecomments; }
	}

    /// <summary>
    /// Start date
    /// </summary>
    [System.ComponentModel.Description("Start date")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.DateField @STARTDATE {
		get { return _startdate; }
	}

    /// <summary>
    /// End date
    /// </summary>
    [System.ComponentModel.Description("End date")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.DateField @ENDDATE {
		get { return _enddate; }
	}

    /// <summary>
    /// Is confidential
    /// </summary>
    [System.ComponentModel.Description("Is confidential")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.BooleanField @ISCONFIDENTIAL {
		get { return _isconfidential; }
	}

    /// <summary>
    /// Date added
    /// </summary>
    [System.ComponentModel.Description("Date added")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.DateField @DATEADDED {
		get { return _dateadded; }
	}


        ///// <summary>
        ///// Origin code
        ///// </summary>
        //[System.ComponentModel.Description("Origin code")]
        //[System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
        //public global::Blackbaud.AppFx.UIModeling.Core.ValueListField @ORIGINCODE
        //{
        //    get { return _origincode; }
        //}

        [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @INVALIDACCOUNT {
		get { return _invalidaccount; }
	}

    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @PRIMARYIMAGE {
		get { return _primaryimage; }
	}

    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @DONOTEMAILIMAGE {
		get { return _donotemailimage; }
	}

    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @DONOTEMAILDESCRIPTION {
		get { return _donotemaildescription; }
	}

    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @CONTACTIMAGE {
		get { return _contactimage; }
	}

    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @CONTACTDESCRIPTION {
		get { return _contactdescription; }
	}

    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.BooleanField @SHOWINVALID {
		get { return _showinvalid; }
	}

    /// <summary>
    /// Information source
    /// </summary>
    [System.ComponentModel.Description("Information source")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @ORIGINCODETRANSLATION {
		get { return _origincodetranslation; }
	}

    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @ENDDATEDESCRIPTION {
		get { return _enddatedescription; }
	}

    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @HYPHEN {
		get { return _hyphen; }
	}

}


}
