//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by BBUIModelLibrary
//     Version:  4.0.165.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace UM.CustomFx.GratefulPatient.UIModel
{

/// <summary>
/// Represents the UI model for the 'UMHSInteractionFormPARTICIPANTS' data form
/// </summary>
public partial class @UMHSInteractionFormPARTICIPANTSUIModel : global::Blackbaud.AppFx.UIModeling.Core.UIModel
{

#region "Extensibility methods"

	partial void OnCreated();

#endregion

    private global::Blackbaud.AppFx.UIModeling.Core.GuidField _id;
    private global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid> _constituentid;
    private global::Blackbaud.AppFx.UIModeling.Core.ShowSearchFormUIAction _constituentidsearchaction;

	[System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public @UMHSInteractionFormPARTICIPANTSUIModel() : base()
	{


        _id = new global::Blackbaud.AppFx.UIModeling.Core.GuidField();
        _constituentid = new global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid>();
        _constituentidsearchaction = new global::Blackbaud.AppFx.UIModeling.Core.ShowSearchFormUIAction();

        //
        //_id
        //
        _id.Name = "ID";
        _id.Caption = "ID";
        _id.Visible = false;
        this.Fields.Add(_id);
        //
        //_constituentid
        //
        _constituentid.Name = "CONSTITUENTID";
        _constituentid.Caption = "Participant";
        _constituentid.SimpleDataListId = new System.Guid("eec723dc-3ed3-425b-9ef2-8ba1ccc190d1");
        _constituentid.Parameters.Add(new global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListParameter("CONSTITUENTID", "PARENT.FIELDS!CONTEXTID"));
        _constituentid.LinkedActions.Add(_constituentidsearchaction);
        this.Fields.Add(_constituentid);
        //
        //_constituentidsearchaction
        //
        _constituentidsearchaction.Name = "CONSTITUENTIDSEARCHACTION";
        _constituentidsearchaction.Caption = "Search";
        _constituentidsearchaction.SearchListId = new System.Guid("747530a1-be80-4054-a021-d2a599248261");
        //_constituentidsearchaction.EnableQuickFind = true;
        //_constituentidsearchaction.SearchFieldOverrides.Add(new global::Blackbaud.AppFx.UIModeling.Core.FieldOverride() {FieldId = "INCLUDENONCONSTITUENTRECORDS", DefaultValueText = "true"});
        this.Actions.Add(_constituentidsearchaction);

		OnCreated();

	}

    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.GuidField @ID {
		get { return _id; }
	}

    /// <summary>
    /// Participant
    /// </summary>
    [System.ComponentModel.Description("Participant")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid> @CONSTITUENTID {
		get { return _constituentid; }
	}

    /// <summary>
    /// Search
    /// </summary>
    [System.ComponentModel.Description("Search")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.ShowSearchFormUIAction @CONSTITUENTIDSEARCHACTION {
		get { return _constituentidsearchaction; }
	}

}


}
