//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by BBUIModelLibrary
//     Version:  4.0.165.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace UM.CustomFx.GratefulPatient.UIModel
{

/// <summary>
/// Represents the UI model for the 'UMHS Interaction Add Form' data form
/// </summary>
[global::Blackbaud.AppFx.UIModeling.Core.DataFormUIModelMetadata(global::Blackbaud.AppFx.UIModeling.Core.DataFormMode.Add, "51f7a78b-7da7-48a6-860c-cde8848edc5a", "b3a04417-321f-44c4-a3b7-4b115e5eeafc", "MIMED Interaction", "MIMED Data")]
public partial class @UMHSInteractionFormUIModel : global::Blackbaud.AppFx.UIModeling.Core.DataFormUIModel
{

#region "Extensibility methods"

	partial void OnCreated();

#endregion

    private global::Blackbaud.AppFx.UIModeling.Core.StringField _summary;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _name;
    private global::Blackbaud.AppFx.UIModeling.Core.CodeTableField _statuscodeid;
    private global::Blackbaud.AppFx.UIModeling.Core.SearchListField<System.Guid> _fundraiserid;
    private global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid> _interactioncategoryid;
    private global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid> _interactionsubcategoryid;
    private global::Blackbaud.AppFx.UIModeling.Core.CodeTableField _contactmethodcodeid;
    private global::Blackbaud.AppFx.UIModeling.Core.SearchListField<System.Guid> _eventid;
    private global::Blackbaud.AppFx.UIModeling.Core.DateField _expecteddate;
    private global::Blackbaud.AppFx.UIModeling.Core.DateField _actualdate;
    private global::Blackbaud.AppFx.UIModeling.Core.CollectionField<UMHSInteractionFormSITESUIModel> _sites;
    private global::Blackbaud.AppFx.UIModeling.Core.BooleanField _siterequired;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _comments;
    private global::Blackbaud.AppFx.UIModeling.Core.CollectionField<UMHSInteractionFormPARTICIPANTSUIModel> _participants;

	[System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public @UMHSInteractionFormUIModel() : base()
	{


        _summary = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _name = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _statuscodeid = new global::Blackbaud.AppFx.UIModeling.Core.CodeTableField();
        _fundraiserid = new global::Blackbaud.AppFx.UIModeling.Core.SearchListField<System.Guid>();
        _interactioncategoryid = new global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid>();
        _interactionsubcategoryid = new global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid>();
        _contactmethodcodeid = new global::Blackbaud.AppFx.UIModeling.Core.CodeTableField();
        _eventid = new global::Blackbaud.AppFx.UIModeling.Core.SearchListField<System.Guid>();
        _expecteddate = new global::Blackbaud.AppFx.UIModeling.Core.DateField();
        _actualdate = new global::Blackbaud.AppFx.UIModeling.Core.DateField();
        _sites = new global::Blackbaud.AppFx.UIModeling.Core.CollectionField<UMHSInteractionFormSITESUIModel>();
        _siterequired = new global::Blackbaud.AppFx.UIModeling.Core.BooleanField();
        _comments = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _participants = new global::Blackbaud.AppFx.UIModeling.Core.CollectionField<UMHSInteractionFormPARTICIPANTSUIModel>();

        this.Mode = global::Blackbaud.AppFx.UIModeling.Core.DataFormMode.Add;
        this.DataFormTemplateId = new System.Guid("51f7a78b-7da7-48a6-860c-cde8848edc5a");
        this.DataFormInstanceId = new System.Guid("b3a04417-321f-44c4-a3b7-4b115e5eeafc");
        this.RecordType = "MIMED Interaction";
        this.ContextRecordType = "MIMED Data";
        this.FixedDialog = true;
        this.UserInterfaceUrl = "browser/htmlforms/custom/um.customfx.gratefulpatient/UMHSInteractionForm.html";

        //
        //_summary
        //
        _summary.Name = "SUMMARY";
        _summary.Caption = "Summary";
        _summary.Required = true;
        _summary.MaxLength = 100;
        this.Fields.Add(_summary);
        //
        //_name
        //
        _name.Name = "NAME";
        _name.Caption = "Patient name";
        _name.Visible = false;
        _name.DBReadOnly = true;
        _name.MaxLength = 700;
        this.Fields.Add(_name);
        //
        //_statuscodeid
        //
        _statuscodeid.Name = "STATUSCODEID";
        _statuscodeid.Caption = "Status";
        _statuscodeid.Required = true;
        _statuscodeid.CodeTableName = "USR_INTERACTION_STATUSCODE";
        this.Fields.Add(_statuscodeid);
        //
        //_fundraiserid
        //
        _fundraiserid.Name = "FUNDRAISERID";
        _fundraiserid.Caption = "Owner";
        _fundraiserid.SearchListId = new System.Guid("35fa0186-b669-436f-913a-5e9fd5e59982");
        _fundraiserid.EnableQuickFind = true;
        this.Fields.Add(_fundraiserid);
        //
        //_interactioncategoryid
        //
        _interactioncategoryid.Name = "INTERACTIONCATEGORYID";
        _interactioncategoryid.Caption = "Category";
        _interactioncategoryid.Required = true;
        _interactioncategoryid.SimpleDataListId = new System.Guid("cbba7545-b66f-44ac-aa24-d9c2f8cbc4ec");
        this.Fields.Add(_interactioncategoryid);
        //
        //_interactionsubcategoryid
        //
        _interactionsubcategoryid.Name = "INTERACTIONSUBCATEGORYID";
        _interactionsubcategoryid.Caption = "Subcategory";
        _interactionsubcategoryid.Required = true;
        _interactionsubcategoryid.SimpleDataListId = new System.Guid("0eacc39b-07d1-4641-8774-e319559535a7");
        _interactionsubcategoryid.Parameters.Add(new global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListParameter("INTERACTIONCATEGORYID", "Fields!INTERACTIONCATEGORYID"));
        this.Fields.Add(_interactionsubcategoryid);
        //
        //_contactmethodcodeid
        //
        _contactmethodcodeid.Name = "CONTACTMETHODCODEID";
        _contactmethodcodeid.Caption = "Contact method";
        _contactmethodcodeid.Required = true;
        _contactmethodcodeid.CodeTableName = "INTERACTIONTYPECODE";
        this.Fields.Add(_contactmethodcodeid);
        //
        //_eventid
        //
        _eventid.Name = "EVENTID";
        _eventid.Caption = "Event";
        _eventid.SearchListId = new System.Guid("21452a39-7c7d-4334-8b89-6c0ea619acec");
        _eventid.EnableQuickFind = true;
        this.Fields.Add(_eventid);
        //
        //_expecteddate
        //
        _expecteddate.Name = "EXPECTEDDATE";
        _expecteddate.Caption = "Expected date";
        _expecteddate.Required = true;
        this.Fields.Add(_expecteddate);
        //
        //_actualdate
        //
        _actualdate.Name = "ACTUALDATE";
        _actualdate.Caption = "Actual date";
        this.Fields.Add(_actualdate);
        //
        //_sites
        //
        _sites.Name = "SITES";
        _sites.Caption = "Sites";
        this.Fields.Add(_sites);
        //
        //_siterequired
        //
        _siterequired.Name = "SITEREQUIRED";
        _siterequired.Caption = "Site required";
        _siterequired.DBReadOnly = true;
        this.Fields.Add(_siterequired);
        //
        //_comments
        //
        _comments.Name = "COMMENT";
        _comments.Caption = "Comments";
        this.Fields.Add(_comments);
        //
        //_participants
        //
        _participants.Name = "PARTICIPANTS";
        _participants.Caption = "Participants";
        this.Fields.Add(_participants);

		OnCreated();

	}

    /// <summary>
    /// Summary
    /// </summary>
    [System.ComponentModel.Description("Summary")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @SUMMARY {
		get { return _summary; }
	}

    /// <summary>
    /// Patient name
    /// </summary>
    [System.ComponentModel.Description("Patient name")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @NAME {
		get { return _name; }
	}

    /// <summary>
    /// Status
    /// </summary>
    [System.ComponentModel.Description("Status")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.CodeTableField @STATUSCODEID {
		get { return _statuscodeid; }
	}

    /// <summary>
    /// Owner
    /// </summary>
    [System.ComponentModel.Description("Owner")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.SearchListField<System.Guid> @FUNDRAISERID {
		get { return _fundraiserid; }
	}

    /// <summary>
    /// Category
    /// </summary>
    [System.ComponentModel.Description("Category")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid> @INTERACTIONCATEGORYID {
		get { return _interactioncategoryid; }
	}

    /// <summary>
    /// Subcategory
    /// </summary>
    [System.ComponentModel.Description("Subcategory")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid> @INTERACTIONSUBCATEGORYID {
		get { return _interactionsubcategoryid; }
	}

    /// <summary>
    /// Contact method
    /// </summary>
    [System.ComponentModel.Description("Contact method")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.CodeTableField @CONTACTMETHODCODEID {
		get { return _contactmethodcodeid; }
	}

    /// <summary>
    /// Event
    /// </summary>
    [System.ComponentModel.Description("Event")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.SearchListField<System.Guid> @EVENTID {
		get { return _eventid; }
	}

    /// <summary>
    /// Expected date
    /// </summary>
    [System.ComponentModel.Description("Expected date")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.DateField @EXPECTEDDATE {
		get { return _expecteddate; }
	}

    /// <summary>
    /// Actual date
    /// </summary>
    [System.ComponentModel.Description("Actual date")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.DateField @ACTUALDATE {
		get { return _actualdate; }
	}

    /// <summary>
    /// Sites
    /// </summary>
    [System.ComponentModel.Description("Sites")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.CollectionField<UMHSInteractionFormSITESUIModel> @SITES {
		get { return _sites; }
	}

    /// <summary>
    /// Site required
    /// </summary>
    [System.ComponentModel.Description("Site required")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.BooleanField @SITEREQUIRED {
		get { return _siterequired; }
	}

    /// <summary>
    /// Comments
    /// </summary>
    [System.ComponentModel.Description("Comments")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @COMMENTS {
		get { return _comments; }
	}

    /// <summary>
    /// Participants
    /// </summary>
    [System.ComponentModel.Description("Participants")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.CollectionField<UMHSInteractionFormPARTICIPANTSUIModel> @PARTICIPANTS {
		get { return _participants; }
	}

}


}
