//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by BBUIModelLibrary
//     Version:  4.0.165.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace UM.CustomFx.GratefulPatient.UIModel
{

/// <summary>
/// Represents the UI model for the 'UMHSDuplicateConstituentSearchNEWCONSTITUENT' data form
/// </summary>
public partial class @UMHSDuplicateConstituentSearchNEWCONSTITUENTUIModel : global::Blackbaud.AppFx.UIModeling.Core.UIModel
{

#region "Enums"

    /// <summary>
    /// Enumerated values for use with the GENDERCODE property
    /// </summary>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public enum GENDERCODES : int
	{
        @Unknown = 0,
        @Male = 1,
        @Female = 2
	}

    /// <summary>
    /// Enumerated values for use with the SPOUSE_GENDERCODE property
    /// </summary>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public enum SPOUSE_GENDERCODES : int
	{
        @Unknown = 0,
        @Male = 1,
        @Female = 2
	}

#endregion

#region "Extensibility methods"

	partial void OnCreated();

#endregion

    private global::Blackbaud.AppFx.UIModeling.Core.BooleanField _isorganization;
    private global::Blackbaud.AppFx.UIModeling.Core.BooleanField _isgroup;
    private global::Blackbaud.AppFx.UIModeling.Core.BooleanField _ishousehold;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _lastname;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _firstname;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _middlename;
    private global::Blackbaud.AppFx.UIModeling.Core.CodeTableField _titlecodeid;
    private global::Blackbaud.AppFx.UIModeling.Core.CodeTableField _suffixcodeid;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _nickname;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _maidenname;
    private global::Blackbaud.AppFx.UIModeling.Core.FuzzyDateField _birthdate;
    private global::Blackbaud.AppFx.UIModeling.Core.ValueListField<System.Nullable<GENDERCODES>> _gendercode;
    private global::Blackbaud.AppFx.UIModeling.Core.CodeTableField _maritalstatuscodeid;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _webaddress;
    private global::Blackbaud.AppFx.UIModeling.Core.CodeTableField _industrycodeid;
    private global::Blackbaud.AppFx.UIModeling.Core.IntegerField _numemployees;
    private global::Blackbaud.AppFx.UIModeling.Core.IntegerField _numsubsidiaries;
    private global::Blackbaud.AppFx.UIModeling.Core.SearchListField<System.Guid> _parentcorpid;
    private global::Blackbaud.AppFx.UIModeling.Core.CodeTableField _addressaddresstypecodeid;
    private global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid> _addresscountryid;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _addressaddressblock;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _addresscity;
    private global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid> _addressstateid;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _addresspostcode;
    private global::Blackbaud.AppFx.UIModeling.Core.BooleanField _addressdonotmail;
    private global::Blackbaud.AppFx.UIModeling.Core.CodeTableField _phonephonetypecodeid;
    private global::Blackbaud.AppFx.UIModeling.Core.PhoneField _phonenumber;
    private global::Blackbaud.AppFx.UIModeling.Core.CodeTableField _emailaddressemailaddresstypecodeid;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _emailaddressemailaddress;
    private global::Blackbaud.AppFx.UIModeling.Core.BooleanField _existingspouse;
    private global::Blackbaud.AppFx.UIModeling.Core.SearchListField<System.Guid> _spouseid;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _spouselastname;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _spousefirstname;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _spousemiddlename;
    private global::Blackbaud.AppFx.UIModeling.Core.CodeTableField _spousetitlecodeid;
    private global::Blackbaud.AppFx.UIModeling.Core.CodeTableField _spousesuffixcodeid;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _spousenickname;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _spousemaidenname;
    private global::Blackbaud.AppFx.UIModeling.Core.FuzzyDateField _spousebirthdate;
    private global::Blackbaud.AppFx.UIModeling.Core.ValueListField<System.Nullable<SPOUSE_GENDERCODES>> _spousegendercode;
    private global::Blackbaud.AppFx.UIModeling.Core.CodeTableField _spouserelationshiptypecodeid;
    private global::Blackbaud.AppFx.UIModeling.Core.CodeTableField _spousereciprocaltypecodeid;
    private global::Blackbaud.AppFx.UIModeling.Core.DateField _spousestartdate;
    private global::Blackbaud.AppFx.UIModeling.Core.BooleanField _spouseisspouse;
    private global::Blackbaud.AppFx.UIModeling.Core.BooleanField _copyprimaryinformation;
    private global::Blackbaud.AppFx.UIModeling.Core.BooleanField _primaryrelationshipexists;
    private global::Blackbaud.AppFx.UIModeling.Core.DecimalField _primarymatchfactor;
    private global::Blackbaud.AppFx.UIModeling.Core.BooleanField _reciprocalrelationshipexists;
    private global::Blackbaud.AppFx.UIModeling.Core.DecimalField _reciprocalmatchfactor;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _existingbusiness;
    private global::Blackbaud.AppFx.UIModeling.Core.SearchListField<string> _businessid;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _businessname;
    private global::Blackbaud.AppFx.UIModeling.Core.CodeTableField _businessaddresstypecodeid;
    private global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid> _businesscountryid;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _businessaddressblock;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _businesscity;
    private global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid> _businessstateid;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _businesspostcode;
    private global::Blackbaud.AppFx.UIModeling.Core.BooleanField _businessdonotmail;
    private global::Blackbaud.AppFx.UIModeling.Core.CodeTableField _businessphonetypecodeid;
    private global::Blackbaud.AppFx.UIModeling.Core.PhoneField _businessnumber;
    private global::Blackbaud.AppFx.UIModeling.Core.CodeTableField _businessrelationshiptypecodeid;
    private global::Blackbaud.AppFx.UIModeling.Core.CodeTableField _businessreciprocaltypecodeid;
    private global::Blackbaud.AppFx.UIModeling.Core.DateField _businessstartdate;
    private global::Blackbaud.AppFx.UIModeling.Core.BooleanField _iscontact;
    private global::Blackbaud.AppFx.UIModeling.Core.CodeTableField _contacttypecodeid;
    private global::Blackbaud.AppFx.UIModeling.Core.BooleanField _isprimarycontact;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _position;
    private global::Blackbaud.AppFx.UIModeling.Core.BooleanField _ismatchinggiftrelationship;
    private global::Blackbaud.AppFx.UIModeling.Core.BooleanField _givesanonymously;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _groupdescription;
    private global::Blackbaud.AppFx.UIModeling.Core.SearchListField<System.Guid> _groupprimarycontact;
    private global::Blackbaud.AppFx.UIModeling.Core.DateField _groupstartdate;
    private global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid> _groupgrouptypeid;
    private global::Blackbaud.AppFx.UIModeling.Core.SearchListField<System.Guid> _householdprimarycontactid;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _householdprimarycontactkeyname;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _householdprimarycontactfirstname;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _householdprimarycontactmiddlename;
    private global::Blackbaud.AppFx.UIModeling.Core.CodeTableField _householdprimarycontacttitlecodeid;
    private global::Blackbaud.AppFx.UIModeling.Core.CodeTableField _householdprimarycontactsuffixcodeid;
    private global::Blackbaud.AppFx.UIModeling.Core.BooleanField _householdprimarycontactcopyhouseholdcontact;
    private global::Blackbaud.AppFx.UIModeling.Core.SearchListField<System.Guid> _householdsecondmemberid;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _householdsecondmemberkeyname;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _householdsecondmemberfirstname;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _householdsecondmembermiddlename;
    private global::Blackbaud.AppFx.UIModeling.Core.CodeTableField _householdsecondmembertitlecodeid;
    private global::Blackbaud.AppFx.UIModeling.Core.CodeTableField _householdsecondmembersuffixcodeid;
    private global::Blackbaud.AppFx.UIModeling.Core.BooleanField _householdsecondmembercopyhouseholdcontact;
    private global::Blackbaud.AppFx.UIModeling.Core.CodeTableField _householdsecondmemberrelationshipreciprocaltypecodeid;
    private global::Blackbaud.AppFx.UIModeling.Core.CodeTableField _householdsecondmemberrelationshiprelationshiptypecodeid;
    private global::Blackbaud.AppFx.UIModeling.Core.DateField _householdsecondmemberrelationshipstartdate;
    private global::Blackbaud.AppFx.UIModeling.Core.BooleanField _householdsecondmemberrelationshipisspouse;

	[System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public @UMHSDuplicateConstituentSearchNEWCONSTITUENTUIModel() : base()
	{


        _isorganization = new global::Blackbaud.AppFx.UIModeling.Core.BooleanField();
        _isgroup = new global::Blackbaud.AppFx.UIModeling.Core.BooleanField();
        _ishousehold = new global::Blackbaud.AppFx.UIModeling.Core.BooleanField();
        _lastname = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _firstname = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _middlename = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _titlecodeid = new global::Blackbaud.AppFx.UIModeling.Core.CodeTableField();
        _suffixcodeid = new global::Blackbaud.AppFx.UIModeling.Core.CodeTableField();
        _nickname = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _maidenname = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _birthdate = new global::Blackbaud.AppFx.UIModeling.Core.FuzzyDateField();
        _gendercode = new global::Blackbaud.AppFx.UIModeling.Core.ValueListField<System.Nullable<GENDERCODES>>();
        _maritalstatuscodeid = new global::Blackbaud.AppFx.UIModeling.Core.CodeTableField();
        _webaddress = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _industrycodeid = new global::Blackbaud.AppFx.UIModeling.Core.CodeTableField();
        _numemployees = new global::Blackbaud.AppFx.UIModeling.Core.IntegerField();
        _numsubsidiaries = new global::Blackbaud.AppFx.UIModeling.Core.IntegerField();
        _parentcorpid = new global::Blackbaud.AppFx.UIModeling.Core.SearchListField<System.Guid>();
        _addressaddresstypecodeid = new global::Blackbaud.AppFx.UIModeling.Core.CodeTableField();
        _addresscountryid = new global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid>();
        _addressaddressblock = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _addresscity = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _addressstateid = new global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid>();
        _addresspostcode = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _addressdonotmail = new global::Blackbaud.AppFx.UIModeling.Core.BooleanField();
        _phonephonetypecodeid = new global::Blackbaud.AppFx.UIModeling.Core.CodeTableField();
        _phonenumber = new global::Blackbaud.AppFx.UIModeling.Core.PhoneField();
        _emailaddressemailaddresstypecodeid = new global::Blackbaud.AppFx.UIModeling.Core.CodeTableField();
        _emailaddressemailaddress = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _existingspouse = new global::Blackbaud.AppFx.UIModeling.Core.BooleanField();
        _spouseid = new global::Blackbaud.AppFx.UIModeling.Core.SearchListField<System.Guid>();
        _spouselastname = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _spousefirstname = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _spousemiddlename = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _spousetitlecodeid = new global::Blackbaud.AppFx.UIModeling.Core.CodeTableField();
        _spousesuffixcodeid = new global::Blackbaud.AppFx.UIModeling.Core.CodeTableField();
        _spousenickname = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _spousemaidenname = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _spousebirthdate = new global::Blackbaud.AppFx.UIModeling.Core.FuzzyDateField();
        _spousegendercode = new global::Blackbaud.AppFx.UIModeling.Core.ValueListField<System.Nullable<SPOUSE_GENDERCODES>>();
        _spouserelationshiptypecodeid = new global::Blackbaud.AppFx.UIModeling.Core.CodeTableField();
        _spousereciprocaltypecodeid = new global::Blackbaud.AppFx.UIModeling.Core.CodeTableField();
        _spousestartdate = new global::Blackbaud.AppFx.UIModeling.Core.DateField();
        _spouseisspouse = new global::Blackbaud.AppFx.UIModeling.Core.BooleanField();
        _copyprimaryinformation = new global::Blackbaud.AppFx.UIModeling.Core.BooleanField();
        _primaryrelationshipexists = new global::Blackbaud.AppFx.UIModeling.Core.BooleanField();
        _primarymatchfactor = new global::Blackbaud.AppFx.UIModeling.Core.DecimalField();
        _reciprocalrelationshipexists = new global::Blackbaud.AppFx.UIModeling.Core.BooleanField();
        _reciprocalmatchfactor = new global::Blackbaud.AppFx.UIModeling.Core.DecimalField();
        _existingbusiness = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _businessid = new global::Blackbaud.AppFx.UIModeling.Core.SearchListField<string>();
        _businessname = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _businessaddresstypecodeid = new global::Blackbaud.AppFx.UIModeling.Core.CodeTableField();
        _businesscountryid = new global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid>();
        _businessaddressblock = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _businesscity = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _businessstateid = new global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid>();
        _businesspostcode = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _businessdonotmail = new global::Blackbaud.AppFx.UIModeling.Core.BooleanField();
        _businessphonetypecodeid = new global::Blackbaud.AppFx.UIModeling.Core.CodeTableField();
        _businessnumber = new global::Blackbaud.AppFx.UIModeling.Core.PhoneField();
        _businessrelationshiptypecodeid = new global::Blackbaud.AppFx.UIModeling.Core.CodeTableField();
        _businessreciprocaltypecodeid = new global::Blackbaud.AppFx.UIModeling.Core.CodeTableField();
        _businessstartdate = new global::Blackbaud.AppFx.UIModeling.Core.DateField();
        _iscontact = new global::Blackbaud.AppFx.UIModeling.Core.BooleanField();
        _contacttypecodeid = new global::Blackbaud.AppFx.UIModeling.Core.CodeTableField();
        _isprimarycontact = new global::Blackbaud.AppFx.UIModeling.Core.BooleanField();
        _position = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _ismatchinggiftrelationship = new global::Blackbaud.AppFx.UIModeling.Core.BooleanField();
        _givesanonymously = new global::Blackbaud.AppFx.UIModeling.Core.BooleanField();
        _groupdescription = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _groupprimarycontact = new global::Blackbaud.AppFx.UIModeling.Core.SearchListField<System.Guid>();
        _groupstartdate = new global::Blackbaud.AppFx.UIModeling.Core.DateField();
        _groupgrouptypeid = new global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid>();
        _householdprimarycontactid = new global::Blackbaud.AppFx.UIModeling.Core.SearchListField<System.Guid>();
        _householdprimarycontactkeyname = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _householdprimarycontactfirstname = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _householdprimarycontactmiddlename = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _householdprimarycontacttitlecodeid = new global::Blackbaud.AppFx.UIModeling.Core.CodeTableField();
        _householdprimarycontactsuffixcodeid = new global::Blackbaud.AppFx.UIModeling.Core.CodeTableField();
        _householdprimarycontactcopyhouseholdcontact = new global::Blackbaud.AppFx.UIModeling.Core.BooleanField();
        _householdsecondmemberid = new global::Blackbaud.AppFx.UIModeling.Core.SearchListField<System.Guid>();
        _householdsecondmemberkeyname = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _householdsecondmemberfirstname = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _householdsecondmembermiddlename = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _householdsecondmembertitlecodeid = new global::Blackbaud.AppFx.UIModeling.Core.CodeTableField();
        _householdsecondmembersuffixcodeid = new global::Blackbaud.AppFx.UIModeling.Core.CodeTableField();
        _householdsecondmembercopyhouseholdcontact = new global::Blackbaud.AppFx.UIModeling.Core.BooleanField();
        _householdsecondmemberrelationshipreciprocaltypecodeid = new global::Blackbaud.AppFx.UIModeling.Core.CodeTableField();
        _householdsecondmemberrelationshiprelationshiptypecodeid = new global::Blackbaud.AppFx.UIModeling.Core.CodeTableField();
        _householdsecondmemberrelationshipstartdate = new global::Blackbaud.AppFx.UIModeling.Core.DateField();
        _householdsecondmemberrelationshipisspouse = new global::Blackbaud.AppFx.UIModeling.Core.BooleanField();

        //
        //_isorganization
        //
        _isorganization.Name = "ISORGANIZATION";
        _isorganization.Caption = "Is organization";
        this.Fields.Add(_isorganization);
        //
        //_isgroup
        //
        _isgroup.Name = "ISGROUP";
        _isgroup.Caption = "Is group";
        this.Fields.Add(_isgroup);
        //
        //_ishousehold
        //
        _ishousehold.Name = "ISHOUSEHOLD";
        _ishousehold.Caption = "Is household";
        this.Fields.Add(_ishousehold);
        //
        //_lastname
        //
        _lastname.Name = "LASTNAME";
        _lastname.Caption = "Last\\org\\group\\household name";
        _lastname.Required = true;
        this.Fields.Add(_lastname);
        //
        //_firstname
        //
        _firstname.Name = "FIRSTNAME";
        _firstname.Caption = "First name";
        this.Fields.Add(_firstname);
        //
        //_middlename
        //
        _middlename.Name = "MIDDLENAME";
        _middlename.Caption = "Middle name";
        this.Fields.Add(_middlename);
        //
        //_titlecodeid
        //
        _titlecodeid.Name = "TITLECODEID";
        _titlecodeid.Caption = "Title";
        _titlecodeid.CodeTableName = "TITLECODE";
        this.Fields.Add(_titlecodeid);
        //
        //_suffixcodeid
        //
        _suffixcodeid.Name = "SUFFIXCODEID";
        _suffixcodeid.Caption = "Suffix";
        _suffixcodeid.CodeTableName = "SUFFIXCODE";
        this.Fields.Add(_suffixcodeid);
        //
        //_nickname
        //
        _nickname.Name = "NICKNAME";
        _nickname.Caption = "Nickname";
        this.Fields.Add(_nickname);
        //
        //_maidenname
        //
        _maidenname.Name = "MAIDENNAME";
        _maidenname.Caption = "Maiden name";
        this.Fields.Add(_maidenname);
        //
        //_birthdate
        //
        _birthdate.Name = "BIRTHDATE";
        _birthdate.Caption = "Birth date";
        _birthdate.AllowMonthDay = true;
        this.Fields.Add(_birthdate);
        //
        //_gendercode
        //
        _gendercode.Name = "GENDERCODE";
        _gendercode.Caption = "Gender";
        _gendercode.DataSource.Add(new global::Blackbaud.AppFx.UIModeling.Core.ValueListItem<System.Nullable<GENDERCODES>> {Value = GENDERCODES.@Unknown, Translation = "Unknown"});
        _gendercode.DataSource.Add(new global::Blackbaud.AppFx.UIModeling.Core.ValueListItem<System.Nullable<GENDERCODES>> {Value = GENDERCODES.@Male, Translation = "Male"});
        _gendercode.DataSource.Add(new global::Blackbaud.AppFx.UIModeling.Core.ValueListItem<System.Nullable<GENDERCODES>> {Value = GENDERCODES.@Female, Translation = "Female"});
        _gendercode.Value = GENDERCODES.@Unknown;
        this.Fields.Add(_gendercode);
        //
        //_maritalstatuscodeid
        //
        _maritalstatuscodeid.Name = "MARITALSTATUSCODEID";
        _maritalstatuscodeid.Caption = "Marital status";
        _maritalstatuscodeid.CodeTableName = "MARITALSTATUSCODE";
        this.Fields.Add(_maritalstatuscodeid);
        //
        //_webaddress
        //
        _webaddress.Name = "WEBADDRESS";
        _webaddress.Caption = "Website";
        this.Fields.Add(_webaddress);
        //
        //_industrycodeid
        //
        _industrycodeid.Name = "INDUSTRYCODEID";
        _industrycodeid.Caption = "Industry";
        _industrycodeid.CodeTableName = "INDUSTRYCODE";
        this.Fields.Add(_industrycodeid);
        //
        //_numemployees
        //
        _numemployees.Name = "NUMEMPLOYEES";
        _numemployees.Caption = "No. of employees";
        this.Fields.Add(_numemployees);
        //
        //_numsubsidiaries
        //
        _numsubsidiaries.Name = "NUMSUBSIDIARIES";
        _numsubsidiaries.Caption = "No. of subsidiary orgs";
        this.Fields.Add(_numsubsidiaries);
        //
        //_parentcorpid
        //
        _parentcorpid.Name = "PARENTCORPID";
        _parentcorpid.Caption = "Parent org";
        _parentcorpid.SearchListId = new System.Guid("ef1da4e7-0631-49de-bd60-7d084cb7cb2b");
        this.Fields.Add(_parentcorpid);
        //
        //_addressaddresstypecodeid
        //
        _addressaddresstypecodeid.Name = "ADDRESS_ADDRESSTYPECODEID";
        _addressaddresstypecodeid.Caption = "Address type";
        _addressaddresstypecodeid.CodeTableName = "ADDRESSTYPECODE";
        this.Fields.Add(_addressaddresstypecodeid);
        //
        //_addresscountryid
        //
        _addresscountryid.Name = "ADDRESS_COUNTRYID";
        _addresscountryid.Caption = "Country";
        _addresscountryid.SimpleDataListId = new System.Guid("c9649672-353d-42e8-8c25-4d34bbabfbba");
        this.Fields.Add(_addresscountryid);
        //
        //_addressaddressblock
        //
        _addressaddressblock.Name = "ADDRESS_ADDRESSBLOCK";
        _addressaddressblock.Caption = "Address";
        this.Fields.Add(_addressaddressblock);
        //
        //_addresscity
        //
        _addresscity.Name = "ADDRESS_CITY";
        _addresscity.Caption = "City";
        this.Fields.Add(_addresscity);
        //
        //_addressstateid
        //
        _addressstateid.Name = "ADDRESS_STATEID";
        _addressstateid.Caption = "State";
        _addressstateid.SimpleDataListId = new System.Guid("7fa91401-596c-4f7c-936d-6e41683121d7");
        _addressstateid.Parameters.Add(new global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListParameter("COUNTRYID", "Fields!ADDRESS_COUNTRYID"));
        this.Fields.Add(_addressstateid);
        //
        //_addresspostcode
        //
        _addresspostcode.Name = "ADDRESS_POSTCODE";
        _addresspostcode.Caption = "ZIP";
        this.Fields.Add(_addresspostcode);
        //
        //_addressdonotmail
        //
        _addressdonotmail.Name = "ADDRESS_DONOTMAIL";
        _addressdonotmail.Caption = "Do not send mail to this address";
        this.Fields.Add(_addressdonotmail);
        //
        //_phonephonetypecodeid
        //
        _phonephonetypecodeid.Name = "PHONE_PHONETYPECODEID";
        _phonephonetypecodeid.Caption = "Phone type";
        _phonephonetypecodeid.CodeTableName = "PHONETYPECODE";
        this.Fields.Add(_phonephonetypecodeid);
        //
        //_phonenumber
        //
        _phonenumber.Name = "PHONE_NUMBER";
        _phonenumber.Caption = "Phone number";
        this.Fields.Add(_phonenumber);
        //
        //_emailaddressemailaddresstypecodeid
        //
        _emailaddressemailaddresstypecodeid.Name = "EMAILADDRESS_EMAILADDRESSTYPECODEID";
        _emailaddressemailaddresstypecodeid.Caption = "Email type";
        _emailaddressemailaddresstypecodeid.CodeTableName = "EMAILADDRESSTYPECODE";
        this.Fields.Add(_emailaddressemailaddresstypecodeid);
        //
        //_emailaddressemailaddress
        //
        _emailaddressemailaddress.Name = "EMAILADDRESS_EMAILADDRESS";
        _emailaddressemailaddress.Caption = "Email address";
        this.Fields.Add(_emailaddressemailaddress);
        //
        //_existingspouse
        //
        _existingspouse.Name = "EXISTINGSPOUSE";
        _existingspouse.Caption = "Existing constituent";
        this.Fields.Add(_existingspouse);
        //
        //_spouseid
        //
        _spouseid.Name = "SPOUSEID";
        _spouseid.Caption = "Spouse full name";
        _spouseid.SearchListId = new System.Guid("4685952f-6964-486c-9acd-5560a8a30862");
        this.Fields.Add(_spouseid);
        //
        //_spouselastname
        //
        _spouselastname.Name = "SPOUSE_LASTNAME";
        _spouselastname.Caption = "Spouse last name";
        this.Fields.Add(_spouselastname);
        //
        //_spousefirstname
        //
        _spousefirstname.Name = "SPOUSE_FIRSTNAME";
        _spousefirstname.Caption = "Spouse first name";
        this.Fields.Add(_spousefirstname);
        //
        //_spousemiddlename
        //
        _spousemiddlename.Name = "SPOUSE_MIDDLENAME";
        _spousemiddlename.Caption = "Spouse middle name";
        this.Fields.Add(_spousemiddlename);
        //
        //_spousetitlecodeid
        //
        _spousetitlecodeid.Name = "SPOUSE_TITLECODEID";
        _spousetitlecodeid.Caption = "Spouse title";
        _spousetitlecodeid.CodeTableName = "TITLECODE";
        this.Fields.Add(_spousetitlecodeid);
        //
        //_spousesuffixcodeid
        //
        _spousesuffixcodeid.Name = "SPOUSE_SUFFIXCODEID";
        _spousesuffixcodeid.Caption = "Spouse suffix";
        _spousesuffixcodeid.CodeTableName = "SUFFIXCODE";
        this.Fields.Add(_spousesuffixcodeid);
        //
        //_spousenickname
        //
        _spousenickname.Name = "SPOUSE_NICKNAME";
        _spousenickname.Caption = "Spouse nickname";
        this.Fields.Add(_spousenickname);
        //
        //_spousemaidenname
        //
        _spousemaidenname.Name = "SPOUSE_MAIDENNAME";
        _spousemaidenname.Caption = "Spouse maiden name";
        this.Fields.Add(_spousemaidenname);
        //
        //_spousebirthdate
        //
        _spousebirthdate.Name = "SPOUSE_BIRTHDATE";
        _spousebirthdate.Caption = "Spouse birth date";
        _spousebirthdate.AllowMonthDay = true;
        this.Fields.Add(_spousebirthdate);
        //
        //_spousegendercode
        //
        _spousegendercode.Name = "SPOUSE_GENDERCODE";
        _spousegendercode.Caption = "Spouse gender";
        _spousegendercode.DataSource.Add(new global::Blackbaud.AppFx.UIModeling.Core.ValueListItem<System.Nullable<SPOUSE_GENDERCODES>> {Value = SPOUSE_GENDERCODES.@Unknown, Translation = "Unknown"});
        _spousegendercode.DataSource.Add(new global::Blackbaud.AppFx.UIModeling.Core.ValueListItem<System.Nullable<SPOUSE_GENDERCODES>> {Value = SPOUSE_GENDERCODES.@Male, Translation = "Male"});
        _spousegendercode.DataSource.Add(new global::Blackbaud.AppFx.UIModeling.Core.ValueListItem<System.Nullable<SPOUSE_GENDERCODES>> {Value = SPOUSE_GENDERCODES.@Female, Translation = "Female"});
        _spousegendercode.Value = SPOUSE_GENDERCODES.@Unknown;
        this.Fields.Add(_spousegendercode);
        //
        //_spouserelationshiptypecodeid
        //
        _spouserelationshiptypecodeid.Name = "SPOUSE_RELATIONSHIPTYPECODEID";
        _spouserelationshiptypecodeid.Caption = "Spouse relationship type";
        _spouserelationshiptypecodeid.CodeTableName = "RELATIONSHIPTYPECODE";
        this.Fields.Add(_spouserelationshiptypecodeid);
        //
        //_spousereciprocaltypecodeid
        //
        _spousereciprocaltypecodeid.Name = "SPOUSE_RECIPROCALTYPECODEID";
        _spousereciprocaltypecodeid.Caption = "Spouse reciprocal relationship type";
        _spousereciprocaltypecodeid.CodeTableName = "RELATIONSHIPTYPECODE";
        this.Fields.Add(_spousereciprocaltypecodeid);
        //
        //_spousestartdate
        //
        _spousestartdate.Name = "SPOUSE_STARTDATE";
        _spousestartdate.Caption = "Spouse start date";
        this.Fields.Add(_spousestartdate);
        //
        //_spouseisspouse
        //
        _spouseisspouse.Name = "SPOUSE_ISSPOUSE";
        _spouseisspouse.Caption = "Is spouse";
        this.Fields.Add(_spouseisspouse);
        //
        //_copyprimaryinformation
        //
        _copyprimaryinformation.Name = "COPYPRIMARYINFORMATION";
        _copyprimaryinformation.Caption = "Copy primary information";
        _copyprimaryinformation.Value = true;
        this.Fields.Add(_copyprimaryinformation);
        //
        //_primaryrelationshipexists
        //
        _primaryrelationshipexists.Name = "PRIMARYRELATIONSHIPEXISTS";
        _primaryrelationshipexists.Caption = "Apply recognition credit to individual for constituent's payments";
        this.Fields.Add(_primaryrelationshipexists);
        //
        //_primarymatchfactor
        //
        _primarymatchfactor.Name = "PRIMARYMATCHFACTOR";
        _primarymatchfactor.Caption = "Primary recognition credit factor";
        _primarymatchfactor.Value = 100M;
        this.Fields.Add(_primarymatchfactor);
        //
        //_reciprocalrelationshipexists
        //
        _reciprocalrelationshipexists.Name = "RECIPROCALRELATIONSHIPEXISTS";
        _reciprocalrelationshipexists.Caption = "Apply recognition credit to constituent for individual's payments";
        this.Fields.Add(_reciprocalrelationshipexists);
        //
        //_reciprocalmatchfactor
        //
        _reciprocalmatchfactor.Name = "RECIPROCALMATCHFACTOR";
        _reciprocalmatchfactor.Caption = "Reciprocal recognition credit factor";
        _reciprocalmatchfactor.Value = 100M;
        this.Fields.Add(_reciprocalmatchfactor);
        //
        //_existingbusiness
        //
        _existingbusiness.Name = "EXISTINGBUSINESS";
        _existingbusiness.Caption = "Business is existing constituent";
        this.Fields.Add(_existingbusiness);
        //
        //_businessid
        //
        _businessid.Name = "BUSINESSID";
        _businessid.Caption = "Org name";
        _businessid.SearchListId = new System.Guid("ef1da4e7-0631-49de-bd60-7d084cb7cb2b");
        this.Fields.Add(_businessid);
        //
        //_businessname
        //
        _businessname.Name = "BUSINESS_NAME";
        _businessname.Caption = "Business organization name";
        this.Fields.Add(_businessname);
        //
        //_businessaddresstypecodeid
        //
        _businessaddresstypecodeid.Name = "BUSINESS_ADDRESSTYPECODEID";
        _businessaddresstypecodeid.Caption = "Business address type";
        _businessaddresstypecodeid.CodeTableName = "ADDRESSTYPECODE";
        this.Fields.Add(_businessaddresstypecodeid);
        //
        //_businesscountryid
        //
        _businesscountryid.Name = "BUSINESS_COUNTRYID";
        _businesscountryid.Caption = "Business country";
        _businesscountryid.SimpleDataListId = new System.Guid("c9649672-353d-42e8-8c25-4d34bbabfbba");
        this.Fields.Add(_businesscountryid);
        //
        //_businessaddressblock
        //
        _businessaddressblock.Name = "BUSINESS_ADDRESSBLOCK";
        _businessaddressblock.Caption = "Business address";
        this.Fields.Add(_businessaddressblock);
        //
        //_businesscity
        //
        _businesscity.Name = "BUSINESS_CITY";
        _businesscity.Caption = "Business city";
        this.Fields.Add(_businesscity);
        //
        //_businessstateid
        //
        _businessstateid.Name = "BUSINESS_STATEID";
        _businessstateid.Caption = "Business state";
        _businessstateid.SimpleDataListId = new System.Guid("7fa91401-596c-4f7c-936d-6e41683121d7");
        _businessstateid.Parameters.Add(new global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListParameter("COUNTRYID", "Fields!ADDRESS_COUNTRYID"));
        this.Fields.Add(_businessstateid);
        //
        //_businesspostcode
        //
        _businesspostcode.Name = "BUSINESS_POSTCODE";
        _businesspostcode.Caption = "Business ZIP";
        this.Fields.Add(_businesspostcode);
        //
        //_businessdonotmail
        //
        _businessdonotmail.Name = "BUSINESS_DONOTMAIL";
        _businessdonotmail.Caption = "Business do not send mail to this address";
        this.Fields.Add(_businessdonotmail);
        //
        //_businessphonetypecodeid
        //
        _businessphonetypecodeid.Name = "BUSINESS_PHONETYPECODEID";
        _businessphonetypecodeid.Caption = "Business phone type";
        _businessphonetypecodeid.CodeTableName = "PHONETYPECODE";
        this.Fields.Add(_businessphonetypecodeid);
        //
        //_businessnumber
        //
        _businessnumber.Name = "BUSINESS_NUMBER";
        _businessnumber.Caption = "Business phone number";
        this.Fields.Add(_businessnumber);
        //
        //_businessrelationshiptypecodeid
        //
        _businessrelationshiptypecodeid.Name = "BUSINESS_RELATIONSHIPTYPECODEID";
        _businessrelationshiptypecodeid.Caption = "Business relationship type";
        _businessrelationshiptypecodeid.CodeTableName = "RELATIONSHIPTYPECODE";
        this.Fields.Add(_businessrelationshiptypecodeid);
        //
        //_businessreciprocaltypecodeid
        //
        _businessreciprocaltypecodeid.Name = "BUSINESS_RECIPROCALTYPECODEID";
        _businessreciprocaltypecodeid.Caption = "Business reciprocal relationship type";
        _businessreciprocaltypecodeid.CodeTableName = "RELATIONSHIPTYPECODE";
        this.Fields.Add(_businessreciprocaltypecodeid);
        //
        //_businessstartdate
        //
        _businessstartdate.Name = "BUSINESS_STARTDATE";
        _businessstartdate.Caption = "Business start date";
        this.Fields.Add(_businessstartdate);
        //
        //_iscontact
        //
        _iscontact.Name = "ISCONTACT";
        _iscontact.Caption = "Is contact";
        this.Fields.Add(_iscontact);
        //
        //_contacttypecodeid
        //
        _contacttypecodeid.Name = "CONTACTTYPECODEID";
        _contacttypecodeid.Caption = "Contact type";
        _contacttypecodeid.CodeTableName = "CONTACTTYPECODE";
        this.Fields.Add(_contacttypecodeid);
        //
        //_isprimarycontact
        //
        _isprimarycontact.Name = "ISPRIMARYCONTACT";
        _isprimarycontact.Caption = "Primary contact";
        this.Fields.Add(_isprimarycontact);
        //
        //_position
        //
        _position.Name = "POSITION";
        _position.Caption = "Position";
        this.Fields.Add(_position);
        //
        //_ismatchinggiftrelationship
        //
        _ismatchinggiftrelationship.Name = "ISMATCHINGGIFTRELATIONSHIP";
        _ismatchinggiftrelationship.Caption = "This organization will match individual's contributions";
        this.Fields.Add(_ismatchinggiftrelationship);
        //
        //_givesanonymously
        //
        _givesanonymously.Name = "GIVESANONYMOUSLY";
        _givesanonymously.Caption = "Gives anonymously";
        this.Fields.Add(_givesanonymously);
        //
        //_groupdescription
        //
        _groupdescription.Name = "GROUP_DESCRIPTION";
        _groupdescription.Caption = "Group\\household description";
        this.Fields.Add(_groupdescription);
        //
        //_groupprimarycontact
        //
        _groupprimarycontact.Name = "GROUP_PRIMARYCONTACT";
        _groupprimarycontact.Caption = "Group primary contact";
        _groupprimarycontact.SearchListId = new System.Guid("8d689026-e3b8-4d0e-8cbd-ac640039783c");
        this.Fields.Add(_groupprimarycontact);
        //
        //_groupstartdate
        //
        _groupstartdate.Name = "GROUP_STARTDATE";
        _groupstartdate.Caption = "Group start date";
        this.Fields.Add(_groupstartdate);
        //
        //_groupgrouptypeid
        //
        _groupgrouptypeid.Name = "GROUP_GROUPTYPEID";
        _groupgrouptypeid.Caption = "Group type";
        _groupgrouptypeid.SimpleDataListId = new System.Guid("927b11bc-3f88-44b0-a8fb-cfc1d5c627ea");
        this.Fields.Add(_groupgrouptypeid);
        //
        //_householdprimarycontactid
        //
        _householdprimarycontactid.Name = "HOUSEHOLD_PRIMARYCONTACTID";
        _householdprimarycontactid.Caption = "Existing household primary contact";
        _householdprimarycontactid.SearchListId = new System.Guid("4685952f-6964-486c-9acd-5560a8a30862");
        _householdprimarycontactid.EnableQuickFind = true;
        this.Fields.Add(_householdprimarycontactid);
        //
        //_householdprimarycontactkeyname
        //
        _householdprimarycontactkeyname.Name = "HOUSEHOLD_PRIMARYCONTACT_KEYNAME";
        _householdprimarycontactkeyname.Caption = "New household primary contact last name";
        this.Fields.Add(_householdprimarycontactkeyname);
        //
        //_householdprimarycontactfirstname
        //
        _householdprimarycontactfirstname.Name = "HOUSEHOLD_PRIMARYCONTACT_FIRSTNAME";
        _householdprimarycontactfirstname.Caption = "New household primary contact first name";
        this.Fields.Add(_householdprimarycontactfirstname);
        //
        //_householdprimarycontactmiddlename
        //
        _householdprimarycontactmiddlename.Name = "HOUSEHOLD_PRIMARYCONTACT_MIDDLENAME";
        _householdprimarycontactmiddlename.Caption = "New household primary contact middle initial";
        this.Fields.Add(_householdprimarycontactmiddlename);
        //
        //_householdprimarycontacttitlecodeid
        //
        _householdprimarycontacttitlecodeid.Name = "HOUSEHOLD_PRIMARYCONTACT_TITLECODEID";
        _householdprimarycontacttitlecodeid.Caption = "New household primary contact title";
        _householdprimarycontacttitlecodeid.CodeTableName = "TITLECODE";
        this.Fields.Add(_householdprimarycontacttitlecodeid);
        //
        //_householdprimarycontactsuffixcodeid
        //
        _householdprimarycontactsuffixcodeid.Name = "HOUSEHOLD_PRIMARYCONTACT_SUFFIXCODEID";
        _householdprimarycontactsuffixcodeid.Caption = "New household primary contact suffix";
        _householdprimarycontactsuffixcodeid.CodeTableName = "SUFFIXCODE";
        this.Fields.Add(_householdprimarycontactsuffixcodeid);
        //
        //_householdprimarycontactcopyhouseholdcontact
        //
        _householdprimarycontactcopyhouseholdcontact.Name = "HOUSEHOLD_PRIMARYCONTACT_COPYHOUSEHOLDCONTACT";
        _householdprimarycontactcopyhouseholdcontact.Caption = "New household primary contact copy household contact information";
        this.Fields.Add(_householdprimarycontactcopyhouseholdcontact);
        //
        //_householdsecondmemberid
        //
        _householdsecondmemberid.Name = "HOUSEHOLD_SECONDMEMBERID";
        _householdsecondmemberid.Caption = "Existing second household member";
        _householdsecondmemberid.SearchListId = new System.Guid("4685952f-6964-486c-9acd-5560a8a30862");
        this.Fields.Add(_householdsecondmemberid);
        //
        //_householdsecondmemberkeyname
        //
        _householdsecondmemberkeyname.Name = "HOUSEHOLD_SECONDMEMBER_KEYNAME";
        _householdsecondmemberkeyname.Caption = "New second household member last name";
        this.Fields.Add(_householdsecondmemberkeyname);
        //
        //_householdsecondmemberfirstname
        //
        _householdsecondmemberfirstname.Name = "HOUSEHOLD_SECONDMEMBER_FIRSTNAME";
        _householdsecondmemberfirstname.Caption = "New second household member first name";
        this.Fields.Add(_householdsecondmemberfirstname);
        //
        //_householdsecondmembermiddlename
        //
        _householdsecondmembermiddlename.Name = "HOUSEHOLD_SECONDMEMBER_MIDDLENAME";
        _householdsecondmembermiddlename.Caption = "New second household member middle initial";
        this.Fields.Add(_householdsecondmembermiddlename);
        //
        //_householdsecondmembertitlecodeid
        //
        _householdsecondmembertitlecodeid.Name = "HOUSEHOLD_SECONDMEMBER_TITLECODEID";
        _householdsecondmembertitlecodeid.Caption = "New second household member title";
        _householdsecondmembertitlecodeid.CodeTableName = "TITLECODE";
        this.Fields.Add(_householdsecondmembertitlecodeid);
        //
        //_householdsecondmembersuffixcodeid
        //
        _householdsecondmembersuffixcodeid.Name = "HOUSEHOLD_SECONDMEMBER_SUFFIXCODEID";
        _householdsecondmembersuffixcodeid.Caption = "New second household member suffix";
        _householdsecondmembersuffixcodeid.CodeTableName = "SUFFIXCODE";
        this.Fields.Add(_householdsecondmembersuffixcodeid);
        //
        //_householdsecondmembercopyhouseholdcontact
        //
        _householdsecondmembercopyhouseholdcontact.Name = "HOUSEHOLD_SECONDMEMBER_COPYHOUSEHOLDCONTACT";
        _householdsecondmembercopyhouseholdcontact.Caption = "New second household member copy household contact information";
        this.Fields.Add(_householdsecondmembercopyhouseholdcontact);
        //
        //_householdsecondmemberrelationshipreciprocaltypecodeid
        //
        _householdsecondmemberrelationshipreciprocaltypecodeid.Name = "HOUSEHOLD_SECONDMEMBER_RELATIONSHIP_RECIPROCALTYPECODEID";
        _householdsecondmemberrelationshipreciprocaltypecodeid.Caption = "Household members reciprocal relationship type";
        _householdsecondmemberrelationshipreciprocaltypecodeid.CodeTableName = "RELATIONSHIPTYPECODE";
        this.Fields.Add(_householdsecondmemberrelationshipreciprocaltypecodeid);
        //
        //_householdsecondmemberrelationshiprelationshiptypecodeid
        //
        _householdsecondmemberrelationshiprelationshiptypecodeid.Name = "HOUSEHOLD_SECONDMEMBER_RELATIONSHIP_RELATIONSHIPTYPECODEID";
        _householdsecondmemberrelationshiprelationshiptypecodeid.Caption = "Household members relationship type";
        _householdsecondmemberrelationshiprelationshiptypecodeid.CodeTableName = "RELATIONSHIPTYPECODE";
        this.Fields.Add(_householdsecondmemberrelationshiprelationshiptypecodeid);
        //
        //_householdsecondmemberrelationshipstartdate
        //
        _householdsecondmemberrelationshipstartdate.Name = "HOUSEHOLD_SECONDMEMBER_RELATIONSHIP_STARTDATE";
        _householdsecondmemberrelationshipstartdate.Caption = "Household members relationship start date";
        this.Fields.Add(_householdsecondmemberrelationshipstartdate);
        //
        //_householdsecondmemberrelationshipisspouse
        //
        _householdsecondmemberrelationshipisspouse.Name = "HOUSEHOLD_SECONDMEMBER_RELATIONSHIP_ISSPOUSE";
        _householdsecondmemberrelationshipisspouse.Caption = "Households members relationship is spousal";
        this.Fields.Add(_householdsecondmemberrelationshipisspouse);

		OnCreated();

	}

    /// <summary>
    /// Is organization
    /// </summary>
    [System.ComponentModel.Description("Is organization")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.BooleanField @ISORGANIZATION {
		get { return _isorganization; }
	}

    /// <summary>
    /// Is group
    /// </summary>
    [System.ComponentModel.Description("Is group")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.BooleanField @ISGROUP {
		get { return _isgroup; }
	}

    /// <summary>
    /// Is household
    /// </summary>
    [System.ComponentModel.Description("Is household")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.BooleanField @ISHOUSEHOLD {
		get { return _ishousehold; }
	}

    /// <summary>
    /// Last\org\group\household name
    /// </summary>
    [System.ComponentModel.Description("Last\\org\\group\\household name")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @LASTNAME {
		get { return _lastname; }
	}

    /// <summary>
    /// First name
    /// </summary>
    [System.ComponentModel.Description("First name")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @FIRSTNAME {
		get { return _firstname; }
	}

    /// <summary>
    /// Middle name
    /// </summary>
    [System.ComponentModel.Description("Middle name")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @MIDDLENAME {
		get { return _middlename; }
	}

    /// <summary>
    /// Title
    /// </summary>
    [System.ComponentModel.Description("Title")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.CodeTableField @TITLECODEID {
		get { return _titlecodeid; }
	}

    /// <summary>
    /// Suffix
    /// </summary>
    [System.ComponentModel.Description("Suffix")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.CodeTableField @SUFFIXCODEID {
		get { return _suffixcodeid; }
	}

    /// <summary>
    /// Nickname
    /// </summary>
    [System.ComponentModel.Description("Nickname")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @NICKNAME {
		get { return _nickname; }
	}

    /// <summary>
    /// Maiden name
    /// </summary>
    [System.ComponentModel.Description("Maiden name")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @MAIDENNAME {
		get { return _maidenname; }
	}

    /// <summary>
    /// Birth date
    /// </summary>
    [System.ComponentModel.Description("Birth date")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.FuzzyDateField @BIRTHDATE {
		get { return _birthdate; }
	}

    /// <summary>
    /// Gender
    /// </summary>
    [System.ComponentModel.Description("Gender")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.ValueListField<System.Nullable<GENDERCODES>> @GENDERCODE {
		get { return _gendercode; }
	}

    /// <summary>
    /// Marital status
    /// </summary>
    [System.ComponentModel.Description("Marital status")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.CodeTableField @MARITALSTATUSCODEID {
		get { return _maritalstatuscodeid; }
	}

    /// <summary>
    /// Website
    /// </summary>
    [System.ComponentModel.Description("Website")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @WEBADDRESS {
		get { return _webaddress; }
	}

    /// <summary>
    /// Industry
    /// </summary>
    [System.ComponentModel.Description("Industry")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.CodeTableField @INDUSTRYCODEID {
		get { return _industrycodeid; }
	}

    /// <summary>
    /// No. of employees
    /// </summary>
    [System.ComponentModel.Description("No. of employees")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.IntegerField @NUMEMPLOYEES {
		get { return _numemployees; }
	}

    /// <summary>
    /// No. of subsidiary orgs
    /// </summary>
    [System.ComponentModel.Description("No. of subsidiary orgs")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.IntegerField @NUMSUBSIDIARIES {
		get { return _numsubsidiaries; }
	}

    /// <summary>
    /// Parent org
    /// </summary>
    [System.ComponentModel.Description("Parent org")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.SearchListField<System.Guid> @PARENTCORPID {
		get { return _parentcorpid; }
	}

    /// <summary>
    /// Address type
    /// </summary>
    [System.ComponentModel.Description("Address type")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.CodeTableField @ADDRESS_ADDRESSTYPECODEID {
		get { return _addressaddresstypecodeid; }
	}

    /// <summary>
    /// Country
    /// </summary>
    [System.ComponentModel.Description("Country")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid> @ADDRESS_COUNTRYID {
		get { return _addresscountryid; }
	}

    /// <summary>
    /// Address
    /// </summary>
    [System.ComponentModel.Description("Address")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @ADDRESS_ADDRESSBLOCK {
		get { return _addressaddressblock; }
	}

    /// <summary>
    /// City
    /// </summary>
    [System.ComponentModel.Description("City")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @ADDRESS_CITY {
		get { return _addresscity; }
	}

    /// <summary>
    /// State
    /// </summary>
    [System.ComponentModel.Description("State")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid> @ADDRESS_STATEID {
		get { return _addressstateid; }
	}

    /// <summary>
    /// ZIP
    /// </summary>
    [System.ComponentModel.Description("ZIP")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @ADDRESS_POSTCODE {
		get { return _addresspostcode; }
	}

    /// <summary>
    /// Do not send mail to this address
    /// </summary>
    [System.ComponentModel.Description("Do not send mail to this address")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.BooleanField @ADDRESS_DONOTMAIL {
		get { return _addressdonotmail; }
	}

    /// <summary>
    /// Phone type
    /// </summary>
    [System.ComponentModel.Description("Phone type")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.CodeTableField @PHONE_PHONETYPECODEID {
		get { return _phonephonetypecodeid; }
	}

    /// <summary>
    /// Phone number
    /// </summary>
    [System.ComponentModel.Description("Phone number")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.PhoneField @PHONE_NUMBER {
		get { return _phonenumber; }
	}

    /// <summary>
    /// Email type
    /// </summary>
    [System.ComponentModel.Description("Email type")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.CodeTableField @EMAILADDRESS_EMAILADDRESSTYPECODEID {
		get { return _emailaddressemailaddresstypecodeid; }
	}

    /// <summary>
    /// Email address
    /// </summary>
    [System.ComponentModel.Description("Email address")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @EMAILADDRESS_EMAILADDRESS {
		get { return _emailaddressemailaddress; }
	}

    /// <summary>
    /// Existing constituent
    /// </summary>
    [System.ComponentModel.Description("Existing constituent")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.BooleanField @EXISTINGSPOUSE {
		get { return _existingspouse; }
	}

    /// <summary>
    /// Spouse full name
    /// </summary>
    [System.ComponentModel.Description("Spouse full name")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.SearchListField<System.Guid> @SPOUSEID {
		get { return _spouseid; }
	}

    /// <summary>
    /// Spouse last name
    /// </summary>
    [System.ComponentModel.Description("Spouse last name")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @SPOUSE_LASTNAME {
		get { return _spouselastname; }
	}

    /// <summary>
    /// Spouse first name
    /// </summary>
    [System.ComponentModel.Description("Spouse first name")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @SPOUSE_FIRSTNAME {
		get { return _spousefirstname; }
	}

    /// <summary>
    /// Spouse middle name
    /// </summary>
    [System.ComponentModel.Description("Spouse middle name")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @SPOUSE_MIDDLENAME {
		get { return _spousemiddlename; }
	}

    /// <summary>
    /// Spouse title
    /// </summary>
    [System.ComponentModel.Description("Spouse title")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.CodeTableField @SPOUSE_TITLECODEID {
		get { return _spousetitlecodeid; }
	}

    /// <summary>
    /// Spouse suffix
    /// </summary>
    [System.ComponentModel.Description("Spouse suffix")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.CodeTableField @SPOUSE_SUFFIXCODEID {
		get { return _spousesuffixcodeid; }
	}

    /// <summary>
    /// Spouse nickname
    /// </summary>
    [System.ComponentModel.Description("Spouse nickname")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @SPOUSE_NICKNAME {
		get { return _spousenickname; }
	}

    /// <summary>
    /// Spouse maiden name
    /// </summary>
    [System.ComponentModel.Description("Spouse maiden name")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @SPOUSE_MAIDENNAME {
		get { return _spousemaidenname; }
	}

    /// <summary>
    /// Spouse birth date
    /// </summary>
    [System.ComponentModel.Description("Spouse birth date")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.FuzzyDateField @SPOUSE_BIRTHDATE {
		get { return _spousebirthdate; }
	}

    /// <summary>
    /// Spouse gender
    /// </summary>
    [System.ComponentModel.Description("Spouse gender")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.ValueListField<System.Nullable<SPOUSE_GENDERCODES>> @SPOUSE_GENDERCODE {
		get { return _spousegendercode; }
	}

    /// <summary>
    /// Spouse relationship type
    /// </summary>
    [System.ComponentModel.Description("Spouse relationship type")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.CodeTableField @SPOUSE_RELATIONSHIPTYPECODEID {
		get { return _spouserelationshiptypecodeid; }
	}

    /// <summary>
    /// Spouse reciprocal relationship type
    /// </summary>
    [System.ComponentModel.Description("Spouse reciprocal relationship type")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.CodeTableField @SPOUSE_RECIPROCALTYPECODEID {
		get { return _spousereciprocaltypecodeid; }
	}

    /// <summary>
    /// Spouse start date
    /// </summary>
    [System.ComponentModel.Description("Spouse start date")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.DateField @SPOUSE_STARTDATE {
		get { return _spousestartdate; }
	}

    /// <summary>
    /// Is spouse
    /// </summary>
    [System.ComponentModel.Description("Is spouse")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.BooleanField @SPOUSE_ISSPOUSE {
		get { return _spouseisspouse; }
	}

    /// <summary>
    /// Copy primary information
    /// </summary>
    [System.ComponentModel.Description("Copy primary information")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.BooleanField @COPYPRIMARYINFORMATION {
		get { return _copyprimaryinformation; }
	}

    /// <summary>
    /// Apply recognition credit to individual for constituent's payments
    /// </summary>
    [System.ComponentModel.Description("Apply recognition credit to individual for constituent's payments")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.BooleanField @PRIMARYRELATIONSHIPEXISTS {
		get { return _primaryrelationshipexists; }
	}

    /// <summary>
    /// Primary recognition credit factor
    /// </summary>
    [System.ComponentModel.Description("Primary recognition credit factor")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.DecimalField @PRIMARYMATCHFACTOR {
		get { return _primarymatchfactor; }
	}

    /// <summary>
    /// Apply recognition credit to constituent for individual's payments
    /// </summary>
    [System.ComponentModel.Description("Apply recognition credit to constituent for individual's payments")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.BooleanField @RECIPROCALRELATIONSHIPEXISTS {
		get { return _reciprocalrelationshipexists; }
	}

    /// <summary>
    /// Reciprocal recognition credit factor
    /// </summary>
    [System.ComponentModel.Description("Reciprocal recognition credit factor")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.DecimalField @RECIPROCALMATCHFACTOR {
		get { return _reciprocalmatchfactor; }
	}

    /// <summary>
    /// Business is existing constituent
    /// </summary>
    [System.ComponentModel.Description("Business is existing constituent")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @EXISTINGBUSINESS {
		get { return _existingbusiness; }
	}

    /// <summary>
    /// Org name
    /// </summary>
    [System.ComponentModel.Description("Org name")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.SearchListField<string> @BUSINESSID {
		get { return _businessid; }
	}

    /// <summary>
    /// Business organization name
    /// </summary>
    [System.ComponentModel.Description("Business organization name")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @BUSINESS_NAME {
		get { return _businessname; }
	}

    /// <summary>
    /// Business address type
    /// </summary>
    [System.ComponentModel.Description("Business address type")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.CodeTableField @BUSINESS_ADDRESSTYPECODEID {
		get { return _businessaddresstypecodeid; }
	}

    /// <summary>
    /// Business country
    /// </summary>
    [System.ComponentModel.Description("Business country")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid> @BUSINESS_COUNTRYID {
		get { return _businesscountryid; }
	}

    /// <summary>
    /// Business address
    /// </summary>
    [System.ComponentModel.Description("Business address")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @BUSINESS_ADDRESSBLOCK {
		get { return _businessaddressblock; }
	}

    /// <summary>
    /// Business city
    /// </summary>
    [System.ComponentModel.Description("Business city")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @BUSINESS_CITY {
		get { return _businesscity; }
	}

    /// <summary>
    /// Business state
    /// </summary>
    [System.ComponentModel.Description("Business state")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid> @BUSINESS_STATEID {
		get { return _businessstateid; }
	}

    /// <summary>
    /// Business ZIP
    /// </summary>
    [System.ComponentModel.Description("Business ZIP")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @BUSINESS_POSTCODE {
		get { return _businesspostcode; }
	}

    /// <summary>
    /// Business do not send mail to this address
    /// </summary>
    [System.ComponentModel.Description("Business do not send mail to this address")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.BooleanField @BUSINESS_DONOTMAIL {
		get { return _businessdonotmail; }
	}

    /// <summary>
    /// Business phone type
    /// </summary>
    [System.ComponentModel.Description("Business phone type")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.CodeTableField @BUSINESS_PHONETYPECODEID {
		get { return _businessphonetypecodeid; }
	}

    /// <summary>
    /// Business phone number
    /// </summary>
    [System.ComponentModel.Description("Business phone number")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.PhoneField @BUSINESS_NUMBER {
		get { return _businessnumber; }
	}

    /// <summary>
    /// Business relationship type
    /// </summary>
    [System.ComponentModel.Description("Business relationship type")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.CodeTableField @BUSINESS_RELATIONSHIPTYPECODEID {
		get { return _businessrelationshiptypecodeid; }
	}

    /// <summary>
    /// Business reciprocal relationship type
    /// </summary>
    [System.ComponentModel.Description("Business reciprocal relationship type")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.CodeTableField @BUSINESS_RECIPROCALTYPECODEID {
		get { return _businessreciprocaltypecodeid; }
	}

    /// <summary>
    /// Business start date
    /// </summary>
    [System.ComponentModel.Description("Business start date")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.DateField @BUSINESS_STARTDATE {
		get { return _businessstartdate; }
	}

    /// <summary>
    /// Is contact
    /// </summary>
    [System.ComponentModel.Description("Is contact")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.BooleanField @ISCONTACT {
		get { return _iscontact; }
	}

    /// <summary>
    /// Contact type
    /// </summary>
    [System.ComponentModel.Description("Contact type")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.CodeTableField @CONTACTTYPECODEID {
		get { return _contacttypecodeid; }
	}

    /// <summary>
    /// Primary contact
    /// </summary>
    [System.ComponentModel.Description("Primary contact")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.BooleanField @ISPRIMARYCONTACT {
		get { return _isprimarycontact; }
	}

    /// <summary>
    /// Position
    /// </summary>
    [System.ComponentModel.Description("Position")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @POSITION {
		get { return _position; }
	}

    /// <summary>
    /// This organization will match individual's contributions
    /// </summary>
    [System.ComponentModel.Description("This organization will match individual's contributions")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.BooleanField @ISMATCHINGGIFTRELATIONSHIP {
		get { return _ismatchinggiftrelationship; }
	}

    /// <summary>
    /// Gives anonymously
    /// </summary>
    [System.ComponentModel.Description("Gives anonymously")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.BooleanField @GIVESANONYMOUSLY {
		get { return _givesanonymously; }
	}

    /// <summary>
    /// Group\household description
    /// </summary>
    [System.ComponentModel.Description("Group\\household description")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @GROUP_DESCRIPTION {
		get { return _groupdescription; }
	}

    /// <summary>
    /// Group primary contact
    /// </summary>
    [System.ComponentModel.Description("Group primary contact")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.SearchListField<System.Guid> @GROUP_PRIMARYCONTACT {
		get { return _groupprimarycontact; }
	}

    /// <summary>
    /// Group start date
    /// </summary>
    [System.ComponentModel.Description("Group start date")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.DateField @GROUP_STARTDATE {
		get { return _groupstartdate; }
	}

    /// <summary>
    /// Group type
    /// </summary>
    [System.ComponentModel.Description("Group type")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid> @GROUP_GROUPTYPEID {
		get { return _groupgrouptypeid; }
	}

    /// <summary>
    /// Existing household primary contact
    /// </summary>
    [System.ComponentModel.Description("Existing household primary contact")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.SearchListField<System.Guid> @HOUSEHOLD_PRIMARYCONTACTID {
		get { return _householdprimarycontactid; }
	}

    /// <summary>
    /// New household primary contact last name
    /// </summary>
    [System.ComponentModel.Description("New household primary contact last name")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @HOUSEHOLD_PRIMARYCONTACT_KEYNAME {
		get { return _householdprimarycontactkeyname; }
	}

    /// <summary>
    /// New household primary contact first name
    /// </summary>
    [System.ComponentModel.Description("New household primary contact first name")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @HOUSEHOLD_PRIMARYCONTACT_FIRSTNAME {
		get { return _householdprimarycontactfirstname; }
	}

    /// <summary>
    /// New household primary contact middle initial
    /// </summary>
    [System.ComponentModel.Description("New household primary contact middle initial")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @HOUSEHOLD_PRIMARYCONTACT_MIDDLENAME {
		get { return _householdprimarycontactmiddlename; }
	}

    /// <summary>
    /// New household primary contact title
    /// </summary>
    [System.ComponentModel.Description("New household primary contact title")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.CodeTableField @HOUSEHOLD_PRIMARYCONTACT_TITLECODEID {
		get { return _householdprimarycontacttitlecodeid; }
	}

    /// <summary>
    /// New household primary contact suffix
    /// </summary>
    [System.ComponentModel.Description("New household primary contact suffix")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.CodeTableField @HOUSEHOLD_PRIMARYCONTACT_SUFFIXCODEID {
		get { return _householdprimarycontactsuffixcodeid; }
	}

    /// <summary>
    /// New household primary contact copy household contact information
    /// </summary>
    [System.ComponentModel.Description("New household primary contact copy household contact information")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.BooleanField @HOUSEHOLD_PRIMARYCONTACT_COPYHOUSEHOLDCONTACT {
		get { return _householdprimarycontactcopyhouseholdcontact; }
	}

    /// <summary>
    /// Existing second household member
    /// </summary>
    [System.ComponentModel.Description("Existing second household member")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.SearchListField<System.Guid> @HOUSEHOLD_SECONDMEMBERID {
		get { return _householdsecondmemberid; }
	}

    /// <summary>
    /// New second household member last name
    /// </summary>
    [System.ComponentModel.Description("New second household member last name")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @HOUSEHOLD_SECONDMEMBER_KEYNAME {
		get { return _householdsecondmemberkeyname; }
	}

    /// <summary>
    /// New second household member first name
    /// </summary>
    [System.ComponentModel.Description("New second household member first name")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @HOUSEHOLD_SECONDMEMBER_FIRSTNAME {
		get { return _householdsecondmemberfirstname; }
	}

    /// <summary>
    /// New second household member middle initial
    /// </summary>
    [System.ComponentModel.Description("New second household member middle initial")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @HOUSEHOLD_SECONDMEMBER_MIDDLENAME {
		get { return _householdsecondmembermiddlename; }
	}

    /// <summary>
    /// New second household member title
    /// </summary>
    [System.ComponentModel.Description("New second household member title")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.CodeTableField @HOUSEHOLD_SECONDMEMBER_TITLECODEID {
		get { return _householdsecondmembertitlecodeid; }
	}

    /// <summary>
    /// New second household member suffix
    /// </summary>
    [System.ComponentModel.Description("New second household member suffix")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.CodeTableField @HOUSEHOLD_SECONDMEMBER_SUFFIXCODEID {
		get { return _householdsecondmembersuffixcodeid; }
	}

    /// <summary>
    /// New second household member copy household contact information
    /// </summary>
    [System.ComponentModel.Description("New second household member copy household contact information")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.BooleanField @HOUSEHOLD_SECONDMEMBER_COPYHOUSEHOLDCONTACT {
		get { return _householdsecondmembercopyhouseholdcontact; }
	}

    /// <summary>
    /// Household members reciprocal relationship type
    /// </summary>
    [System.ComponentModel.Description("Household members reciprocal relationship type")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.CodeTableField @HOUSEHOLD_SECONDMEMBER_RELATIONSHIP_RECIPROCALTYPECODEID {
		get { return _householdsecondmemberrelationshipreciprocaltypecodeid; }
	}

    /// <summary>
    /// Household members relationship type
    /// </summary>
    [System.ComponentModel.Description("Household members relationship type")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.CodeTableField @HOUSEHOLD_SECONDMEMBER_RELATIONSHIP_RELATIONSHIPTYPECODEID {
		get { return _householdsecondmemberrelationshiprelationshiptypecodeid; }
	}

    /// <summary>
    /// Household members relationship start date
    /// </summary>
    [System.ComponentModel.Description("Household members relationship start date")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.DateField @HOUSEHOLD_SECONDMEMBER_RELATIONSHIP_STARTDATE {
		get { return _householdsecondmemberrelationshipstartdate; }
	}

    /// <summary>
    /// Households members relationship is spousal
    /// </summary>
    [System.ComponentModel.Description("Households members relationship is spousal")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.BooleanField @HOUSEHOLD_SECONDMEMBER_RELATIONSHIP_ISSPOUSE {
		get { return _householdsecondmemberrelationshipisspouse; }
	}

}


}
