//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by BBUIModelLibrary
//     Version:  4.0.163.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace UM.CustomFx.GratefulPatient.UIModel
{

/// <summary>
/// Represents the UI model for the 'MIMED Data Constituent Search' data form
/// </summary>
[global::Blackbaud.AppFx.UIModeling.Core.SearchListUIModelMetadata("747530a1-be80-4054-a021-d2a599248261", "MIMED Data")]
public partial class @UMHSDataConstituentSearchUIModel : global::Blackbaud.AppFx.UIModeling.Core.SearchListUIModel
{

#region "Enums"

    /// <summary>
    /// Enumerated values for use with the GENDERCODE property
    /// </summary>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.163.0")]
	public enum GENDERCODES : int
	{
        @Unknown = 0,
        @Male = 1,
        @Female = 2
	}

#endregion

#region "Extensibility methods"

	partial void OnCreated();

#endregion

    private global::Blackbaud.AppFx.UIModeling.Core.IntegerField _constituenttype;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _fullname;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _keyname;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _firstname;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _lookupid;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _addressblock;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _city;
    private global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid> _stateid;
    private global::Blackbaud.AppFx.UIModeling.Core.SearchListField<string> _postcode;
    private global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid> _countryid;
    private global::Blackbaud.AppFx.UIModeling.Core.BooleanField _includeinactive;
    private global::Blackbaud.AppFx.UIModeling.Core.BooleanField _includedeceased;
    private global::Blackbaud.AppFx.UIModeling.Core.BooleanField _onlyprimaryaddress;
    private global::Blackbaud.AppFx.UIModeling.Core.BooleanField _exactmatchonly;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _ssn;
    private global::Blackbaud.AppFx.UIModeling.Core.BooleanField _checknickname;
    private global::Blackbaud.AppFx.UIModeling.Core.BooleanField _checkaliases;
    private global::Blackbaud.AppFx.UIModeling.Core.YearField _classof;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _primarybusiness;
    private global::Blackbaud.AppFx.UIModeling.Core.BooleanField _checkmergedconstituents;
    private global::Blackbaud.AppFx.UIModeling.Core.DateField _minimumdate;
    private global::Blackbaud.AppFx.UIModeling.Core.BooleanField _excludecustomgroups;
    private global::Blackbaud.AppFx.UIModeling.Core.BooleanField _excludehouseholds;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _emailaddress;
    private global::Blackbaud.AppFx.UIModeling.Core.BooleanField _includeindividuals;
    private global::Blackbaud.AppFx.UIModeling.Core.BooleanField _includeorganizations;
    private global::Blackbaud.AppFx.UIModeling.Core.BooleanField _includegroups;
    private global::Blackbaud.AppFx.UIModeling.Core.BooleanField _checkalternatelookupids;
    private global::Blackbaud.AppFx.UIModeling.Core.BooleanField _fuzzysearchonname;
    private global::Blackbaud.AppFx.UIModeling.Core.BooleanField _includenonconstituentrecords;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _phonenumber;
    private global::Blackbaud.AppFx.UIModeling.Core.SearchListField<System.Guid> _prospectmanagerid;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _middlename;
    private global::Blackbaud.AppFx.UIModeling.Core.CodeTableField _suffixcodeid;
    private global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid> _constituency;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _sourcecode;
    private global::Blackbaud.AppFx.UIModeling.Core.ValueListField<System.Nullable<GENDERCODES>> _gendercode;
    private global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid> _scu;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _umhsdata;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _mrn;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _cpisequence;
    private global::Blackbaud.AppFx.UIModeling.Core.BooleanField _patientsonly;
    private global::Blackbaud.AppFx.UIModeling.Core.FuzzyDateField _birthdate;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _searchin;
    private global::Blackbaud.AppFx.UIModeling.Core.GroupField _advancedsearchoptionsgroup;
    private global::Blackbaud.AppFx.UIModeling.Core.GenericUIAction _showadvancedoptions;
    private global::Blackbaud.AppFx.UIModeling.Core.GenericUIAction _hideadvancedoptions;

	[System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.163.0")]
	public @UMHSDataConstituentSearchUIModel() : base()
	{


        _constituenttype = new global::Blackbaud.AppFx.UIModeling.Core.IntegerField();
        _fullname = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _keyname = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _firstname = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _lookupid = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _addressblock = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _city = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _stateid = new global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid>();
        _postcode = new global::Blackbaud.AppFx.UIModeling.Core.SearchListField<string>();
        _countryid = new global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid>();
        _includeinactive = new global::Blackbaud.AppFx.UIModeling.Core.BooleanField();
        _includedeceased = new global::Blackbaud.AppFx.UIModeling.Core.BooleanField();
        _onlyprimaryaddress = new global::Blackbaud.AppFx.UIModeling.Core.BooleanField();
        _exactmatchonly = new global::Blackbaud.AppFx.UIModeling.Core.BooleanField();
        _ssn = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _checknickname = new global::Blackbaud.AppFx.UIModeling.Core.BooleanField();
        _checkaliases = new global::Blackbaud.AppFx.UIModeling.Core.BooleanField();
        _classof = new global::Blackbaud.AppFx.UIModeling.Core.YearField();
        _primarybusiness = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _checkmergedconstituents = new global::Blackbaud.AppFx.UIModeling.Core.BooleanField();
        _minimumdate = new global::Blackbaud.AppFx.UIModeling.Core.DateField();
        _excludecustomgroups = new global::Blackbaud.AppFx.UIModeling.Core.BooleanField();
        _excludehouseholds = new global::Blackbaud.AppFx.UIModeling.Core.BooleanField();
        _emailaddress = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _includeindividuals = new global::Blackbaud.AppFx.UIModeling.Core.BooleanField();
        _includeorganizations = new global::Blackbaud.AppFx.UIModeling.Core.BooleanField();
        _includegroups = new global::Blackbaud.AppFx.UIModeling.Core.BooleanField();
        _checkalternatelookupids = new global::Blackbaud.AppFx.UIModeling.Core.BooleanField();
        _fuzzysearchonname = new global::Blackbaud.AppFx.UIModeling.Core.BooleanField();
        _includenonconstituentrecords = new global::Blackbaud.AppFx.UIModeling.Core.BooleanField();
        _phonenumber = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _prospectmanagerid = new global::Blackbaud.AppFx.UIModeling.Core.SearchListField<System.Guid>();
        _middlename = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _suffixcodeid = new global::Blackbaud.AppFx.UIModeling.Core.CodeTableField();
        _constituency = new global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid>();
        _sourcecode = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _gendercode = new global::Blackbaud.AppFx.UIModeling.Core.ValueListField<System.Nullable<GENDERCODES>>();
        _scu = new global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid>();
        _umhsdata = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _mrn = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _cpisequence = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _patientsonly = new global::Blackbaud.AppFx.UIModeling.Core.BooleanField();
        _birthdate = new global::Blackbaud.AppFx.UIModeling.Core.FuzzyDateField();
        _searchin = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _advancedsearchoptionsgroup = new global::Blackbaud.AppFx.UIModeling.Core.GroupField();
        _showadvancedoptions = new global::Blackbaud.AppFx.UIModeling.Core.GenericUIAction();
        _hideadvancedoptions = new global::Blackbaud.AppFx.UIModeling.Core.GenericUIAction();

        this.SearchListId = new System.Guid("747530a1-be80-4054-a021-d2a599248261");
        this.SearchRecordType = "MIMED Data";
        this.FORMHEADER.Value = "MIMED Constituent Search";
        this.TranslationFunctionId = new System.Guid("68ee2516-f46f-45ae-a6c2-e480d0e794d8");
        this.UserInterfaceUrl = "browser/htmlforms/custom/um.customfx.gratefulpatient/UMHSDataConstituentSearch.html";

        //
        //_constituenttype
        //
        _constituenttype.Name = "CONSTITUENTTYPE";
        _constituenttype.Caption = "CONSTITUENTTYPE";
        _constituenttype.Visible = false;
        this.Fields.Add(_constituenttype);
        //
        //_fullname
        //
        _fullname.Name = "FULLNAME";
        _fullname.Caption = "FULLNAME";
        _fullname.Visible = false;
        this.Fields.Add(_fullname);
        //
        //_keyname
        //
        _keyname.Name = "KEYNAME";
        _keyname.Caption = "Last/Org name";
        _keyname.MaxLength = 50;
        this.Fields.Add(_keyname);
        //
        //_firstname
        //
        _firstname.Name = "FIRSTNAME";
        _firstname.Caption = "First name";
        _firstname.MaxLength = 50;
        this.Fields.Add(_firstname);
        //
        //_lookupid
        //
        _lookupid.Name = "LOOKUPID";
        _lookupid.Caption = "Lookup ID";
        _lookupid.MaxLength = 36;
        this.Fields.Add(_lookupid);
        //
        //_addressblock
        //
        _addressblock.Name = "ADDRESSBLOCK";
        _addressblock.Caption = "Address";
        _addressblock.MaxLength = 100;
        this.Fields.Add(_addressblock);
        //
        //_city
        //
        _city.Name = "CITY";
        _city.Caption = "City";
        _city.MaxLength = 100;
        this.Fields.Add(_city);
        //
        //_stateid
        //
        _stateid.Name = "STATEID";
        _stateid.Caption = "State";
        _stateid.SimpleDataListId = new System.Guid("7fa91401-596c-4f7c-936d-6e41683121d7");
        _stateid.Parameters.Add(new global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListParameter("COUNTRYID", "FIELDS!COUNTRYID"));
        this.Fields.Add(_stateid);
        //
        //_postcode
        //
        _postcode.Name = "POSTCODE";
        _postcode.Caption = "ZIP/Postal code";
        _postcode.MaxLength = 20;
        _postcode.SearchListId = new System.Guid("e5de8c33-de58-4dc6-9a13-48be9f03db81");
        _postcode.DisplayTextIsValue = true;
        this.Fields.Add(_postcode);
        //
        //_countryid
        //
        _countryid.Name = "COUNTRYID";
        _countryid.Caption = "Country";
        _countryid.SimpleDataListId = new System.Guid("c9649672-353d-42e8-8c25-4d34bbabfbba");
        this.Fields.Add(_countryid);
        //
        //_includeinactive
        //
        _includeinactive.Name = "INCLUDEINACTIVE";
        _includeinactive.Caption = "Include inactive";
        this.Fields.Add(_includeinactive);
        //
        //_includedeceased
        //
        _includedeceased.Name = "INCLUDEDECEASED";
        _includedeceased.Caption = "Include deceased";
        this.Fields.Add(_includedeceased);
        //
        //_onlyprimaryaddress
        //
        _onlyprimaryaddress.Name = "ONLYPRIMARYADDRESS";
        _onlyprimaryaddress.Caption = "Only search primary addresses";
        _onlyprimaryaddress.Value = true;
        this.Fields.Add(_onlyprimaryaddress);
        //
        //_exactmatchonly
        //
        _exactmatchonly.Name = "EXACTMATCHONLY";
        _exactmatchonly.Caption = "Match all criteria exactly";
        this.Fields.Add(_exactmatchonly);
        //
        //_ssn
        //
        _ssn.Name = "SSN";
        _ssn.Caption = "SSN";
        _ssn.Visible = false;
        _ssn.MaxLength = 20;
        this.Fields.Add(_ssn);
        //
        //_checknickname
        //
        _checknickname.Name = "CHECKNICKNAME";
        _checknickname.Caption = "Check nickname";
        this.Fields.Add(_checknickname);
        //
        //_checkaliases
        //
        _checkaliases.Name = "CHECKALIASES";
        _checkaliases.Caption = "Check aliases";
        this.Fields.Add(_checkaliases);
        //
        //_classof
        //
        _classof.Name = "CLASSOF";
        _classof.Caption = "Primary class year";
        this.Fields.Add(_classof);
        //
        //_primarybusiness
        //
        _primarybusiness.Name = "PRIMARYBUSINESS";
        _primarybusiness.Caption = "Primary business";
        this.Fields.Add(_primarybusiness);
        //
        //_checkmergedconstituents
        //
        _checkmergedconstituents.Name = "CHECKMERGEDCONSTITUENTS";
        _checkmergedconstituents.Caption = "Check merged constituents";
        this.Fields.Add(_checkmergedconstituents);
        //
        //_minimumdate
        //
        _minimumdate.Name = "MINIMUMDATE";
        _minimumdate.Caption = "Minimum date";
        this.Fields.Add(_minimumdate);
        //
        //_excludecustomgroups
        //
        _excludecustomgroups.Name = "EXCLUDECUSTOMGROUPS";
        _excludecustomgroups.Caption = "Exclude custom groups";
        this.Fields.Add(_excludecustomgroups);
        //
        //_excludehouseholds
        //
        _excludehouseholds.Name = "EXCLUDEHOUSEHOLDS";
        _excludehouseholds.Caption = "Exclude households";
        this.Fields.Add(_excludehouseholds);
        //
        //_emailaddress
        //
        _emailaddress.Name = "EMAILADDRESS";
        _emailaddress.Caption = "Email address";
        _emailaddress.MaxLength = 100;
        this.Fields.Add(_emailaddress);
        //
        //_includeindividuals
        //
        _includeindividuals.Name = "INCLUDEINDIVIDUALS";
        _includeindividuals.Caption = "Individuals";
        _includeindividuals.Value = true;
        this.Fields.Add(_includeindividuals);
        //
        //_includeorganizations
        //
        _includeorganizations.Name = "INCLUDEORGANIZATIONS";
        _includeorganizations.Caption = "Organizations";
        _includeorganizations.Value = true;
        this.Fields.Add(_includeorganizations);
        //
        //_includegroups
        //
        _includegroups.Name = "INCLUDEGROUPS";
        _includegroups.Caption = "Groups/Households";
        _includegroups.Value = true;
        this.Fields.Add(_includegroups);
        //
        //_checkalternatelookupids
        //
        _checkalternatelookupids.Name = "CHECKALTERNATELOOKUPIDS";
        _checkalternatelookupids.Caption = "Check alternate lookup IDs";
        this.Fields.Add(_checkalternatelookupids);
        //
        //_fuzzysearchonname
        //
        _fuzzysearchonname.Name = "FUZZYSEARCHONNAME";
        _fuzzysearchonname.Caption = "Include fuzzy search on name";
        this.Fields.Add(_fuzzysearchonname);
        //
        //_includenonconstituentrecords
        //
        _includenonconstituentrecords.Name = "INCLUDENONCONSTITUENTRECORDS";
        _includenonconstituentrecords.Caption = "Include constituents not considered for fundraising purposes";
        _includenonconstituentrecords.Visible = false;
        this.Fields.Add(_includenonconstituentrecords);
        //
        //_phonenumber
        //
        _phonenumber.Name = "PHONENUMBER";
        _phonenumber.Caption = "Phone number";
        this.Fields.Add(_phonenumber);
        //
        //_prospectmanagerid
        //
        _prospectmanagerid.Name = "PROSPECTMANAGERID";
        _prospectmanagerid.Caption = "Prospect manager";
        _prospectmanagerid.SearchListId = new System.Guid("35fa0186-b669-436f-913a-5e9fd5e59982");
        _prospectmanagerid.EnableQuickFind = true;
        this.Fields.Add(_prospectmanagerid);
        //
        //_middlename
        //
        _middlename.Name = "MIDDLENAME";
        _middlename.Caption = "Middle name";
        this.Fields.Add(_middlename);
        //
        //_suffixcodeid
        //
        _suffixcodeid.Name = "SUFFIXCODEID";
        _suffixcodeid.Caption = "Suffix";
        _suffixcodeid.CodeTableName = "SUFFIXCODE";
        this.Fields.Add(_suffixcodeid);
        //
        //_constituency
        //
        _constituency.Name = "CONSTITUENCY";
        _constituency.Caption = "Constituency";
        _constituency.SimpleDataListId = new System.Guid("7821c1ab-3001-485b-aec7-f55749f959e6");
        this.Fields.Add(_constituency);
        //
        //_sourcecode
        //
        _sourcecode.Name = "SOURCECODE";
        _sourcecode.Caption = "Source code";
        this.Fields.Add(_sourcecode);
        //
        //_gendercode
        //
        _gendercode.Name = "GENDERCODE";
        _gendercode.Caption = "Gender";
        _gendercode.DataSource.Add(new global::Blackbaud.AppFx.UIModeling.Core.ValueListItem<System.Nullable<GENDERCODES>> {Value = GENDERCODES.@Unknown, Translation = "Unknown"});
        _gendercode.DataSource.Add(new global::Blackbaud.AppFx.UIModeling.Core.ValueListItem<System.Nullable<GENDERCODES>> {Value = GENDERCODES.@Male, Translation = "Male"});
        _gendercode.DataSource.Add(new global::Blackbaud.AppFx.UIModeling.Core.ValueListItem<System.Nullable<GENDERCODES>> {Value = GENDERCODES.@Female, Translation = "Female"});
        this.Fields.Add(_gendercode);
        //
        //_scu
        //
        _scu.Name = "SCU";
        _scu.Caption = "Degree from";
        _scu.SimpleDataListId = new System.Guid("bb0353ee-ac0e-4d80-9fc3-0d4e6202dbf6");
        this.Fields.Add(_scu);
        //
        //_umhsdata
        //
        _umhsdata.Name = "UMHSDATA";
        _umhsdata.Caption = "MIMED Data";
        _umhsdata.MaxLength = 3;
        this.Fields.Add(_umhsdata);
        //
        //_mrn
        //
        _mrn.Name = "MRN";
        _mrn.Caption = "MRN";
        _mrn.MaxLength = 50;
        this.Fields.Add(_mrn);
        //
        //_cpisequence
        //
        _cpisequence.Name = "CPISEQUENCE";
        _cpisequence.Caption = "CPI Sequence";
        _cpisequence.MaxLength = 50;
        this.Fields.Add(_cpisequence);
        //
        //_patientsonly
        //
        _patientsonly.Name = "PATIENTSONLY";
        _patientsonly.Caption = "MIMED Constituents Only";
        this.Fields.Add(_patientsonly);
        //
        //_birthdate
        //
        _birthdate.Name = "BIRTHDATE";
        _birthdate.Caption = "Birth date";
        this.Fields.Add(_birthdate);
        //
        //_searchin
        //
        _searchin.Name = "SEARCHIN";
        _searchin.Caption = "Search in";
        _searchin.DBReadOnly = true;
        this.Fields.Add(_searchin);
        //
        //_advancedsearchoptionsgroup
        //
        _advancedsearchoptionsgroup.Name = "ADVANCEDSEARCHOPTIONSGROUP";
        _advancedsearchoptionsgroup.Caption = "Advanced search options";
        this.Fields.Add(_advancedsearchoptionsgroup);
        //
        //_showadvancedoptions
        //
        _showadvancedoptions.Name = "SHOWADVANCEDOPTIONS";
        _showadvancedoptions.Caption = "Show advanced search options";
        this.Actions.Add(_showadvancedoptions);
        //
        //_hideadvancedoptions
        //
        _hideadvancedoptions.Name = "HIDEADVANCEDOPTIONS";
        _hideadvancedoptions.Caption = "Hide advanced search options";
        this.Actions.Add(_hideadvancedoptions);

		OnCreated();

	}

    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.163.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.IntegerField @CONSTITUENTTYPE {
		get { return _constituenttype; }
	}

    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.163.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @FULLNAME {
		get { return _fullname; }
	}

    /// <summary>
    /// Last/Org name
    /// </summary>
    [System.ComponentModel.Description("Last/Org name")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.163.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @KEYNAME {
		get { return _keyname; }
	}

    /// <summary>
    /// First name
    /// </summary>
    [System.ComponentModel.Description("First name")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.163.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @FIRSTNAME {
		get { return _firstname; }
	}

    /// <summary>
    /// Lookup ID
    /// </summary>
    [System.ComponentModel.Description("Lookup ID")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.163.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @LOOKUPID {
		get { return _lookupid; }
	}

    /// <summary>
    /// Address
    /// </summary>
    [System.ComponentModel.Description("Address")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.163.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @ADDRESSBLOCK {
		get { return _addressblock; }
	}

    /// <summary>
    /// City
    /// </summary>
    [System.ComponentModel.Description("City")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.163.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @CITY {
		get { return _city; }
	}

    /// <summary>
    /// State
    /// </summary>
    [System.ComponentModel.Description("State")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.163.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid> @STATEID {
		get { return _stateid; }
	}

    /// <summary>
    /// ZIP/Postal code
    /// </summary>
    [System.ComponentModel.Description("ZIP/Postal code")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.163.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.SearchListField<string> @POSTCODE {
		get { return _postcode; }
	}

    /// <summary>
    /// Country
    /// </summary>
    [System.ComponentModel.Description("Country")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.163.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid> @COUNTRYID {
		get { return _countryid; }
	}

    /// <summary>
    /// Include inactive
    /// </summary>
    [System.ComponentModel.Description("Include inactive")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.163.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.BooleanField @INCLUDEINACTIVE {
		get { return _includeinactive; }
	}

    /// <summary>
    /// Include deceased
    /// </summary>
    [System.ComponentModel.Description("Include deceased")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.163.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.BooleanField @INCLUDEDECEASED {
		get { return _includedeceased; }
	}

    /// <summary>
    /// Only search primary addresses
    /// </summary>
    [System.ComponentModel.Description("Only search primary addresses")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.163.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.BooleanField @ONLYPRIMARYADDRESS {
		get { return _onlyprimaryaddress; }
	}

    /// <summary>
    /// Match all criteria exactly
    /// </summary>
    [System.ComponentModel.Description("Match all criteria exactly")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.163.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.BooleanField @EXACTMATCHONLY {
		get { return _exactmatchonly; }
	}

    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.163.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @SSN {
		get { return _ssn; }
	}

    /// <summary>
    /// Check nickname
    /// </summary>
    [System.ComponentModel.Description("Check nickname")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.163.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.BooleanField @CHECKNICKNAME {
		get { return _checknickname; }
	}

    /// <summary>
    /// Check aliases
    /// </summary>
    [System.ComponentModel.Description("Check aliases")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.163.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.BooleanField @CHECKALIASES {
		get { return _checkaliases; }
	}

    /// <summary>
    /// Primary class year
    /// </summary>
    [System.ComponentModel.Description("Primary class year")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.163.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.YearField @CLASSOF {
		get { return _classof; }
	}

    /// <summary>
    /// Primary business
    /// </summary>
    [System.ComponentModel.Description("Primary business")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.163.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @PRIMARYBUSINESS {
		get { return _primarybusiness; }
	}

    /// <summary>
    /// Check merged constituents
    /// </summary>
    [System.ComponentModel.Description("Check merged constituents")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.163.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.BooleanField @CHECKMERGEDCONSTITUENTS {
		get { return _checkmergedconstituents; }
	}

    /// <summary>
    /// Minimum date
    /// </summary>
    [System.ComponentModel.Description("Minimum date")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.163.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.DateField @MINIMUMDATE {
		get { return _minimumdate; }
	}

    /// <summary>
    /// Exclude custom groups
    /// </summary>
    [System.ComponentModel.Description("Exclude custom groups")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.163.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.BooleanField @EXCLUDECUSTOMGROUPS {
		get { return _excludecustomgroups; }
	}

    /// <summary>
    /// Exclude households
    /// </summary>
    [System.ComponentModel.Description("Exclude households")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.163.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.BooleanField @EXCLUDEHOUSEHOLDS {
		get { return _excludehouseholds; }
	}

    /// <summary>
    /// Email address
    /// </summary>
    [System.ComponentModel.Description("Email address")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.163.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @EMAILADDRESS {
		get { return _emailaddress; }
	}

    /// <summary>
    /// Individuals
    /// </summary>
    [System.ComponentModel.Description("Individuals")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.163.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.BooleanField @INCLUDEINDIVIDUALS {
		get { return _includeindividuals; }
	}

    /// <summary>
    /// Organizations
    /// </summary>
    [System.ComponentModel.Description("Organizations")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.163.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.BooleanField @INCLUDEORGANIZATIONS {
		get { return _includeorganizations; }
	}

    /// <summary>
    /// Groups/Households
    /// </summary>
    [System.ComponentModel.Description("Groups/Households")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.163.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.BooleanField @INCLUDEGROUPS {
		get { return _includegroups; }
	}

    /// <summary>
    /// Check alternate lookup IDs
    /// </summary>
    [System.ComponentModel.Description("Check alternate lookup IDs")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.163.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.BooleanField @CHECKALTERNATELOOKUPIDS {
		get { return _checkalternatelookupids; }
	}

    /// <summary>
    /// Include fuzzy search on name
    /// </summary>
    [System.ComponentModel.Description("Include fuzzy search on name")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.163.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.BooleanField @FUZZYSEARCHONNAME {
		get { return _fuzzysearchonname; }
	}

    /// <summary>
    /// Include constituents not considered for fundraising purposes
    /// </summary>
    [System.ComponentModel.Description("Include constituents not considered for fundraising purposes")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.163.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.BooleanField @INCLUDENONCONSTITUENTRECORDS {
		get { return _includenonconstituentrecords; }
	}

    /// <summary>
    /// Phone number
    /// </summary>
    [System.ComponentModel.Description("Phone number")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.163.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @PHONENUMBER {
		get { return _phonenumber; }
	}

    /// <summary>
    /// Prospect manager
    /// </summary>
    [System.ComponentModel.Description("Prospect manager")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.163.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.SearchListField<System.Guid> @PROSPECTMANAGERID {
		get { return _prospectmanagerid; }
	}

    /// <summary>
    /// Middle name
    /// </summary>
    [System.ComponentModel.Description("Middle name")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.163.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @MIDDLENAME {
		get { return _middlename; }
	}

    /// <summary>
    /// Suffix
    /// </summary>
    [System.ComponentModel.Description("Suffix")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.163.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.CodeTableField @SUFFIXCODEID {
		get { return _suffixcodeid; }
	}

    /// <summary>
    /// Constituency
    /// </summary>
    [System.ComponentModel.Description("Constituency")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.163.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid> @CONSTITUENCY {
		get { return _constituency; }
	}

    /// <summary>
    /// Source code
    /// </summary>
    [System.ComponentModel.Description("Source code")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.163.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @SOURCECODE {
		get { return _sourcecode; }
	}

    /// <summary>
    /// Gender
    /// </summary>
    [System.ComponentModel.Description("Gender")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.163.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.ValueListField<System.Nullable<GENDERCODES>> @GENDERCODE {
		get { return _gendercode; }
	}

    /// <summary>
    /// Degree from
    /// </summary>
    [System.ComponentModel.Description("Degree from")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.163.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid> @SCU {
		get { return _scu; }
	}

    /// <summary>
    /// MIMED Data
    /// </summary>
    [System.ComponentModel.Description("MIMED Data")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.163.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @UMHSDATA {
		get { return _umhsdata; }
	}

    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.163.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @MRN {
		get { return _mrn; }
	}

    /// <summary>
    /// CPI Sequence
    /// </summary>
    [System.ComponentModel.Description("CPI Sequence")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.163.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @CPISEQUENCE {
		get { return _cpisequence; }
	}

    /// <summary>
    /// UMHS Constituents Only
    /// </summary>
    [System.ComponentModel.Description("MIMED Constituents Only")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.163.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.BooleanField @PATIENTSONLY {
		get { return _patientsonly; }
	}

    /// <summary>
    /// Birth date
    /// </summary>
    [System.ComponentModel.Description("Birth date")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.163.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.FuzzyDateField @BIRTHDATE {
		get { return _birthdate; }
	}

    /// <summary>
    /// Search in
    /// </summary>
    [System.ComponentModel.Description("Search in")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.163.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @SEARCHIN {
		get { return _searchin; }
	}

    /// <summary>
    /// Advanced search options
    /// </summary>
    [System.ComponentModel.Description("Advanced search options")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.163.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.GroupField @ADVANCEDSEARCHOPTIONSGROUP {
		get { return _advancedsearchoptionsgroup; }
	}

    /// <summary>
    /// Show advanced search options
    /// </summary>
    [System.ComponentModel.Description("Show advanced search options")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.163.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.GenericUIAction @SHOWADVANCEDOPTIONS {
		get { return _showadvancedoptions; }
	}

    /// <summary>
    /// Hide advanced search options
    /// </summary>
    [System.ComponentModel.Description("Hide advanced search options")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.163.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.GenericUIAction @HIDEADVANCEDOPTIONS {
		get { return _hideadvancedoptions; }
	}


}


}
