//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by BBUIModelLibrary
//     Version:  4.0.165.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace UM.CustomFx.GratefulPatient.UIModel
{

/// <summary>
/// Represents the UI model for the 'UMHSInteractionCopyINTERACTIONS' data form
/// </summary>
public partial class @UMHSInteractionCopyINTERACTIONSUIModel : global::Blackbaud.AppFx.UIModeling.Core.UIModel
{

#region "Extensibility methods"

	partial void OnCreated();

#endregion

    private global::Blackbaud.AppFx.UIModeling.Core.GuidField _id;
    private global::Blackbaud.AppFx.UIModeling.Core.BooleanField _selected;
    private global::Blackbaud.AppFx.UIModeling.Core.DateField _date;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _status;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _category;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _subcategory;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _summary;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _contactmethod;

	[System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public @UMHSInteractionCopyINTERACTIONSUIModel() : base()
	{


        _id = new global::Blackbaud.AppFx.UIModeling.Core.GuidField();
        _selected = new global::Blackbaud.AppFx.UIModeling.Core.BooleanField();
        _date = new global::Blackbaud.AppFx.UIModeling.Core.DateField();
        _status = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _category = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _subcategory = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _summary = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _contactmethod = new global::Blackbaud.AppFx.UIModeling.Core.StringField();

        //
        //_id
        //
        _id.Name = "ID";
        _id.Caption = "ID";
        _id.Visible = false;
        this.Fields.Add(_id);
        //
        //_selected
        //
        _selected.Name = "SELECTED";
        _selected.Caption = "Selected";
        this.Fields.Add(_selected);
        //
        //_date
        //
        _date.Name = "DATE";
        _date.Caption = "Date";
        _date.DBReadOnly = true;
        this.Fields.Add(_date);
        //
        //_status
        //
        _status.Name = "STATUS";
        _status.Caption = "Status";
        _status.DBReadOnly = true;
        this.Fields.Add(_status);
        //
        //_category
        //
        _category.Name = "CATEGORY";
        _category.Caption = "Category";
        _category.DBReadOnly = true;
        this.Fields.Add(_category);
        //
        //_subcategory
        //
        _subcategory.Name = "SUBCATEGORY";
        _subcategory.Caption = "Sub category";
        _subcategory.DBReadOnly = true;
        this.Fields.Add(_subcategory);
        //
        //_summary
        //
        _summary.Name = "SUMMARY";
        _summary.Caption = "Summary";
        _summary.DBReadOnly = true;
        this.Fields.Add(_summary);
        //
        //_contactmethod
        //
        _contactmethod.Name = "CONTACTMETHOD";
        _contactmethod.Caption = "Contact method";
        _contactmethod.DBReadOnly = true;
        this.Fields.Add(_contactmethod);

		OnCreated();

	}

    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.GuidField @ID {
		get { return _id; }
	}

    /// <summary>
    /// Selected
    /// </summary>
    [System.ComponentModel.Description("Selected")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.BooleanField @SELECTED {
		get { return _selected; }
	}

    /// <summary>
    /// Date
    /// </summary>
    [System.ComponentModel.Description("Date")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.DateField @DATE {
		get { return _date; }
	}

    /// <summary>
    /// Status
    /// </summary>
    [System.ComponentModel.Description("Status")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @STATUS {
		get { return _status; }
	}

    /// <summary>
    /// Category
    /// </summary>
    [System.ComponentModel.Description("Category")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @CATEGORY {
		get { return _category; }
	}

    /// <summary>
    /// Sub category
    /// </summary>
    [System.ComponentModel.Description("Sub category")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @SUBCATEGORY {
		get { return _subcategory; }
	}

    /// <summary>
    /// Summary
    /// </summary>
    [System.ComponentModel.Description("Summary")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @SUMMARY {
		get { return _summary; }
	}

    /// <summary>
    /// Contact method
    /// </summary>
    [System.ComponentModel.Description("Contact method")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.165.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @CONTACTMETHOD {
		get { return _contactmethod; }
	}

}


}
