//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by BBUIModelLibrary
//     Version:  4.0.159.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace UM.CustomFx.GratefulPatient.UIModel
{

/// <summary>
/// Represents the UI model for the 'UMHS Address Add Form' data form
/// </summary>
[global::Blackbaud.AppFx.UIModeling.Core.DataFormUIModelMetadata(global::Blackbaud.AppFx.UIModeling.Core.DataFormMode.Add, "0df28b0a-7d6a-417b-a990-1218ac17c55b", "76d17156-002d-415d-a534-23ba9529025d", "MIMED Address", "MIMED Data")]
public partial class @UMHSAddressFormUIModel : global::Blackbaud.AppFx.UIModeling.Core.DataFormUIModel
{

#region "Extensibility methods"

	partial void OnCreated();

#endregion

    private global::Blackbaud.AppFx.UIModeling.Core.CodeTableField _addresstypecodeid;
    private global::Blackbaud.AppFx.UIModeling.Core.BooleanField _isprimary;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _addressblock;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _city;
    private global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid> _stateid;
    private global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid> _countryid;
    private global::Blackbaud.AppFx.UIModeling.Core.SearchListField<string> _postcode;
    private global::Blackbaud.AppFx.UIModeling.Core.BooleanField _donotmail;
    private global::Blackbaud.AppFx.UIModeling.Core.CodeTableField _donotmailreasoncodeid;
    private global::Blackbaud.AppFx.UIModeling.Core.DateField _historicalstartdate;
    private global::Blackbaud.AppFx.UIModeling.Core.DateField _historicalenddate;
    private global::Blackbaud.AppFx.UIModeling.Core.BooleanField _isconfidential;
    private global::Blackbaud.AppFx.UIModeling.Core.CodeTableField _infosourcecodeid;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _infosourcecomments;
    private global::Blackbaud.AppFx.UIModeling.Core.GroupField _addressinformation;
    private global::Blackbaud.AppFx.UIModeling.Core.GroupField _addresssource;

        [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public @UMHSAddressFormUIModel() : base()
	{


        _addresstypecodeid = new global::Blackbaud.AppFx.UIModeling.Core.CodeTableField();
        _isprimary = new global::Blackbaud.AppFx.UIModeling.Core.BooleanField();
        _addressblock = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _city = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _stateid = new global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid>();
        _countryid = new global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid>();
        _postcode = new global::Blackbaud.AppFx.UIModeling.Core.SearchListField<string>();
        _donotmail = new global::Blackbaud.AppFx.UIModeling.Core.BooleanField();
        _donotmailreasoncodeid = new global::Blackbaud.AppFx.UIModeling.Core.CodeTableField();
        _historicalstartdate = new global::Blackbaud.AppFx.UIModeling.Core.DateField();
        _historicalenddate = new global::Blackbaud.AppFx.UIModeling.Core.DateField();
        _isconfidential = new global::Blackbaud.AppFx.UIModeling.Core.BooleanField();
        _infosourcecodeid = new global::Blackbaud.AppFx.UIModeling.Core.CodeTableField();
        _infosourcecomments = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _addressinformation = new global::Blackbaud.AppFx.UIModeling.Core.GroupField();
        _addresssource = new global::Blackbaud.AppFx.UIModeling.Core.GroupField();

        this.Mode = global::Blackbaud.AppFx.UIModeling.Core.DataFormMode.Add;
        this.DataFormTemplateId = new System.Guid("0df28b0a-7d6a-417b-a990-1218ac17c55b");
        this.DataFormInstanceId = new System.Guid("76d17156-002d-415d-a534-23ba9529025d");
        this.RecordType = "MIMED Address";
        this.ContextRecordType = "MIMED Data";
        this.FixedDialog = true;
        this.FORMHEADER.Value = "Add MIMED Address";
        this.UserInterfaceUrl = "browser/htmlforms/custom/um.customfx.gratefulpatient/UMHSAddressForm.html";

        //
        //_addresstypecodeid
        //
        _addresstypecodeid.Name = "ADDRESSTYPECODEID";
        _addresstypecodeid.Caption = "Address type";
        _addresstypecodeid.CodeTableName = "ADDRESSTYPECODE";
        this.Fields.Add(_addresstypecodeid);
        //
        //_isprimary
        //
        _isprimary.Name = "ISPRIMARY";
        _isprimary.Caption = "Is primary";
        this.Fields.Add(_isprimary);
        //
        //_addressblock
        //
        _addressblock.Name = "ADDRESSBLOCK";
        _addressblock.Caption = "Address";
        _addressblock.MaxLength = 150;
        _addressblock.Multiline = true;
        this.Fields.Add(_addressblock);
        //
        //_city
        //
        _city.Name = "CITY";
        _city.Caption = "City";
        _city.MaxLength = 50;
        this.Fields.Add(_city);
        //
        //_stateid
        //
        _stateid.Name = "STATEID";
        _stateid.Caption = "State";
        _stateid.SimpleDataListId = new System.Guid("7fa91401-596c-4f7c-936d-6e41683121d7");
        _stateid.Parameters.Add(new global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListParameter("COUNTRYID", "Fields!COUNTRYID"));
        this.Fields.Add(_stateid);
        //
        //_countryid
        //
        _countryid.Name = "COUNTRYID";
        _countryid.Caption = "Country";
        _countryid.Required = true;
        _countryid.SimpleDataListId = new System.Guid("c9649672-353d-42e8-8c25-4d34bbabfbba");
            _countryid.Value = System.Guid.Parse("27CF0F7D-CDAF-448F-80DE-E9196BF28D36");
        this.Fields.Add(_countryid);
        //
        //_postcode
        //
        _postcode.Name = "POSTCODE";
        _postcode.Caption = "ZIP";
        _postcode.MaxLength = 12;
        _postcode.SearchListId = new System.Guid("e5de8c33-de58-4dc6-9a13-48be9f03db81");
        _postcode.DisplayTextIsValue = true;
        this.Fields.Add(_postcode);
        //
        //_donotmail
        //
        _donotmail.Name = "DONOTMAIL";
        _donotmail.Caption = "Do not send mail to this address";
        this.Fields.Add(_donotmail);
        //
        //_donotmailreasoncodeid
        //
        _donotmailreasoncodeid.Name = "DONOTMAILREASONCODEID";
        _donotmailreasoncodeid.Caption = "Reason";
        _donotmailreasoncodeid.CodeTableName = "DONOTMAILREASONCODE";
        this.Fields.Add(_donotmailreasoncodeid);
        //
        //_historicalstartdate
        //
        _historicalstartdate.Name = "HISTORICALSTARTDATE";
        _historicalstartdate.Caption = "Start date";
        _historicalstartdate.Value = System.DateTime.Today;
        this.Fields.Add(_historicalstartdate);

        //
        //_historicalenddate
        //
        _historicalenddate.Name = "HISTORICALENDDATE";
        _historicalenddate.Caption = "End date";
        this.Fields.Add(_historicalenddate);
        //
        //_isconfidential
        //
        _isconfidential.Name = "ISCONFIDENTIAL";
        _isconfidential.Caption = "Is confidential";
        this.Fields.Add(_isconfidential);
        //
        //_infosourcecodeid
        //
        _infosourcecodeid.Name = "INFOSOURCECODEID";
        _infosourcecodeid.Caption = "Information source";
        _infosourcecodeid.CodeTableName = "INFOSOURCECODE";
        this.Fields.Add(_infosourcecodeid);
        //
        //_infosourcecomments
        //
        _infosourcecomments.Name = "INFOSOURCECOMMENTS";
        _infosourcecomments.Caption = "Comments";
        _infosourcecomments.MaxLength = 256;
        _infosourcecomments.Multiline = true;
        this.Fields.Add(_infosourcecomments);
        //
        //_addressinformation
        //
        _addressinformation.Name = "ADDRESSINFORMATION";
        _addressinformation.Caption = "Address information";
        _addressinformation.Fields.Add("ADDRESSTYPECODEID");
        _addressinformation.Fields.Add("COUNTRYID");
        _addressinformation.Fields.Add("ADDRESSBLOCK");
        _addressinformation.Fields.Add("CITY");
        _addressinformation.Fields.Add("STATEID");
        _addressinformation.Fields.Add("POSTCODE");
        _addressinformation.Fields.Add("ISPRIMARY");
        _addressinformation.Fields.Add("DONOTMAIL");
        _addressinformation.Fields.Add("DONOTMAILREASONCODEID");
        _addressinformation.Fields.Add("ISCONFIDENTIAL");
        this.Fields.Add(_addressinformation);

        //
        //_addresssource
        //
        _addresssource.Name = "ADDRESSSOURCE";
        _addresssource.Caption = "Address Source";
        _addresssource.Fields.Add("INFOSOURCECODEID");
        _addresssource.Fields.Add("INFOSOURCECOMMENTS");
        this.Fields.Add(_addresssource);

        OnCreated();

	}

    /// <summary>
    /// Address type
    /// </summary>
    [System.ComponentModel.Description("Address type")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.CodeTableField @ADDRESSTYPECODEID {
		get { return _addresstypecodeid; }
	}

    /// <summary>
    /// Is primary
    /// </summary>
    [System.ComponentModel.Description("Is primary")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.BooleanField @ISPRIMARY {
		get { return _isprimary; }
	}

    /// <summary>
    /// Address block
    /// </summary>
    [System.ComponentModel.Description("Address block")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @ADDRESSBLOCK {
		get { return _addressblock; }
	}

    /// <summary>
    /// City
    /// </summary>
    [System.ComponentModel.Description("City")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @CITY {
		get { return _city; }
	}

    /// <summary>
    /// State
    /// </summary>
    [System.ComponentModel.Description("State")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid> @STATEID {
		get { return _stateid; }
	}

    /// <summary>
    /// Country
    /// </summary>
    [System.ComponentModel.Description("Country")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid> @COUNTRYID {
		get { return _countryid; }
	}

    /// <summary>
    /// ZIP
    /// </summary>
    [System.ComponentModel.Description("ZIP")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.SearchListField<string> @POSTCODE {
		get { return _postcode; }
	}

    /// <summary>
    /// Do not mail
    /// </summary>
    [System.ComponentModel.Description("Do not mail")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.BooleanField @DONOTMAIL {
		get { return _donotmail; }
	}

    /// <summary>
    /// Do not mail reason
    /// </summary>
    [System.ComponentModel.Description("Do not mail reason")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.CodeTableField @DONOTMAILREASONCODEID {
		get { return _donotmailreasoncodeid; }
	}

    /// <summary>
    /// Start date
    /// </summary>
    [System.ComponentModel.Description("Start date")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.DateField @HISTORICALSTARTDATE {
		get { return _historicalstartdate; }
	}

    /// <summary>
    /// End date
    /// </summary>
    [System.ComponentModel.Description("End date")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.DateField @HISTORICALENDDATE {
		get { return _historicalenddate; }
	}

    /// <summary>
    /// Is confidential
    /// </summary>
    [System.ComponentModel.Description("Is confidential")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.BooleanField @ISCONFIDENTIAL {
		get { return _isconfidential; }
	}

    /// <summary>
    /// Information source
    /// </summary>
    [System.ComponentModel.Description("Information source")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.CodeTableField @INFOSOURCECODEID {
		get { return _infosourcecodeid; }
	}

    /// <summary>
    /// Comments
    /// </summary>
    [System.ComponentModel.Description("Comments")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @INFOSOURCECOMMENTS {
		get { return _infosourcecomments; }
	}

    /// <summary>
    /// Address information
    /// </summary>
    [System.ComponentModel.Description("Address information")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.GroupField @ADDRESSINFORMATION {
		get { return _addressinformation; }
	}

}


}
