//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by BBUIModelLibrary
//     Version:  4.0.159.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace UM.CustomFx.GratefulPatient.UIModel
{

/// <summary>
/// Represents the UI model for the 'UMHS Documentation Add Form' data form
/// </summary>
[global::Blackbaud.AppFx.UIModeling.Core.DataFormUIModelMetadata(global::Blackbaud.AppFx.UIModeling.Core.DataFormMode.Add, "5cc0148b-3314-41a6-912e-81b8fd6308c4", "c1acc6db-8da4-4586-bb88-3e785f88370d", "MIMED Data", "MIMED Data")]
public partial class @UMHSDocumentationFormUIModel : global::Blackbaud.AppFx.UIModeling.Core.DataFormUIModel
{

#region "Extensibility methods"

	partial void OnCreated();

#endregion

    private global::Blackbaud.AppFx.UIModeling.Core.IntegerField _contexttype;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _title;
    private global::Blackbaud.AppFx.UIModeling.Core.DateField _dateentered;
    private global::Blackbaud.AppFx.UIModeling.Core.SearchListField<System.Guid> _authorid;
    private global::Blackbaud.AppFx.UIModeling.Core.CodeTableField _notetypecodeid;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _textnote;
    private global::Blackbaud.AppFx.UIModeling.Core.HtmlField _htmlnote;

	[System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public @UMHSDocumentationFormUIModel() : base()
	{


        _contexttype = new global::Blackbaud.AppFx.UIModeling.Core.IntegerField();
        _title = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _dateentered = new global::Blackbaud.AppFx.UIModeling.Core.DateField();
        _authorid = new global::Blackbaud.AppFx.UIModeling.Core.SearchListField<System.Guid>();
        _notetypecodeid = new global::Blackbaud.AppFx.UIModeling.Core.CodeTableField();
        _textnote = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _htmlnote = new global::Blackbaud.AppFx.UIModeling.Core.HtmlField();

        this.Mode = global::Blackbaud.AppFx.UIModeling.Core.DataFormMode.Add;
        this.DataFormTemplateId = new System.Guid("5cc0148b-3314-41a6-912e-81b8fd6308c4");
        this.DataFormInstanceId = new System.Guid("c1acc6db-8da4-4586-bb88-3e785f88370d");
        this.RecordType = "MIMED Data";
        this.ContextRecordType = "MIMED Data";
        this.FORMHEADER.Value = "Add a note";
        this.UserInterfaceUrl = "browser/htmlforms/custom/um.customfx.gratefulpatient/UMHSDocumentationForm.html";

        //
        //_contexttype
        //
        _contexttype.Name = "CONTEXTTYPE";
        _contexttype.Caption = "Context type";
        _contexttype.Visible = false;
        _contexttype.DBReadOnly = true;
        this.Fields.Add(_contexttype);
        //
        //_title
        //
        _title.Name = "TITLE";
        _title.Caption = "Title";
        _title.Description = "The title of this note";
        _title.MaxLength = 50;
        this.Fields.Add(_title);
        //
        //_dateentered
        //
        _dateentered.Name = "DATEENTERED";
        _dateentered.Caption = "Date";
        _dateentered.Description = "The date this note was entered";
        _dateentered.Required = true;
        this.Fields.Add(_dateentered);
        //
        //_authorid
        //
        _authorid.Name = "AUTHORID";
        _authorid.Caption = "Author";
        _authorid.Description = "The author of this note";
        _authorid.SearchListId = new System.Guid("23c5c603-d7d8-4106-aecc-65392b563887");
        _authorid.EnableQuickFind = true;
        this.Fields.Add(_authorid);
        //
        //_notetypecodeid
        //
        _notetypecodeid.Name = "NOTETYPECODEID";
        _notetypecodeid.Caption = "Type";
        _notetypecodeid.Description = "The user-defined type of this note";
        _notetypecodeid.Required = true;
        _notetypecodeid.CodeTableName = "USR_UMHS_NOTETYPECODE";
        this.Fields.Add(_notetypecodeid);
        //
        //_textnote
        //
        _textnote.Name = "TEXTNOTE";
        _textnote.Caption = "Notes";
        _textnote.Description = "The plain text that comprises this note";
        _textnote.Visible = false;
        this.Fields.Add(_textnote);
        //
        //_htmlnote
        //
        _htmlnote.Name = "HTMLNOTE";
        _htmlnote.Caption = "Notes";
        _htmlnote.Description = "The HTML that comprises this note";
        this.Fields.Add(_htmlnote);

		OnCreated();

	}

    /// <summary>
    /// Context type
    /// </summary>
    [System.ComponentModel.Description("Context type")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.IntegerField @CONTEXTTYPE {
		get { return _contexttype; }
	}

    /// <summary>
    /// The title of this note
    /// </summary>
    [System.ComponentModel.Description("The title of this note")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @TITLE {
		get { return _title; }
	}

    /// <summary>
    /// The date this note was entered
    /// </summary>
    [System.ComponentModel.Description("The date this note was entered")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.DateField @DATEENTERED {
		get { return _dateentered; }
	}

    /// <summary>
    /// The author of this note
    /// </summary>
    [System.ComponentModel.Description("The author of this note")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.SearchListField<System.Guid> @AUTHORID {
		get { return _authorid; }
	}

    /// <summary>
    /// The user-defined type of this note
    /// </summary>
    [System.ComponentModel.Description("The user-defined type of this note")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.CodeTableField @NOTETYPECODEID {
		get { return _notetypecodeid; }
	}

    /// <summary>
    /// The plain text that comprises this note
    /// </summary>
    [System.ComponentModel.Description("The plain text that comprises this note")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @TEXTNOTE {
		get { return _textnote; }
	}

    /// <summary>
    /// The HTML that comprises this note
    /// </summary>
    [System.ComponentModel.Description("The HTML that comprises this note")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.159.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.HtmlField @HTMLNOTE {
		get { return _htmlnote; }
	}

}


}
