//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by BBUIModelLibrary
//     Version:  4.0.163.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace UM.CustomFx.GratefulPatient.UIModel
{

/// <summary>
/// Represents the UI model for the 'USR_USP_SEARCHLIST_UMHS_BATCH_DUPCHECK' data form
/// </summary>
[global::Blackbaud.AppFx.UIModeling.Core.SearchListUIModelMetadata("0724fade-676e-4e54-84ae-8ab6ef10abe6", "MIMED Data")]
public partial class @UMHSBatchDupeCheckUIModel : global::Blackbaud.AppFx.UIModeling.Core.SearchListUIModel
{

#region "Extensibility methods"

	partial void OnCreated();

#endregion

    private global::Blackbaud.AppFx.UIModeling.Core.GuidField _id;
    private global::Blackbaud.AppFx.UIModeling.Core.GuidField _batchid;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _mrn;
    private global::Blackbaud.AppFx.UIModeling.Core.GuidField _batchconstituentid;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _constituentlookupid;
    private global::Blackbaud.AppFx.UIModeling.Core.CodeTableField _titlecodeid;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _firstname;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _middlename;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _lastname;
    private global::Blackbaud.AppFx.UIModeling.Core.CodeTableField _suffixcodeid;
    private global::Blackbaud.AppFx.UIModeling.Core.FuzzyDateField _birthdate;
    private global::Blackbaud.AppFx.UIModeling.Core.CodeTableField _addresstypecodeid;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _addressblock;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _city;
    private global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid> _stateid;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _postcode;
    private global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid> _countryid;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _phonenumber;
    private global::Blackbaud.AppFx.UIModeling.Core.CodeTableField _phonetypecodeid;
    private global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid> _phonecountryid;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _phoneother;
    private global::Blackbaud.AppFx.UIModeling.Core.CodeTableField _phoneothertypecodeid;
    private global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid> _phoneothercountryid;
    private global::Blackbaud.AppFx.UIModeling.Core.EmailAddressField _emailaddress;
    private global::Blackbaud.AppFx.UIModeling.Core.CodeTableField _emailaddresstypecodeid;
    private global::Blackbaud.AppFx.UIModeling.Core.GuidField _duplicaterecordid;
    private global::Blackbaud.AppFx.UIModeling.Core.DecimalField _overallmatchthreshold;
    private global::Blackbaud.AppFx.UIModeling.Core.DecimalField _automatchthreshold;
    private global::Blackbaud.AppFx.UIModeling.Core.BooleanField _domanualreviewforautomatch;
    private global::Blackbaud.AppFx.UIModeling.Core.BooleanField _gotonextrecord;
    private global::Blackbaud.AppFx.UIModeling.Core.GenericUIAction _save;
    private global::Blackbaud.AppFx.UIModeling.Core.GenericUIAction _cancel;

	[System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.163.0")]
	public @UMHSBatchDupeCheckUIModel() : base()
	{


        _id = new global::Blackbaud.AppFx.UIModeling.Core.GuidField();
        _batchid = new global::Blackbaud.AppFx.UIModeling.Core.GuidField();
        _mrn = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _constituentlookupid = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _batchconstituentid = new global::Blackbaud.AppFx.UIModeling.Core.GuidField();
        _titlecodeid = new global::Blackbaud.AppFx.UIModeling.Core.CodeTableField();
        _firstname = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _middlename = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _lastname = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _suffixcodeid = new global::Blackbaud.AppFx.UIModeling.Core.CodeTableField();
        _birthdate = new global::Blackbaud.AppFx.UIModeling.Core.FuzzyDateField();
        _addresstypecodeid = new global::Blackbaud.AppFx.UIModeling.Core.CodeTableField();
        _addressblock = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _city = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _stateid = new global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid>();
        _postcode = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _countryid = new global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid>();
        _phonenumber = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _phonetypecodeid = new global::Blackbaud.AppFx.UIModeling.Core.CodeTableField();
        _phonecountryid = new global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid>();
        _phoneother = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _phoneothertypecodeid = new global::Blackbaud.AppFx.UIModeling.Core.CodeTableField();
        _phoneothercountryid = new global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid>();
        _emailaddress = new global::Blackbaud.AppFx.UIModeling.Core.EmailAddressField();
        _emailaddresstypecodeid = new global::Blackbaud.AppFx.UIModeling.Core.CodeTableField();
        _duplicaterecordid = new global::Blackbaud.AppFx.UIModeling.Core.GuidField();
        _overallmatchthreshold = new global::Blackbaud.AppFx.UIModeling.Core.DecimalField();
        _automatchthreshold = new global::Blackbaud.AppFx.UIModeling.Core.DecimalField();
        _domanualreviewforautomatch = new global::Blackbaud.AppFx.UIModeling.Core.BooleanField();
        _gotonextrecord = new global::Blackbaud.AppFx.UIModeling.Core.BooleanField();
        _save = new global::Blackbaud.AppFx.UIModeling.Core.GenericUIAction();
        _cancel = new global::Blackbaud.AppFx.UIModeling.Core.GenericUIAction();

        this.SearchListId = new System.Guid("0724fade-676e-4e54-84ae-8ab6ef10abe6");
        this.SearchRecordType = "MIMED Data";
        this.FORMHEADER.Value = "MIMED Batch Duplicate Search";
        this.TranslationFunctionId = new System.Guid("e58d466f-1532-4dea-9b50-dd046094ed31");
        this.UserInterfaceUrl = "browser/htmlforms/constituent/duplicatecheck/DuplicateConstituentSearch.html";

        //
        //_id
        //
        _id.Name = "ID";
        _id.Caption = "Constituent";
        _id.Visible = false;
        this.Fields.Add(_id);
        //
        //_batchconstituentid
        //
        _batchconstituentid.Name = "BATCHCONSTITUENTID";
        _batchconstituentid.Caption = "Batch Constituent ID";
        _batchconstituentid.Visible = false;
        this.Fields.Add(_batchconstituentid);
        //
        //_batchid
        //
        _batchid.Name = "BATCHID";
        _batchid.Caption = "BATCHID";
        _batchid.Visible = false;
        this.Fields.Add(_batchid);
        //
        //_mrn
        //
        _mrn.Name = "MRN";
        _mrn.Caption = "MRN";
        _mrn.MaxLength = 50;
        this.Fields.Add(_mrn);
        //
        //_constituentlookupid
        //
        _constituentlookupid.Name = "CONSTITUENTLOOKUPID";
        _constituentlookupid.Caption = "Constituent Lookup ID";
        _constituentlookupid.MaxLength = 200;
        this.Fields.Add(_constituentlookupid);

        //
        //_titlecodeid
        //
        _titlecodeid.Name = "TITLECODEID";
        _titlecodeid.Caption = "Title";
        _titlecodeid.CodeTableName = "TITLECODE";
        this.Fields.Add(_titlecodeid);
        //
        //_firstname
        //
        _firstname.Name = "FIRSTNAME";
        _firstname.Caption = "First name";
        _firstname.MaxLength = 50;
        this.Fields.Add(_firstname);
        //
        //_middlename
        //
        _middlename.Name = "MIDDLENAME";
        _middlename.Caption = "Middle name";
        _middlename.MaxLength = 50;
        this.Fields.Add(_middlename);
        //
        //_lastname
        //
        _lastname.Name = "LASTNAME";
        _lastname.Caption = "Last name";
        _lastname.MaxLength = 100;
        this.Fields.Add(_lastname);
        //
        //_suffixcodeid
        //
        _suffixcodeid.Name = "SUFFIXCODEID";
        _suffixcodeid.Caption = "Suffix";
        _suffixcodeid.CodeTableName = "SUFFIXCODE";
        this.Fields.Add(_suffixcodeid);
        //
        //_birthdate
        //
        _birthdate.Name = "BIRTHDATE";
        _birthdate.Caption = "Birthdate";
        this.Fields.Add(_birthdate);
        //
        //_addresstypecodeid
        //
        _addresstypecodeid.Name = "ADDRESSTYPECODEID";
        _addresstypecodeid.Caption = "Address type code";
        _addresstypecodeid.Category = "Address";
        _addresstypecodeid.CodeTableName = "ADDRESSTYPECODE";
        this.Fields.Add(_addresstypecodeid);
        //
        //_addressblock
        //
        _addressblock.Name = "ADDRESSBLOCK";
        _addressblock.Caption = "Address";
        _addressblock.Category = "Address";
        _addressblock.MaxLength = 500;
        this.Fields.Add(_addressblock);
        //
        //_city
        //
        _city.Name = "CITY";
        _city.Caption = "City";
        _city.Category = "Address";
        _city.MaxLength = 100;
        this.Fields.Add(_city);
        //
        //_stateid
        //
        _stateid.Name = "STATEID";
        _stateid.Caption = "State";
        _stateid.Category = "Address";
        _stateid.SimpleDataListId = new System.Guid("cae6185d-898e-474f-84d1-dadaa4b63ad3");
        this.Fields.Add(_stateid);
        //
        //_postcode
        //
        _postcode.Name = "POSTCODE";
        _postcode.Caption = "Post code";
        _postcode.Category = "Address";
        _postcode.MaxLength = 12;
        this.Fields.Add(_postcode);
        //
        //_countryid
        //
        _countryid.Name = "COUNTRYID";
        _countryid.Caption = "Address country";
        _countryid.Category = "Address";
        _countryid.SimpleDataListId = new System.Guid("5a7ceca8-d00f-497a-ba94-498520028f5c");
        this.Fields.Add(_countryid);
        //
        //_phonenumber
        //
        _phonenumber.Name = "PHONENUMBER";
        _phonenumber.Caption = "Phone";
        _phonenumber.Category = "Phone";
        _phonenumber.MaxLength = 200;
        this.Fields.Add(_phonenumber);
        //
        //_phonetypecodeid
        //
        _phonetypecodeid.Name = "PHONETYPECODEID";
        _phonetypecodeid.Caption = "Phone type code";
        _phonetypecodeid.Category = "Phone";
        _phonetypecodeid.CodeTableName = "PHONETYPECODE";
        this.Fields.Add(_phonetypecodeid);
        //
        //_phonecountryid
        //
        _phonecountryid.Name = "PHONE_COUNTRYID";
        _phonecountryid.Caption = "Phone country";
        _phonecountryid.Category = "Phone";
        _phonecountryid.SimpleDataListId = new System.Guid("5a7ceca8-d00f-497a-ba94-498520028f5c");
        this.Fields.Add(_phonecountryid);
        //
        //_phoneother
        //
        _phoneother.Name = "PHONE_OTHER";
        _phoneother.Caption = "Phone (other)";
        _phoneother.Category = "Phone";
        _phoneother.MaxLength = 200;
        this.Fields.Add(_phoneother);
        //
        //_phoneothertypecodeid
        //
        _phoneothertypecodeid.Name = "PHONE_OTHERTYPECODEID";
        _phoneothertypecodeid.Caption = "Phone (other) type code";
        _phoneothertypecodeid.Category = "Phone";
        _phoneothertypecodeid.CodeTableName = "PHONETYPECODE";
        this.Fields.Add(_phoneothertypecodeid);
        //
        //_phoneothercountryid
        //
        _phoneothercountryid.Name = "PHONE_OTHER_COUNTRYID";
        _phoneothercountryid.Caption = "Phone (other) country";
        _phoneothercountryid.Category = "Phone";
        _phoneothercountryid.SimpleDataListId = new System.Guid("5a7ceca8-d00f-497a-ba94-498520028f5c");
        this.Fields.Add(_phoneothercountryid);
        //
        //_emailaddress
        //
        _emailaddress.Name = "EMAILADDRESS";
        _emailaddress.Caption = "Email address";
        _emailaddress.Category = "Email";
        this.Fields.Add(_emailaddress);
        //
        //_emailaddresstypecodeid
        //
        _emailaddresstypecodeid.Name = "EMAILADDRESSTYPECODEID";
        _emailaddresstypecodeid.Caption = "Email address type code";
        _emailaddresstypecodeid.Category = "Email";
        _emailaddresstypecodeid.CodeTableName = "EMAILADDRESSTYPECODE";
        this.Fields.Add(_emailaddresstypecodeid);
        //
        //_duplicaterecordid
        //
        _duplicaterecordid.Name = "DUPLICATERECORDID";
        _duplicaterecordid.Caption = "DUPLICATERECORDID";
        _duplicaterecordid.Visible = false;
        this.Fields.Add(_duplicaterecordid);
        //
        //_overallmatchthreshold
        //
        _overallmatchthreshold.Name = "OVERALLMATCHTHRESHOLD";
        _overallmatchthreshold.Caption = "Overall match threshold";
        _overallmatchthreshold.Visible = false;
        _overallmatchthreshold.AvailableToClient = false;
        _overallmatchthreshold.Precision = 20;
        _overallmatchthreshold.Scale = 4;
        this.Fields.Add(_overallmatchthreshold);
        //
        //_automatchthreshold
        //
        _automatchthreshold.Name = "AUTOMATCHTHRESHOLD";
        _automatchthreshold.Caption = "Auto match threshold";
        _automatchthreshold.Visible = false;
        _automatchthreshold.AvailableToClient = false;
        _automatchthreshold.Precision = 20;
        _automatchthreshold.Scale = 4;
        this.Fields.Add(_automatchthreshold);
        //
        //_domanualreviewforautomatch
        //
        _domanualreviewforautomatch.Name = "DOMANUALREVIEWFORAUTOMATCH";
        _domanualreviewforautomatch.Caption = "DOMANUALREVIEWFORAUTOMATCH";
        _domanualreviewforautomatch.Visible = false;
        this.Fields.Add(_domanualreviewforautomatch);
        //
        //_gotonextrecord
        //
        _gotonextrecord.Name = "GOTONEXTRECORD";
        _gotonextrecord.Caption = "Automatically go to the next duplicate exception";
        _gotonextrecord.DBReadOnly = true;
        _gotonextrecord.Value = true;
        this.Fields.Add(_gotonextrecord);
        //
        //_save
        //
        _save.Name = "SAVE";
        _save.Caption = "Skip";
        this.Actions.Add(_save);
        //
        //_cancel
        //
        _cancel.Name = "CANCEL";
        _cancel.Caption = "Cancel";
        this.Actions.Add(_cancel);

		OnCreated();

	}

    /// <summary>
    /// Constituent
    /// </summary>
    [System.ComponentModel.Description("Constituent")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.163.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.GuidField @ID {
		get { return _id; }
	}

    /// <summary>
    /// Batch Constituent ID
    /// </summary>
    [System.ComponentModel.Description("Batch Constituent ID")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.163.0")]
    public global::Blackbaud.AppFx.UIModeling.Core.GuidField @BATCHCONSTITUENTID
    {
        get { return _batchconstituentid; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.163.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.GuidField @BATCHID {
		get { return _batchid; }
	}

    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.163.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @MRN {
		get { return _mrn; }
	}

    /// <summary>
    /// Constituent Lookup ID
    /// </summary>
    [System.ComponentModel.Description("Constituent Lookup ID")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.163.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @CONSTITUENTLOOKUPID {
		get { return _constituentlookupid; }
	}

    /// <summary>
    /// Title
    /// </summary>
    [System.ComponentModel.Description("Title")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.163.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.CodeTableField @TITLECODEID {
		get { return _titlecodeid; }
	}

    /// <summary>
    /// First name
    /// </summary>
    [System.ComponentModel.Description("First name")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.163.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @FIRSTNAME {
		get { return _firstname; }
	}

    /// <summary>
    /// Middle name
    /// </summary>
    [System.ComponentModel.Description("Middle name")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.163.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @MIDDLENAME {
		get { return _middlename; }
	}

    /// <summary>
    /// Last name
    /// </summary>
    [System.ComponentModel.Description("Last name")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.163.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @LASTNAME {
		get { return _lastname; }
	}

    /// <summary>
    /// Suffix
    /// </summary>
    [System.ComponentModel.Description("Suffix")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.163.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.CodeTableField @SUFFIXCODEID {
		get { return _suffixcodeid; }
	}

    /// <summary>
    /// Birthdate
    /// </summary>
    [System.ComponentModel.Description("Birthdate")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.163.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.FuzzyDateField @BIRTHDATE {
		get { return _birthdate; }
	}

    /// <summary>
    /// Address type code
    /// </summary>
    [System.ComponentModel.Description("Address type code")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.163.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.CodeTableField @ADDRESSTYPECODEID {
		get { return _addresstypecodeid; }
	}

    /// <summary>
    /// Address
    /// </summary>
    [System.ComponentModel.Description("Address")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.163.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @ADDRESSBLOCK {
		get { return _addressblock; }
	}

    /// <summary>
    /// City
    /// </summary>
    [System.ComponentModel.Description("City")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.163.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @CITY {
		get { return _city; }
	}

    /// <summary>
    /// State
    /// </summary>
    [System.ComponentModel.Description("State")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.163.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid> @STATEID {
		get { return _stateid; }
	}

    /// <summary>
    /// Post code
    /// </summary>
    [System.ComponentModel.Description("Post code")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.163.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @POSTCODE {
		get { return _postcode; }
	}

    /// <summary>
    /// Address country
    /// </summary>
    [System.ComponentModel.Description("Address country")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.163.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid> @COUNTRYID {
		get { return _countryid; }
	}

    /// <summary>
    /// Phone
    /// </summary>
    [System.ComponentModel.Description("Phone")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.163.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @PHONENUMBER {
		get { return _phonenumber; }
	}

    /// <summary>
    /// Phone type code
    /// </summary>
    [System.ComponentModel.Description("Phone type code")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.163.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.CodeTableField @PHONETYPECODEID {
		get { return _phonetypecodeid; }
	}

    /// <summary>
    /// Phone country
    /// </summary>
    [System.ComponentModel.Description("Phone country")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.163.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid> @PHONE_COUNTRYID {
		get { return _phonecountryid; }
	}

    /// <summary>
    /// Phone (other)
    /// </summary>
    [System.ComponentModel.Description("Phone (other)")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.163.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @PHONE_OTHER {
		get { return _phoneother; }
	}

    /// <summary>
    /// Phone (other) type code
    /// </summary>
    [System.ComponentModel.Description("Phone (other) type code")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.163.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.CodeTableField @PHONE_OTHERTYPECODEID {
		get { return _phoneothertypecodeid; }
	}

    /// <summary>
    /// Phone (other) country
    /// </summary>
    [System.ComponentModel.Description("Phone (other) country")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.163.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid> @PHONE_OTHER_COUNTRYID {
		get { return _phoneothercountryid; }
	}

    /// <summary>
    /// Email address
    /// </summary>
    [System.ComponentModel.Description("Email address")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.163.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.EmailAddressField @EMAILADDRESS {
		get { return _emailaddress; }
	}

    /// <summary>
    /// Email address type code
    /// </summary>
    [System.ComponentModel.Description("Email address type code")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.163.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.CodeTableField @EMAILADDRESSTYPECODEID {
		get { return _emailaddresstypecodeid; }
	}

    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.163.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.GuidField @DUPLICATERECORDID {
		get { return _duplicaterecordid; }
	}

    /// <summary>
    /// Overall match threshold
    /// </summary>
    [System.ComponentModel.Description("Overall match threshold")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.163.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.DecimalField @OVERALLMATCHTHRESHOLD {
		get { return _overallmatchthreshold; }
	}

    /// <summary>
    /// Auto match threshold
    /// </summary>
    [System.ComponentModel.Description("Auto match threshold")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.163.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.DecimalField @AUTOMATCHTHRESHOLD {
		get { return _automatchthreshold; }
	}

    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.163.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.BooleanField @DOMANUALREVIEWFORAUTOMATCH {
		get { return _domanualreviewforautomatch; }
	}

    /// <summary>
    /// Automatically go to the next duplicate exception
    /// </summary>
    [System.ComponentModel.Description("Automatically go to the next duplicate exception")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.163.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.BooleanField @GOTONEXTRECORD {
		get { return _gotonextrecord; }
	}

    /// <summary>
    /// Skip
    /// </summary>
    [System.ComponentModel.Description("Skip")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.163.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.GenericUIAction @SAVE {
		get { return _save; }
	}

    /// <summary>
    /// Cancel
    /// </summary>
    [System.ComponentModel.Description("Cancel")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.163.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.GenericUIAction @CANCEL {
		get { return _cancel; }
	}

}


}
